### ISSUE TITLE
Task localization

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent-tasks#1000]
I do see in loc files the following: GENERATED FILE - DO NOT EDIT DIRECTLY
What is the tool behind the generation? How do we approach task localization correctly?

Thanks

**Comment by ericsciple** [comment]
It's integrated with the build process "gulp": https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/contribute.md

I didn't setup the loc process, but I can loop in someone who would know if you need more pointers.

@bryanmacfarlane fyi - not sure if this is something we should add more guidance on in the contribute.md.

**Comment by bryanmacfarlane** [comment]
The build (gulp) takes the task.json, extracts all the string out into an enu strings json file.  It creates a task.loc.json file with the tokens in it that reference the keys in the strings file.  The enu strings file for each task (generated) gets handed off to our loc team every release and they create the strings files for every language we support.  

When a task is uploaded to the server, if it has a task.loc.json file in it, we check the language of the TFS sku, we load the appropriate strings file (and fall back to enu), overlay it and upload that to the server.

Of course we support unlocalized tasks.  If a user wants custom tasks to be localized, they just need a tasks.loc.json file and a strings file for each language.

Here's the code that does it:
https://github.com/Microsoft/vso-agent-tasks/blob/master/package.js 

We also support loc strings at runtime in the tasks.  Details here:
https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md#Localization

**Comment by marag** [comment]
> If a user wants custom tasks to be localized, they just need a tasks.loc.json file and a strings file for each language.

I'm very nooby in all of this, so please excuse for stupid question. I desperately want to localize my custom build task. I've created task.loc.json file next to task.json. I've repeated structure "Strings\resources.resjson\en-US\resources.resjson" like in VSS Tasks  and put some strings in this resource file. 
Then I package with "tfx create extention --loc-root  .\MyTask\Strings --manifest-globs vss-extension.json" .
What I missed? The strings still loads from task.json file.

Thanks for help.

**Comment by ericsciple** [comment]
did the strings make it into the zip file? take a look at the tasks repo, when you build there is a _build folder that contains the final layout for each task. the layout in your zip should be similar

**Comment by bryanmacfarlane** [comment]
Also be aware that it's all about the SKU of the TFS server.  When the task is uploaded, we are going to choose one of the strings to put in the DB and that's the TFS SKU.  ( a build is in a language and that's the lang of the server)

The sku of the VSTS cloud is ENU.

**Comment by ericsciple** [comment]
which execution handler are you using? node or powershell3? each one has a method to load the loc strings, `tl.setResourcePath` and `Import-VstsLocStrings`

**Comment by marag** [comment]
> did the strings make it into the zip file? take a look at the tasks repo, when you build there is a _build folder that contains the final layout for each task. the layout in your zip should be similar

At first I've include 'String' folder in vss-extension.json as one of including paths. It didn't help. Then
I've found how this '--loc-root' argument works in vsix-write.js file.  As I understand in comment says that 'Extension.vsixlangpack' should appear after compilation insight  _$vsix archive_\\_strings's folder_.  Is that right?  Because I doesn't have any .vsixlangpack in archive. That is maybe the cause, but how I can fix it?

**Comment by mmajcica** [comment]
@vCillusion this should be an easy one.

package.js seems not to be present any more. However, localization in the build process is done here, https://github.com/Microsoft/azure-pipelines-tasks/blob/14bd8266326dbe44ad05742ed1598960dedf6d3b/make-util.js#L731

For the documentation see:
https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/docs/azure-pipelines-task-lib.md#Localization
