### ISSUE TITLE
PowerShell L0 unit tests

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent-tasks#1001]
Hi,

it may sound obvious and simple but, how to run all of the PowerShell unit tests?
I have some experience with Pester, but you seem to use some custom cmdlets for mocking and assertions.
How would you execute and check all of the available PosH unit tests?

Thanks

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/runningtests.md

**Comment by mmajcica** [comment]
Does this mean that gulp will invoke PS tests also?

Thanks

**Comment by ericsciple** [comment]
Yes if powershell.exe is in your PATH (will be the case on Windows boxes). Mocha is the test runner for all tests (Node and PowerShell). Each test runs in a separate process (isolation).
