### ISSUE TITLE
Powershell On Remote Computer

### ISSUE THREAD

**Issue by russelldyas** [Microsoft/vso-agent-tasks#1006]
Issue:

I am running PowerShell script on a remote computer when ran locally is outputting to stream using Write-information.  However when the script is run via Release manager it does not output back into the release manager log.
Is there anyway to get this into the stream into the release manager logs?

From

Russell

**Comment by pryenugu** [comment]
Hi @russelldyas , for the remote PowerShell task only Write-Verbose works. So probably something like Write-Verbose "Information String" -Verbose will only work as of now. Warning and information streams do not come back in the logs as of now. Only error and verbose stream work. We are looking to fix this in a later update.

**Comment by russelldyas** [comment]
Thanks yes that has solved it.

Thank you

Russell
