### ISSUE TITLE
Changes to Instantiate-Environment prevent resource groups from deploying without VMs

### ISSUE THREAD

**Issue by TopperKain** [Microsoft/vso-agent-tasks#1019]
in https://github.com/Microsoft/vso-agent-tasks/blob/a6cbe62bc9abe7da8cd1a8b18d41568f6c6ffa5a/Tasks/DeployAzureResourceGroup/Utility.ps1 the change made nov 26 to throw an error if no vms are found broke my previously working deployments. This is currently line 462 throw (Get-LocalizedString -Key "No VMs found in resource group: '{0}'. Could not register environment in the output variable: '{1}'" -ArgumentList $resourceGroupName, $outputVariable) 

I'm using the Azure Resource Group Deployment task with the action of "Create or Update Resource Group"

See the attached template for what I am trying to deploy.

[RedSkyDeployment.json.txt](https://github.com/Microsoft/vso-agent-tasks/files/74526/RedSkyDeployment.json.txt)

**Comment by RoopeshNair** [comment]
Are you setting output variable for the Azure Resource Group Task? The task would fail if there are no VMs in Resource Group and the field Output variable is set. If you don't have need for output variable i.e, you are not using it in subsequent task for example "PowerShell on Target", can you clear the field and re-try?

**Comment by pryenugu** [comment]
I checked your deployment template and I can see that you have no VM's created. Can you try clearing the output variable field in the DeployAzureResourceGroup task as @RoopeshNair has suggested?

**Comment by TopperKain** [comment]
Sorry for the slow response, the holidays got to me :)
I tried that and removing the output variable worked.
Thank you.

Sent from Outlook Mobile

    _____________________________

**Comment by ac4simms** [comment]
I had this issue also, and the same fix worked.

**Comment by NickDarvey** [comment]
What are we supposed to do if we actually need to use the output variable but aren't using any virtual machines? Why was this closed?

**Comment by RoopeshNair** [comment]
@NickDarvey 

We return only the VM details in the output variable. Alternatively you use Azure PowerShell task to query the Resource Group and set it as output variables

**Comment by NickDarvey** [comment]
Ahh, cheers @RoopeshNair 

I'd recommend returning the Azure Resource Manager template's [output section](https://azure.microsoft.com/en-us/documentation/articles/resource-group-authoring-templates/#outputs). As an immediate fix, I'd suggest relabeling this field so it isn't confusing for people who assume it's referring to the template's output or at least adding some more explicit helper text explaining what it actually returns.

Let me know if this isn't in your planned road map and I'll find some time to fork it and implement it.

**Comment by rossedman** [comment]
@RoopeshNair @NickDarvey Confused on this, is this still only returning output for VMs? It seems like it is. What is the recommended process/example for returning outputs from ARM templates that are using PaaS services?

**Comment by NickDarvey** [comment]
@rossedman I ended up adding a PowerShell task after to grab the outputs, e.g.:

```powershell
$outputs = (
	Get-AzureRmResourceGroupDeployment -ResourceGroupName $ResourceGroupName | 
	Where-Object -Property Outputs -ne $null |
	Sort-Object -Property Timestamp |
	Select-Object -Last 1
).Outputs

Write-Host "##vso[task.setvariable variable=Cluster.Name;]$($outputs.clusterName.value)"
Write-Host "##vso[task.setvariable variable=ApiM.ServiceName;]$($outputs.apiName.value)"
```

**Comment by rossedman** [comment]
@NickDarvey Thanks a lot! This is great.
