### ISSUE TITLE
Gulp Task should not demand gulp be globally installed on an agent

### ISSUE THREAD

**Issue by drub0y** [Microsoft/vso-agent-tasks#1035]
The Gulp task has support for executing gulp from the source directory (e.g. node_modules), yet [it still demands that Gulp is installed globally on an agent](https://github.com/Microsoft/vso-agent-tasks/blob/c6ac8b930e5f0c6bbb064398d0d54905c9c21370/Tasks/Gulp/task.json#L18). This means one must, at bare minimum, go add a capability of `gulp` to one's build agents just so they can even be considered candidates for builds that use the Gulp task. Given the way the Gulp task is written, this demand should _not_ be necessary and the only demand the Gulp task should actually make is for `node`.

**Comment by drub0y** [comment]
If this is agreed upon I can easily send a PR to remove the demand from the tasks.json, just let me know.

**Comment by pascalberger** [comment]
It seems like this (and #1036) was fixed by a2ecabd5d9997d3e7b90bc274ef3769ba10a4da5

**Comment by ericsciple** [comment]
Thanks @pascalberger

**Comment by drub0y** [comment]
Cheers guys!
