### ISSUE TITLE
Allow outputs from Azure Resource Group Deployment task to be used in subsequent tasks

### ISSUE THREAD

**Issue by MikalJ** [Microsoft/vso-agent-tasks#1045]
Such as generating the name of a website (and provisioning the resource) with an ARM template, and then using it in an Azure Web App Deployment task

**Comment by s093294** [comment]
Depending on your level of time and powershell knowledge you could make your own powershell script for your deployment and set the output as a variable. 

Write-Host ("##vso[task.setvariable variable=variableName;]$variableValue")

would allow you to use them as $(variableName) in subsequent tasks already now.

**Comment by MikalJ** [comment]
Thanks for the tip Paul.
I tried my hand at your suggestion, and came up with the following script, that I execute with an Azure Powershell task immediatly after the Resource Group Deployment task

```powershell
# Make outputs from resource group deployment available to subsequent tasks
param ([string]$resourceGroup)

$outputs = (Get-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroup | Select -Last 1).Outputs
$outputs.Keys | % { Write-Host ("##vso[task.setvariable variable="+$_+";]"+$outputs[$_].Value) }
```
I'm still very new at powershell, so there's propably plenty of room for improvement.

The only way I've found to access the outputs, is to retrieve the deployment object from azure. Currently the Resource Group Deployment task creates, or overwrites, a deployment with the same name as the resource group being created. If that changes, the script might break.

Note: The dollar sign just before "variableValue", in your tip, is not a part of the format. That caused me quite a bit of head scratching.

**Comment by s093294** [comment]
Sorry about that. $Variablenames are typical powershell variables :) Glad you got it working. 

I am also using Get-AzureRmResourceGroupDeployment to get the deployment object and then setting a variable with the information needed.

**Comment by MisinformedDNA** [comment]
Why was this closed? Was this resolved elsewhere?
