### ISSUE TITLE
Windows Machine File Copy task fails - System error 53 has occurred.

### ISSUE THREAD

**Issue by richardjharding** [Microsoft/vso-agent-tasks#1046]
I'm using the VSTS preview Release Management bits and trying to deploy a web app to a Azure hosted VM

I've created a machine group and was able to prove the connection and permissions etc are correct by using the Configure IIS Application Pool task

But when I try and use the Windows Machine File Copy task it fails with

<pre>
2016-01-07T15:48:34.7216403Z ##[error]Copying failed for resource : myvm.cloudapp.net
 
2016-01-07T15:48:34.7216403Z ##[error]Failed to connect to the path \\myvm.cloudapp.net with the user mydomain\myadmin for copying.
 
2016-01-07T15:48:34.7216403Z ##[error]System error 53 has occurred. 
 
2016-01-07T15:48:34.7216403Z ##[error]The network path was not found.
 
2016-01-07T15:48:34.7216403Z ##[error]For more info please refer to http://aka.ms/windowsfilecopyreadme
</pre>

I've also tried entering the hostname and port and credentials into the task but that fails with the same error

I'm using an agent hosted on another azure VM in the same domain/virtual network

Agent version 1.92.0

I have vnext release templates in the previous version of RM working against the same vm so I know that winrm is correctly configured  - how can I diagnose why this task is failing?

I've not tried the copy to azure vm task yet as I need this to work on premise also

**Comment by kmkumaran** [comment]
Typically Azure VMs are in a separate vnet and may not be reachable for UNC shares. You would want to consider using AzureFileCopy task instead of WindowsFileCopy task while targeting Azure VM.

**Comment by richardjharding** [comment]
thanks I've switched to the AzureFileCopy task which has allowed me to keep moving

**Comment by venky76v** [comment]
Hi, We were able to get WinRM file copy working from the build server to the dev server. But now when we are attempting to use WinRM file from the build server to the UAT server which is in a different VLAN separated by a Firewall (I can say it on a DMZ) we are getting an error "Failed to connect to the path \\server\blah\blah" with the user domain\user for copying System error 53 has occurred, The network path was not found. Any suggestions? It is the Windows machine file copy step that is failing on the release step.

**Comment by heidgert** [comment]
@venky76v Have you been able to solve this? We seem to be having the exact same problem in our environment (Windows Machine File Copy works to our Dev environment but not Test env).
