### ISSUE TITLE
XCode task: Use of quotes in arguments does not seem to get handled properly

### ISSUE THREAD

**Issue by meherkasam** [Microsoft/vso-agent-tasks#1051]
When I pass in a parameter to xcodebuild such as -destination "platform=iOS Simulator,name=iPhone 6", I get the following error: xcodebuild: error: option 'Destination' requires at least one parameter of the form 'key=value'

**Comment by meherkasam** [comment]
Fix from email correspondence with bryanmacfarlane:

On the agent, in the _work folder, there’s an xcode folder with a version folder under that.  It has xcodebuild2.js in it.
 
Around line 192.  Should see this.  Get rid of the delimited word.  Just GetInput.  
 

	functionexecBuild(code) {
	// Add optional additional args
	var args=tl.getDelimitedInput('args', ' ', false); 
	if(args) {
	xcb.arg(args); 
	}
	tl.debug('Complete build args: ');
	for(var arg in xcb.args) {
	tl.debug(xcb.args[arg]);
	}
	return xcb.exec(); 
	}
 
Get delimited splits on space regardless of quotes.  The xcb.arg funtion below that handles quotes properly.  When it printed in the log, it concats the array of args so it looked fine.

**Comment by bryanmacfarlane** [comment]
Thanks!

**Comment by bryanmacfarlane** [comment]
This will be released in a week or so to production

**Comment by miktav** [comment]
I'm still getting this error. I asked a [question](http://stackoverflow.com/questions/43989967/xcodebuild-error-option-destination-requires-at-least-one-parameter-of-the-f) about this on stackoverflow. Any insights?

**Comment by madhurig** [comment]
This specific issue has been resolved in Team Services a while back. I can run tests with the input that you specified _-destination "platform=iOS Simulator,name=iPad Pro (9.7 inch),OS=10.3"_. The input looks right, in additional args put anything with spaces that you want to treat as one argument in "". Please share your build logs for further investigation if you continue to see an issue.

**Comment by miktav** [comment]
Thanks for your reply. My mistake was trying to put the -destination parameter in the Actions box, like this: 
test -destination "platform=iOS Simulator,name=iPad Pro (9.7 inch),OS=10.3"
I didn't see the Arguments box under Advanced. When I put this parameter there, it works! 
What was odd is that it accepted and tried to use the -destination parameter in the Actions box. Perhaps this should be disallowed, or if allowed, handled the same way as when it is in the Arguments box.
Thank you so much for reply. Your comment, "_in additional args_, put anything with spaces", was the clue I needed.

**Comment by madhurig** [comment]
@miktav: Feedback noted! We have been considering having inputs to specify the "Test Options" to not require typing in the destination string.
