### ISSUE TITLE
IIS Web Application Deployment Task Doesn't Remotely Deploy Site

### ISSUE THREAD

**Issue by karlrissland** [Microsoft/vso-agent-tasks#1052]
The IIS Web Application Deployment Tasks Requires that you either copy the WebDeployPackage.ZIP file to the local server or point the to a UNC Share where the WebDeployPackage.ZIP file is located.  This requires you to have an extra step in your build process to copy your files to each server in the server farm, or a UNC Path.... If using Azure IaaS, you need to stand up additional infrastructure if you go the file share route.  

An option should be provided to run MSDeploy on the agent and push the deployment to the remote webserver(s) much like you can do from within visual studio, the command line, or powershell.

Attached is the readme which was created when I published my site.  This allows me to publish to the server, with out having to first move the files to the server or setup a UNC share.
[E2EClassic.deploy-readme.txt](https://github.com/Microsoft/vso-agent-tasks/files/81774/E2EClassic.deploy-readme.txt)

**Comment by richardjharding** [comment]
I second this - especially as I'm currently experiencing issues getting the copy to windows machine task running

**Comment by kmkumaran** [comment]
Thanks for the feedback. We have heard this and it is added in our backlog.
