### ISSUE TITLE
Update Sonar Task to break build

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#1072]
With SonarQube 5.3 a new [Quality Gates Web Service](http://docs.sonarqube.org/display/SONAR/Breaking+the+CI+Build) was introduced which could be called and used to break the build. 

It would be nice it the Sonar Finish task could be enhanced with an option to automatically break the build, which would call the sonar web service after uploading the results and break the build or continue.

**Comment by bgavrilMS** [comment]
Hi @pascalberger - we have this on our backlog in Jira https://jira.sonarsource.com/browse/TBSTFNP-31 but we're still discussing with SonarSource what's the best place for the logic (the tasks / the SQ MSBuild Scanner or the SQ Scanner?)
