### ISSUE TITLE
Automated Test Association

### ISSUE THREAD

**Issue by jochenvangasse** [Microsoft/vso-agent-tasks#1073]
I'm running a build that runs distributed tests, and my build produces a nice test run with results every time.

What I can't seem to get working however, is to associate those test run results to my (automated) test cases.
I have several test cases in different test plans and suites, all of them are associated to the tests via the Associated Automation tab on the Test Case work item, but the results don't seem to get picked up.
Is it still possible to associate automated test run results to test cases?

**Comment by atinb** [comment]
We are currently working on providing the ability to run tests using Test Plans and Test Suites and update the results back. Should be available by mid February on VSTS. Thanks!

**Comment by elangelo** [comment]
aren't we past mid february by now? i can't see anything that provides this on VSTS?

**Comment by atinb** [comment]
The functionality to trigger automated tests using Test Plans and Suites will be available with Sprint 97 deployment which should happen in 2-3 weeks. Thanks!

**Comment by billros** [comment]
Can you provide pointers to documentation on this capability?  I am not seeing any way to specify test plan or suite via the VSTS Run Tests on Test Agents task, nor in the related help files.   Parameters appear to have been added to the RunDistributedTests.ps1 script, but do not appear to be exposed in build step...
