### ISSUE TITLE
how to request new agent task, which still in preview, like web deploy

### ISSUE THREAD

**Issue by iamkarlson** [Microsoft/vso-agent-tasks#1083]
Hi, I'm trying to find web deploy to IIS from vso, but can't. Guys from [stackoverflow](http://stackoverflow.com/questions/34828304/publish-website-from-vso-using-web-deploy?noredirect=1#comment57403288_34828304) suggest me use under-preview feature [IISWebAppDeployment](https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/IISWebAppDeployment), but I haven't found where I can enable it. Also, in your [closed issue](https://github.com/Microsoft/vso-agent-tasks/issues/387), you said that this feature in master and it will be delivered soon...

**Comment by wilson208** [comment]
I would also like to use this feature, even if its currently in Beta! @iamkarlson did you have any luck with this?

**Comment by iamkarlson** [comment]
Yes, I did. Send a email to RM_Customer_Queries@microsoft.com and place
your vso Url in letter with explanations what your want to use, which task

**Comment by mvvsubbu** [comment]
This task is in preview mode and hence for only selected customers we have enabled it in VSTS. We are having plans to move this to extension and hence we stopped enabling it to any new VSTS customer. Our recommendation is to download the task from github and change the task name, guid then upload to your VSTS account. If you need any further assistance send mail to RM_Customer_Queries at Microsoft dot com
