### ISSUE TITLE
Using Copy And Publish Build Artifacts in Release Definition

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#1091]
Is the Copy And Publish Build Artifacts task supposed to work in a Release Definition?

I get the following error:

    2016-01-19T16:02:25.0270578Z ##[error]Cannot bind argument to parameter 'StagingFolder' because it is null.

Which makes sense since it uses the [build.stagingdirectory](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/CopyPublishBuildArtifacts/copypublishbuildartifacts.ts#L103).

In this case I would expect the task to be hidden for release definitions. Isn't the `visibility` node in the `task.json` file for this (which is [set only to build for this task](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/CopyPublishBuildArtifacts/task.json#L9))?

**Comment by pascalberger** [comment]
The same applies for Publish Build Artifact task which also doesn't make much sense in a release definition, since it doesn't seem to be possible to upload an artifact to the server in a release definition (failing with `Unable to find container for build: 1234`)

**Comment by chrisrpatterson** [comment]
I would not expect either of those to work in release in the way they are currently implemented.  It shouldn't be displayed.  We will look into that.

Thanks for bringing this to our attention.
