### ISSUE TITLE
Unhandled: tl._checkPath is not a function

### ISSUE THREAD

**Issue by redbrain17** [Microsoft/vso-agent-tasks#1094]
Hello,

I try to deploy a "Hello World" compiled file with the "cURL Upload Files" Utility. I choose scp as protocol
scp://server:/home/user/test/.  I entered my username and password. I added "hello"  to files

Then I start my Build run, the  Hello World projects gets build but not deployed via scp.
   
    ******************************************************************************
    Running CmdLine
    ******************************************************************************
    /usr/bin/make
    cc -g    hello.c   -o hello
    code is: 0
    ******************************************************************************
    Running cURLUploader
    ******************************************************************************
    Unhandled: tl._checkPath is not a function

Some clue whats wrong here?

**Comment by yacaovsnc** [comment]
Are you running against TFS on premise or against VSTS hosted service?  There is a bug in curl (didn't update the function name while the toolrunner lib has updated the function name) and we fixed it pull request #921.  We should be deploying the fix to VSTS very soon (in days).

**Comment by redbrain17** [comment]
Im running it on local hosted TFS 2015. Thx for the explaination for the root cause.

**Comment by yacaovsnc** [comment]
@redbrain17 in that case it seems you will need to patch the server yourself with https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md

Or manually fix the script in your agent folder.  :(

The fix should be released with TFS 2015 update 2.

**Comment by yacaovsnc** [comment]
Closing the issue since fix has already been checked in.
