### ISSUE TITLE
How to change npm version

### ISSUE THREAD

**Issue by rosieks** [Microsoft/vso-agent-tasks#1097]
I'm trying to update npm on my build machine. I have installed new version by running `npm install npm@3.2.0 -g` but when I look into capabilities it still points to `C:\Program Files (x86)\nodejs\npm.cmd`.

Could you provide some instruction how to change that value? Overriding it via user capabilities doesn't work.

**Comment by bryanmacfarlane** [comment]
actually an npm question  - but ...

capabilities don't matter (just that it has a value).  What's important is it's in the path.

run: where npm

then run npm -v

On one of my machines the installer just did the right thing (cmd in pf pointed to 3.0).  On another it still pointed to 2.0 and I fixed it or removed it (where returned a list).

The other thing to be aware of is it has to be in the path of the account your build agent is running as.  (could run as your identity if it works for you).  

We're working toward a better solution here on our side to avoid needing as a pre-req:  https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/tools.md

**Comment by rosieks** [comment]
Thank's - I didn't know that build process is looking for tools by PATH.
