### ISSUE TITLE
Update build definition variables from within the build using log commands

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vso-agent-tasks#1100]
I read about the logging commands (https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md) which I can use to set variables using 

    "##vso[task.setvariable variable=testvar;]testvalue"

Is it possible to persist these values accross builds? this would allow me to have arbitrary build versions and increment them from within the build process. Perhaps something like

    "##vso[task.setvariable variable=testvar;persist=true]testvalue"

The variables could be stored as build definition variables.

**Comment by chrisrpatterson** [comment]
That is not something we currently support.  It is an interesting feature but you have to be a bit careful as a single build definition can run many builds and they are not necessarily serialized.

**Comment by henning-krause** [comment]
okay. Do you see any other place in TFS where I could store a version number? Should be branch specific. 

Currently I store in a file in the root directory of my branch. But this requires me to perform a check in during the actual build process...
