### ISSUE TITLE
command module does not exist: task.complete

### ISSUE THREAD

**Issue by tonyblues** [Microsoft/vso-agent-tasks#1108]
Recently I am seeing warnings of "command module does not exist: task.complete" for both the CocoaPods and Xcode build tasks. I haven't touched my build definitions for a while so I am wondering if this is caused by some recent updates for those VSO tasks.

Thanks!

**Comment by bryanmacfarlane** [comment]
What version of the agent are you using?  It's in the package.json

**Comment by bryanmacfarlane** [comment]
task.complete has been in the agent since july 15, 2015
should be task.complete.js in commands folder of agent.  Should be in 0.3.x and later (0.4.x line is current)

update your agent

**Comment by tonyblues** [comment]
Thanks! It's indeed due to an out-of-date agent. :p
