### ISSUE TITLE
Provide vSphere/HyperV provisioning tasks

### ISSUE THREAD

**Issue by japj** [Microsoft/vso-agent-tasks#111]
Hi,

For certain build/test/deploy scenarios it would be really useful if you could provision an on-premise virtual machine on demand and have tasks execute on it.

i.e. tasks like
* bootup/shutdown virtual (build/test) machines on demand
* wait until the virtual machine is up&running
* copy files to a virtual machine
* revert a virtual machine to a base snapshot, before deploying builds
* cloning a vm template to create more test machines
* make a "snapshot" of a vm

Any thoughts on this? 
Would something like this fit somewhere in the current vso-agent architecture or should it be somewhere else?
Is it something that is already planned/not yet implemented?

**Comment by prateek08** [comment]
Hi Japj,
All the above have been planned, and it definitely fits in the current vso-agent architecture.
We are actively working on a couple of your above tasks as well :)

**Comment by ambrishm** [comment]
Hi Jeroen,

I am PM on team building the tasks for Machine Actions. Would you be interested in trying out our new service and the tasks? If yes let me know and we can work to onb-ard you.

**Comment by bryanmacfarlane** [comment]
We will have an app gallery and you will be able to create and publish custom tasks like the one suggested.  It will not be in the box (what this repo tracks)
