### ISSUE TITLE
Azure tasks fails in release management

### ISSUE THREAD

**Issue by MikalJ** [Microsoft/vso-agent-tasks#1112]
When using our own build server (Azure virtual machine) rather than the hosted build server.
Azure tasks in a **release definition** (Azure powershell, Azure Resource Group Deployment, Azure Web App Deployment, etc.) ~~run immediately after rebooting the build server,~~ will fail with this message:
> The term 'Get-ServiceEndpoint' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

As if the powershell module "Microsoft.TeamFoundation.DistributedTask.Task.Internal" have not been imported.

~~Running a **build definition** that includes any of these tasks will correct the issue, and allow the tasks to complete successfully in a **release deifinition** again.~~

Ideally we do not wish our build definitions to interact with azure at all. Only release definitions should do that.

Edit:
It seems I was mistaken about a build definition containing azure tasks being able to correct the issue. I've before encountered the issue, where it was corrected after running a build. But as of now, that doesn't seem to work. I suspect it might have been a fluke at the time.

However Azure Cloud Service Deployment and Azure Powershell task does complete succesfully when run as a par of our currect build definition (resposible for build 4 solutions, testing and deploying them)

**Comment by MikalJ** [comment]
Closing the issue, as I was having a hard time pinning down the cause, or how to reproduce it. Will open a new issue if I manage to better work out the details of the problem

**Comment by strtdusty** [comment]
I have been seeing this issue as well.  I get the same error when running both generic ps1 scripts with no azure calls, as well as something like the regular ARM deployment task. I have not seen it happen on a hosted build.

**Comment by kmkumaran** [comment]
The issue of Get-ServiceEndpoint not recognized as valid commandlet is addressed. The fix will be available in next deployment.

**Comment by edrohler** [comment]
When is the next deployment? I am still getting this error.

**Comment by pksorensen** [comment]
I just got this for the first time also in a task that used to work. anyone?

**Comment by bryanmacfarlane** [comment]
@pksorensen - what's your account name?

**Comment by yiminghan** [comment]
I've having the same issue.  
I got it when using the GenerateReleaseNotes Task.
https://github.com/rfennell/vNextBuild/issues/37

**Comment by donald-slagle** [comment]
I got the same message. It happened when I change which account the Agent Service was running under. I needed it to run under a domain account because install shield license issues and the Network Service account (default) did not work.

**Comment by yiminghan** [comment]
@donald-slagle  thanks for the reply.  I'm a little confused because I tried two identical build definitions running on the same hosted agent, where one succeeded but the other one failed with the message Get-ServiceEndPoint not recognized.  Again, appreciate any insight on this.

**Comment by bootrider** [comment]
One year later I can confirm that @yiminghan report still happens:

> I've having the same issue.
> I got it when using the GenerateReleaseNotes Task.
> rfennell/vNextBuild#37

and it happens when the account of the Agent Service is changed, as @donald-slagle mentioned.

any solution?

this issue belongs here or belongs to [VSTS Agent](https://github.com/Microsoft/vsts-agent)?
