### ISSUE TITLE
Tagging a build from task

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent-tasks#1113]
Hi all,

is there a way to add a tag to the build from the build task?

Thanks

**Comment by Gergues** [comment]
You can do that at the build at VSO build screen for your build [see below ]
![1-22-2016 9-02-19 am](https://cloud.githubusercontent.com/assets/7481105/12512667/a2eed022-c0e7-11e5-98d4-924dc20170b0.png)

Close this issue if resolved , as it is not an issue for that team :)

thanks.

**Comment by mmajcica** [comment]
@gergues I was not referring to labeling the sources.
This are the tags I'm interested in:
![tags](https://cloud.githubusercontent.com/assets/3026551/12512767/6b453cbe-c11a-11e5-840f-058e22eea213.PNG)

I would like to add a tag programmatically from my build task.

Any idea if that is possible?

**Comment by bryanmacfarlane** [comment]
We're in the process of making the agent capable of using git.exe (instead of libgit)


There's also a checkbox on the definition which says to make the OAuth token available to ad-hoc scripts.


What that adds up to is if you select both of those options, we will stuff the creds into the remote (and remove either at end of prepare or end of build dependending on that check box).


What that means to you is you could write a simple cmd/shell/ps1 script which calls a sequence of git cmds and does a push.  It will authenticate and work.  We make the commit that's being built available as another variable so if I understand your scenario correctly, it should be trivial.


________________________________

**Comment by TingluoHuang** [comment]
@mmajcica we will add a ##vso[build.tag] command to support your scenarios.

**Comment by pascalberger** [comment]
@mmajcica In the meantime until the stuff @bryanmacfarlane mentions is in place, I've put [an extension](https://marketplace.visualstudio.com/items/ioz.vsts-git-build-tasks) in the store which takes care of putting the credentials into the remote and revert the changes back at the end.

**Comment by mmajcica** [comment]
@TingluoHuang thanks. That was something I was looking for. A cmdlet in a Microsoft.TeamFoundation.DistributedTask.Task.Common would be welcome.

Thanks

**Comment by Gergues** [comment]
That would be a nice feature for sure.

**Comment by abhiphirke** [comment]
Hi. Its been more than 6 months for last comment on this thread. Do we have something of this sort available now? I want to tag a build so that i can choose to trigger different release configurations.

**Comment by mmajcica** [comment]
I have built a build task a while ago, if interested, I can share it.

**Comment by shashban** [comment]
"[##vso[build.addbuildtag]](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md )" command is available to tasks for this functionality.

**Comment by andremarques023** [comment]
@shashban This command functionality should be also available for releases. You can manually add a tag to it but there's no logging command, no API, no nothing.

**Comment by shashban** [comment]
@andremarques023 We don't have a task command to ad a release tag yet. You can add a tag using update Release API.

**Comment by StephaneBischoff** [comment]
How can I add a tag to the artifact in the Build process? Basically, I have a automatic release generation based on a Tag. But that tag is on the artifact and not the build.

**Comment by andremarques023** [comment]
I encapsulated the logging command functionality in a task inside this extension: https://marketplace.visualstudio.com/items?itemName=andremarques023.DiagnosticTasks

It would be nice to have this logging command for releases too so the task would work for both.

@

**Comment by andremarques023** [comment]
@StephaneBischoff which artifact? Do you mean the release process?

**Comment by StephaneBischoff** [comment]
Yes, So I have in my Release process (Under Triggers) the Continuous Deployment checked. On the Set trigger on artifact source, I put a Tag condition (With tags). I am wondering how do I add this Tag during the Build process?

**Comment by rmarinho** [comment]
we should have this on log  command as we have for build
