### ISSUE TITLE
DeployAzureResourceGroup task does not support reference parameters

### ISSUE THREAD

**Issue by bmoore-msft** [Microsoft/vso-agent-tasks#1118]
The AzureRM parameter file schema supports reference parameters to retrieve secrets from KeyVault, the syntax is:

        "sqlserverAdminLoginPassword": {
          "reference": {
            "keyVault": {
              "id": "/subscriptions/[guid]/resourceGroups/[rgname]/providers/Microsoft.KeyVault/vaults/[vaultname]"
            },
            "secretName": "adminPassword"
          }
        }
    }

The DeployAzureResourceGroup task does not support using this syntax, the parameters are dropped from the file.

It looks like the task goes through a process of reading the file, converting to a hashtable and then converting back to JSON.  This process makes some assumptions about the schema of the parameter file (which is fragile) - seems like a better approach would be simply to pass the parameter file to the New-AzureRMResourceGroup cmdlet instead of trying to create an object.  If we just passed the param file, it will fix this issue and avoid similar issues in the future.

**Comment by kmkumaran** [comment]
Thanks Brian for the feedback.

**Comment by kmkumaran** [comment]
This has been addressed.
