### ISSUE TITLE
How do I get the SqlAzureDacpacDeployment task on my VSTS Release Management task drop down?

### ISSUE THREAD

**Issue by dawilliams** [Microsoft/vso-agent-tasks#1123]
Hello,

I don't currently have the option to select the SqlAzureDacpacDeployment task.  Is it because we are using the Hosted agent pool and it is missing a requirement?

Thanks,

David

**Comment by chrisrpatterson** [comment]
It is marked as preview so it won't show in your account unless you are in the preview program or it is released.

**Comment by dawilliams** [comment]
Thank you for replying.  How can I tell that something is in preview?

Thanks,

David
On January 25, 2016 at 2:20:52 PM, Chris Patterson (notifications@github.com) wrote:

It is marked as preview so it won't show in your account unless you are in the preview program or it is released.

**Comment by chrisrpatterson** [comment]
The visibility tag in the task.json has Preview in it.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Mon, Jan 25, 2016 at 3:09 PM -0800, "David Williams" <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you for replying.  How can I tell that something is in preview?

Thanks,

David
On January 25, 2016 at 2:20:52 PM, Chris Patterson (notifications@github.com) wrote:

It is marked as preview so it won't show in your account unless you are in the preview program or it is released.

-
Reply to this email directly or view it on GitHub.


-

**Comment by ChristopherHaws** [comment]
How can you join the preview program?

**Comment by kmkumaran** [comment]
You should see SqlAzureDacpacDeployment task visible to all accounts in next VSTS deployment. We plan to remove the "preview" flag for this task.
