### ISSUE TITLE
SPNCreate.ps1 fails if subscription has a space in the name

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vso-agent-tasks#1124]
Trying to run the following:
https://raw.githubusercontent.com/Microsoft/vso-agent-tasks/master/Tasks/DeployAzureResourceGroup/SPNCreation.ps1

Fails if my subscription has a space in the name:

```
Creating a new Application in AAD (App URI - http://VSO.oren.DSRIP Demo.5a5c52ae-db2b-4f66-bc54-1c1d33d656a9)
New-AzureRmADApplication : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"Property
identifierUris is invalid."},"values":[{"item":"PropertyName","value":"identifierUris"},{"item":"PropertyErrorCode","va
lue":"GenericError"}]}}
At C:\Users\oren\Downloads\SPNCreate.ps1:41 char:23
+ ... plication = New-AzureRmADApplication -DisplayName $displayName -HomeP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmADApplication], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADApplicationCommand
```

**Comment by chrisrpatterson** [comment]
Muthu?

**Comment by kmkumaran** [comment]
Thanks for reporting. In the script, can you remove $subscriptionName from below (line no. 18) 
$displayName = "VSO." + $userName + '.' + $subscriptionName + '.' + $newguid

As you had mentioned the space in subscription name is causing this failure. You can unblock yourselves with above change in the script.

**Comment by volago** [comment]
I've seen that newest version is space aware. Although I had similar problem. It was caused by any accent character, in my case polish character: 'ż'.

I workarounded it by replacing 'ż' with 'z'

**Comment by kmkumaran** [comment]
@volago, yes we fixed the script to be space aware. Can you tell us which script input had the polish character?

**Comment by pavanadepu2** [comment]
@volago, Can you take the latest script from GitHub and give it a try:
    https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/DeployAzureResourceGroup/SPNCreation.ps1

**Comment by volago** [comment]
@kmkumaran My Azure subscription name is "Zużycie platformy Windows Azure". The current script is ok. Removing $subscriptionName from composing $displayName helps a lot. Thanks
