### ISSUE TITLE
PublishBuildArtifact creates error on path with spaces

### ISSUE THREAD

**Issue by GerwinNL** [Microsoft/vso-agent-tasks#1131]
We currently run into problems on the Hosted Agent.
We use a task PublishBuildArtifacts (1.0.24) to make some artifacts. Previously, when there was a space in the _PathToPublish_ there where no problems, but recently we get the following error :
##[error]System.ArgumentException: Illegal characters in path.

Works : _PathtoPublish=C:\a\1\s\AGB\10-Vektis.AGB.FEBeheerAGB\Main\Configs\OT_ 
Fails : _PathtoPublish="C:\a\1\s\AGB\10 - Vektis.AGB.FEBeheerAGB\Main\Configs\OT_ 

We CAN rework the scripts, but we consider this behaviour as faulty.
Is this by design ?  Will this be resolved ?

Gerwin

**Comment by chrisrpatterson** [comment]
This is a bug we discovered.  Ting where we on the fix?

**Comment by chrisrpatterson** [comment]
We apologize for the issue.  There is a hotfix going out to the service in the next hour that should resolve it.

**Comment by GerwinNL** [comment]
Chris,

We appreciate your prompt response. 
Thanks to Ting as well :)

We will check it out as soon as the fix is available to us.

Gerwin
