### ISSUE TITLE
Xcode Build Task reports "glob is not defined"when Package App is checked

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vso-agent-tasks#1136]
This was reported both but a customer at MacinCloud and internally. A recent update of the Xcode build task appears to have broken the packaging feature in the task because it is unable to find the "glob" node module.

Example output with system.debug=true:

** BUILD SUCCEEDED **
packageApp=true
Packaging apps.
out: /Users/vso112250/vso-agent/_work/6/s/output/iphoneos9.1/Debug
outPath: /Users/vso112250/vso-agent/_work/6/s/output/iphoneos9.1/Debug/build.sym
/usr/bin/security delete-keychain /Users/vso112250/vso-agent/_work/6/s/_tasktmp.keychain
glob is not defined
taskRunner fail
load loc strings

Un-checking the "Create App Package" does resolve the problem, but this is a less than ideal solution.

**Comment by bryanmacfarlane** [comment]
We are patching.  

Here's the workaround for folks affected:

in _work, tasks, on the agent under latest xcode, xcodebuild2.js 

add the *glob line* below

var tl = require('vsts-task-lib'),
path = require('path'),
fs = require('fs'), 
*glob = require('glob'),*
Q = require ('q'),
xcutils = require('./xcode-task-utils.js');

**Comment by clau3107** [comment]
The workaround seems to be working for us; thanks Bryan and Chuxel!

**Comment by bryanmacfarlane** [comment]
This was patched and fixed
