### ISSUE TITLE
task.json can't be uploaded when file is saved with Unicode bom

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vso-agent-tasks#1151]
I'm having issues publishing build extensions with TFX that have a task.json which contain a unicode BOM. Are they required to be ASCII only? 

The error is pretty cryptic, though anyone who has worked with both encoding will probably recognize those pesky Chinese characters for what they are. Since the json file contains labels and such, I'd expect unicode compatibility for Japanese, Chinese and other languages.

**Comment by bryanmacfarlane** [comment]
Remove the BOM.  It blows up in some deserailizers as invalid JSON (techically is).  For example, JSON.parse in typescript/javascript.

It should be utf-8 with no BOM

**Comment by jessehouwing** [comment]
Would be nice if `Out-File` would support writing json with no BOM :S... Thanks for confirming though. I'll add more .NEt wrapped code to implement my own powershell cmdlet replacements :(.

**Comment by chrisrpatterson** [comment]
@jessehouwing that would be good feedback for the powershell team.
