### ISSUE TITLE
[Feature request] Support building of tasks using .net Core

### ISSUE THREAD

**Issue by neoKushan** [Microsoft/vso-agent-tasks#1162]
To what I understand, if I want a task to run well on Windows I can use Powershell. However that won't work on Linux/Mac/etc. in which we build tasks using nodejs. This means that a lot of tasks have the same task built twice, once in powershell and once in node to ensure it works across platforms. This seems very redundant to me and means anyone writing these tasks either picks a single platform or has to be proficient in both Powershell and Javascript.

In my simple mind, it makes a lot of sense to be able to write tasks in a language that .net developers are very familiar with already (Or indeed one of the many languages that DNX supports). By utilising the dnx, these tasks should also happily run on Windows/Mac/Linux without any changes, ultimately simplifying the building of the tasks and allowing much more flexibility.

**Comment by chrisrpatterson** [comment]
You can write a task in JavaScript and have it run on any platform, both agents support the Node Js task handler.  Given the current flux that DNX and dotnet core has been in it would not have been a good choice.
