### ISSUE TITLE
Add way to debug minimatch

### ISSUE THREAD

**Issue by rosieks** [Microsoft/vso-agent-tasks#1167]
My company just updated to TFS 2015 update 1 and I want to switch to new build system. I have a lot of trouble to write correct minimatch for various tasks like VSTest or CopyPublishBuildArtifacts. I think that this tasks use different patterns which is first disadvantage.

It would be nice to have some debugger that let mi show which files from last build are gathered by minimatch. Thanks to that I will also be able to improve performance of my build.

As a workaround it would be nice to have at least better description for patterns for copy and publish build artifacts - how to exclude some files/directories like pdb or projects with tests

**Comment by ericsciple** [comment]
I think unless the markdown specifically states that it uses minimatch, then it uses an old proprietary format instead. I'm working on docs for the task lib, I'll at least add it there (it probably belongs somewhere else as well). For now you can reference the Find-Files.LegacyPattern*.ps1 unit tests https://github.com/Microsoft/vsts-task-lib/tree/master/powershell/Tests/L0

Also I see now that I'm missing unit tests for the exclude patterns. Exclude patterns start with "-:". Separate multiple patterns with ";".

**Comment by bryanmacfarlane** [comment]
On build definition variable:
System.Debug=true

One other option is simply do dir /s from your output directory as part of the build process so you can see the layout.  From there, match patterns of ** and * are pretty straight forward.  You can also download a drop and try minimatch patterns from the disk.

That's as close as you get right now.  It will show some samples, some matches, etc... which may help.

We do have a feature on the backlog to store output from previous builds in a typeahead help mechanism for ...  You do have an interesting idea where you could try minimatch patterns in the web UI against that metadata.  We'll add that to the backlog feature idea
