### ISSUE TITLE
Add JS based tasked for Publish Code Coverage

### ISSUE THREAD

**Issue by beverts312** [Microsoft/vso-agent-tasks#1188]
Currently there is no way to publish code coverage results into VSTS from an xplat agent running on a linux box. 

VSTS Task Lib has nothing around how to do this in a build task myself.

**Comment by bryanmacfarlane** [comment]
Yes, I believe a team is currently porting that to JS.  Assigning

**Comment by darthtrevino** [comment]
+1
Is there a Web API or something associated with the `Microsoft.TeamFoundation.DistributedTask.Task.CodeCoverage::Publish-CodeCoverage`` powershell command?

**Comment by bryanmacfarlane** [comment]
Yes there is and I'll let Allen detail.

Not that the command is in the closed source windows agent :(

BUT, we are creating a new combined agent which is open sourced so you're not closed off to stuff like that:  https://github.com/Microsoft/vsts-agent

In the meantime, the node based xplat agent (which that is replacing) has an implementation which may provide clues:

https://github.com/Microsoft/vso-agent/blob/master/src/agent/commands/codecoverage.publish.ts

**Comment by AshwiniChalla** [comment]
As mentioned by bryan we have added support for publish code coverage for xplat agent. The agent is not yet released. Next agent update should have it.
