### ISSUE TITLE
Diagnostic Extensions are not applied for a Cloud Service if the cscfg is a minimatch pattern

### ISSUE THREAD

**Issue by ersommer** [Microsoft/vso-agent-tasks#1190]
I'm using the "Azure Cloud Service Deployment" task on VSO to publish a few Cloud Services I own. I noticed that it's not setting up the Diagnostics Extension during deployment. The log doesn't mention anything about diagnostics.

It only happens when the path to the .cscfg is a minimatch pattern (like `$(System.DefaultWorkingDirectory)\**\*.cscfg`). If the path is hard coded (like `$(System.DefaultWorkingDirectory)\Prod\drop\Website.Azure.cspkg`) it works fine.

After looking at [the code](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/AzureCloudPowerShellDeployment/Publish-AzureCloudDeployment.ps1), I believe I found the issue. It calls `$diagnosticExtensions = Get-DiagnosticsExtensions $StorageAccount $CsCfg` where `$CsCfg` is the original path passed into the script. `Get-DiagnosticsExtension` uses that path to find the Extensions folder. If the path is a minimatch pattern, the path doesn't resolve correctly. `$serviceConfigFile` should be passed in instead of `$CsCfg` as it is the actual path to the .cscfg file.

**Comment by yaananth** [comment]
Thanks for reporting, 
Also note that "System.DefaultWorkingDirectory)\Prod\drop\*.cscfg" should work.
Will fix this.
