### ISSUE TITLE
Unable to find FQDN for resource

### ISSUE THREAD

**Issue by ncipollina** [Microsoft/vso-agent-tasks#1199]
I am trying to configure Release Management for a project I currently have hosted in Visual Studio Online.  The target for the release are Azure VM's.  I'm following the instructions in this document https://msdn.microsoft.com/en-us/Library/vs/alm/Release/examples/net-to-azure-vm but every time it executes the Azure Deployment: Select Resource Group task, it fails with error messages saying that it is  Unable to find FQDN for resource for (VM name here).  In my resource group, I have 4 VM's and all have Public IP addresses along with DNS entries matching the format vmname-eastus.cloudapp.azure.com.  Unless I'm mistaken, that is the FQDN for the servers.  Also, the IP address have bee assigned as Static.  Does that make a difference?  Any help resolving this issue would be greatly appreciated.

**Comment by ncipollina** [comment]
I've figured out why it's unable to resolve the FQDN for my servers.  I have an Azure Load balancer set up in the same resource group and I only have one VM associated with the load balancer.  Beyond that, I have no Inbound Nat Rules associated with them either.  So it is not finding my VM's when it's building the $fdqmMap hashtable in the Powershell script.  This is where my VM's would be added to the map:

`        #Find out the NIC, and thus the corresponding machine to which the NAT rule belongs
        foreach($nic in $networkInterfaceResources)
        {
            foreach($ipc in $nic.IpConfigurations)
            {
                foreach($rule in $ipc.LoadBalancerInboundNatRules)
                {
                    $fqdn = $fqdnMap[$rule.Id]
                    if(-not [string]::IsNullOrEmpty($fqdn))
                    {
                        $fqdnMap.Remove($rule.Id)
                        if($nic.VirtualMachine)
                        {
                            $fqdnMap[$nic.VirtualMachine.Id] = $fqdn
                        }
                    }
                }
            }
        }`

I feel like this is a bad assumption to make that if there is a Load Balancer then all VM's in that Resource Group must not only be associated with a Load Balancer, but must also have Inbound NAT rules as well.  These scripts should be able to find the FQDN whether there is a load balancer in place or not.

**Comment by kmkumaran** [comment]
Thanks for the feedback. We will track and address this bug.

**Comment by niadak** [comment]
Fix will be available in next deployment
