### ISSUE TITLE
AzureFileCopy does not work with premium storage

### ISSUE THREAD

**Issue by jesfer** [Microsoft/vso-agent-tasks#1204]
When I use a premium storage account I get this error:

##[error]The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The remote server returned an error: (400) Bad Request. HTTP Status Code: 400 - HTTP Error Message: One of the headers specified in the request is not supported.

**Comment by niadak** [comment]
Hi jesfer,
Today Premium Storage supports only Azure page blobs. Please refer to https://azure.microsoft.com/en-in/documentation/articles/storage-premium-storage/

To use Premium storage account in AzureFileCopy task you have to pass /BlobType:Page as additional parameter. And also you can only upload contents of size multiple on 512 byte.
