### ISSUE TITLE
Test Agent not using ResultsDirectory in .runsettings file

### ISSUE THREAD

**Issue by TestO2015** [Microsoft/vso-agent-tasks#1207]
We're using a .runsettings file with the  'Visual Studio Test using Test Agent' build task:

`<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\TestRuns</ResultsDirectory>
    <TargetPlatform>x64</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>
</RunSettings>`

We expect Test Runs to use the **C:\TestRuns** directory however it is using the %Temp% directory instead. 

It looks like the .runsettings file was used based on the fact that setting the TargetPlatform to 'x64' was apparently effective. Also, using the same .runsettings locally in Visual Studio configured the directories as expected to "C:\TestRuns".

Is there something missing to be configured on the Test Agent or task?

**Comment by AshwiniChalla** [comment]
Ack: I was able reproduce this issue.

**Comment by AshwiniChalla** [comment]
Hi TestO2015, 
This behavior is by design. 
Any specific reason why you are interested in having a specific results directory location?

**Comment by TestO2015** [comment]
Hi AshwiniChalla,

When the %TEMP% directory is used the the 260 character path limit is exceeded.

We were able to work around this for most of the Test Run directories by changing them using the TestContext object during TestInitialize. What remains is the TestContext.DeploymentDirectory as it is created before the TestInitialize. We could probably work around this too but it doesn't sound ideal.

Would be interested to know the reason behind the design! Thanks.

**Comment by AshwiniChalla** [comment]
There is no other way to configure the test run directories as of today. 
We will look to fix this. Added to our backlog.

**Comment by MattHanMS** [comment]
I was able to set the Results directory by adding an "Override TestRun Parameters" to "ResultsDirectory=.\TestResults".  This created the TestResults directory in the directory above the Build_SourcesDirectory.

**Comment by jar240** [comment]
MattHanMS, did you achieve this using the "Run Functional Tests" task, or the "Visual Studio Test" task? Was this with TFS 2015 Update 2?

**Comment by MattHanMS** [comment]
This was using the ‘Visual Studio Task’.  I believe it was with TFS 2015 Update 2, but can’t confirm.

**Comment by jibal** [comment]
> This behavior is by design.

That response makes no sense. There's a property called ResultsDirectory and it's documented as being where the test results go. Therefore it cannot be "by design" that they go somewhere else.

> Any specific reason why you are interested in having a specific results directory location?

This sort of question is so annoying ... there are numerous well-known reasons why people want to keep generated files out of their source folders.

**Comment by cjfarrelly** [comment]
> I was able to set the Results directory by adding an "Override TestRun Parameters" to "ResultsDirectory=.\TestResults". This created the TestResults directory in the directory above the Build_SourcesDirectory.

I'm not sure how this could possibly work.
