### ISSUE TITLE
Publish-AzureWebDeployment.ps1 default Slot value

### ISSUE THREAD

**Issue by RonniePitts** [Microsoft/vso-agent-tasks#1209]
There are some instances where a Azure Web site will have a default instance (no slot setting).

Currently leaving the Slot setting blank will always default to Production even though the remaining code supports it. 

This line should be removed (it only works if the name contains () characters, e.g. the default value isnt used),

if (!$Slot -and $WebSiteName -notlike '*(*)*') {
        $Slot = 'production'
    }

**Comment by RonniePitts** [comment]
This has been fixed in the following commit 

https://github.com/RonniePitts/vso-agent-tasks/commit/2af660d5c4e4417b38f25067cf2c6b5111178daa

**Comment by yaananth** [comment]
If slot is not already defined, we default to 'production' slot.
When the website name is something like : "websitename(mycustomslot)" then, get-azurewebsite commandlet doesn't return an array, it is smart enough to understand that slot name is "mycustomslot". So it would get website with "websitename" for slot "mycustomslot"
If you have build logs where it fails or doesn't happen, feel free to reopen this,

**Comment by RonniePitts** [comment]
That's not correct.

GetAzureWebsite does return an array. Check the documentation.
________________________________

**Comment by yaananth** [comment]
it will if the name doesn't have slot in it. I verified on azure powershell.
Try passing in - Name(slot), it won't return array

**Comment by yaananth** [comment]
![image](https://cloud.githubusercontent.com/assets/12280011/13090987/0576bf8c-d4c7-11e5-9766-83d9cc9d42db.png)

**Comment by RonniePitts** [comment]
You cant use a slot to update the default instance.
________________________________

**Comment by yaananth** [comment]
meaning the one with no custom slots? 
Any website would have default slot as "Production"
Get-AzureWebSite -Name "somename" -Slot Production
is equivalent to
Get-AzureWebSite -Name "somename" 

for websites who doesn't have any other slots.
What default instance are you referring to?
