### ISSUE TITLE
Create multiple packages with one NuGet Packager task

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vso-agent-tasks#1211]
I think this should be possible when I use the right "Path/Pattern to nuspec files" because that field supports minimatch patterns. I want to build 2 nuget packages, one from **\Client.csproj and one from **\CanonicalSchema.csproj. I tried this minimatch pattern, but that doesn't work:

> **\@(CanonicalSchema|Client).csproj

The error I got:

> 2016-02-10T13:44:17.2552576Z Find-Files -SearchPattern **\@(CanonicalSchema|Client).csproj
> 2016-02-10T13:44:17.2708842Z ##[error]Illegal characters in path.

**Comment by vtbassmatt** [comment]
'@' is part of extended globbing, which Find-Files doesn't support. Patterns are split at semicolons and then (more or less) treated as .Net regexes from there. Try your pattern without the `@`. If that doesn't work, `**\CanonicalSchema.csproj;**\Client.csproj` will.

**Comment by tomkuijsten** [comment]
Your last suggestion was my first guesse, but that doesn't work either. When I try ` **\CanonicalSchema.csproj;**\Client.csproj `, this is the result:

```
Find-Files -SearchPattern C:\tfsBuildAgent\_work\17\s\**\CanonicalSchema.csproj;**\Client.csproj
The path is not of a legal form.
Found files: 0
```

**Comment by vtbassmatt** [comment]
D'oh, well that's no good. I'll take a look at this when I get into the office.

**Comment by vtbassmatt** [comment]
Ah, found it. There's a bug in the way the task is written - if it doesn't see a * or ? in the pattern, it assumes it's not a pattern but a direct file reference. One workaround is to force it to evaluate your input as a pattern by including a ? somewhere: `**\CanonicalSchema.cspr?j;**\Client.csproj`

I think we can fix this in a backwards-compatible way by assuming that a semicolon also indicates a pattern.

**Comment by tomkuijsten** [comment]
Nice, thanks for the fix and the work around. I'll give it a try when I'm at work next week.

**Comment by vtbassmatt** [comment]
@tomkuijsten everything working for you?

**Comment by tomkuijsten** [comment]
I just created a test and it didn't work as expected:

```
Checking pattern is specified
Pattern found in solution parameter.
Find-Files -SearchPattern C:\tfsBuildAgent\_work\48\s\**\CanonicalSchema.cspr?j;**\Client.csproj
The path is not of a legal form.
Found files: 0
```

**Comment by vtbassmatt** [comment]
That's odd. It got past the bug I knew about because it says "Pattern found in solution parameter".

There's something funky happening with the Find-Files cmdlet that I don't understand. I reproed the bug you're seeing locally.

The best workaround for now is going to be specifying a single pattern with a wildcard that matches both of your project files: `**\C*.csproj` perhaps? I'm following up with the owners of the Find-Files code to see what I'm missing.

**Comment by vtbassmatt** [comment]
Thanks to @ericsciple I found the right solution. It has to do with relative vs absolute paths. This should fix your issue the right way: `$(build.sourcesdirectory)\**\CanonicalSchema.csproj;$(build.sourcesdirectory)\**\Client.csproj`

**Comment by bryanmacfarlane** [comment]
@ericsciple  - Seems like there's a bug maybe.  All input paths should be relative to the root of the repo, right?  Unless it's not a filepath input type ...  If not, I would expect the default to be $(build.sourcesdirectory)\**\*.csproj to encourage the right input ??

**Comment by vtbassmatt** [comment]
@bryanmacfarlane FWIW it also fails with unrooted paths in PowerShell. I had to explicitly add ".\" to get that working.

**Comment by ericsciple** [comment]
@vtbassmatt there's an optional RootFolder parameter that allows you to specify the root folder for unrooted search patterns. I'm not sure offhand what the default is otherwise... I would assume it's the current working directory. I'm not sure, I need to look into this in our tasks.

**Comment by ericsciple** [comment]
OK, here's what's going on.
1) The search pattern input's type is defined as "FilePath" in the task.json. So the input gets rooted with $(build.sourcesdirectory). This answers part of Bryan's question. The problem is that only the first search pattern is rooted, the FilePath input doesn't understand that it's a delimited list of paths.
2) When the Find-Files cmdlet is processing each individual pattern, it tries to determine what folder to start searching. It tries to grab the path preceding the first wildcard, and passes that to `system.io.path.getdirectoryname(...)`. The problem here is that it ends up passing empty string, which results in the error `The path is not of a legal form.`.

Thoughts on a short-term fix: For the NuGet Packager task, probably the best thing to do is to supply the RootFolder parameter when calling Find-Files. That will make sure each pattern gets rooted. You would probably want to pass whatever value the FilePath input uses to root relative paths. For Build, this is $(build.sourcedirectory). I'm not sure if the NuGet Packager task is commonly used in Release as well. If so you might want to fallback to whatever Release uses (that is, if build.sourcesdirectory is not defined).

...Now I need to go look at the vsbuild/msbuild tasks because they have the same issue :)

**Comment by vtbassmatt** [comment]
Thanks for the investigation and root cause! I'll update.

No idea if this task gets used with RM but for sure the Publisher does. I'll make it work both ways.

**Comment by tomkuijsten** [comment]
I tested your suggestion:  ``` $(build.sourcesdirectory)\**\CanonicalSchema.csproj;$(build.sourcesdirectory)\**\Client.csproj ```

But this ends in:
```
Checking pattern is specified
Pattern found in solution parameter.
Find-Files -SearchPattern c:\tfsBuildAgent02\_work\24\s\ c:\tfsBuildAgent02\_work\24\s\**\CanonicalSchema.csproj;c:\tfsBuildAgent02\_work\24\s\**\Client.csproj 

The given path's format is not supported.
Found files: 0
```
Somehow, the ```  $(build.sourcesdirectory) ``` is prepended anyway. I thought to be clever and changed the pattern to: ``` **\CanonicalSchema.csproj;$(build.sourcesdirectory)\**\Client.csproj  ```

But that ended in:

```
Executing the powershell script: c:\tfsBuildAgent02\tasks\PublishBuildArtifacts\1.0.4\PublishBuildArtifacts.ps1
Preparing artifact content in staging folder c:\tfsBuildAgent02\_work\24\a...
Copying all files from c:\tfsBuildAgent02\_work\24\s\bin\Release\Bronkhorst.InstrumentCommunication.CanonicalSchema.1.3.1-dev.nupkg to c:\tfsBuildAgent02\_work\24\a\NuGet\Bronkhorst.InstrumentCommunication.CanonicalSchema.1.3.1-dev.nupkg
Copying artifact content to \\server\builds...
Start: AssociateArtifact
Associated artifact 641 with build 563
End: AssociateArtifact
```

The client package is missing this time...

**Comment by vtbassmatt** [comment]
@tomkuijsten are you on-prem or VSTS? I wonder if you have an older edition of the packager task. I did `$(build.sourcesdirectory)\**\ConsoleApplication1.csproj;$(build.sourcesdirectory)\**\ConsoleApplication2.csproj` and got:

```
2016-02-18T17:58:53.3667583Z Checking pattern is specified
2016-02-18T17:58:53.3837648Z Pattern found in solution parameter.
2016-02-18T17:58:53.3867594Z Find-Files -SearchPattern C:\a\1\s\**\ConsoleApplication1.csproj;C:\a\1\s\**\ConsoleApplication2.csproj
2016-02-18T17:58:53.4167608Z Found files: 2
2016-02-18T17:58:53.4237587Z --File: "C:\a\1\s\ConsoleApplication1\ConsoleApplication1.csproj"
2016-02-18T17:58:53.4237587Z --File: "C:\a\1\s\ConsoleApplication2\ConsoleApplication2.csproj"
```

This is running version 0.1.58 (really 0.1.60, which includes my fix to split on semicolons but is otherwise identical) of the task.

**Comment by tomkuijsten** [comment]
On-premise TFS 2015 update 1, version 1.4.0 of the PublishBuildArtifacts.

**Comment by vtbassmatt** [comment]
What version of NugetPackager?

**Comment by tomkuijsten** [comment]
Oh dah! Sorry, the version of NugetPackager: 0.1.56

**Comment by tomkuijsten** [comment]
The output of the nugetpackager:

```
2016-02-19T14:16:35.7966247Z Set workingFolder to default: c:\tfsBuildAgent02\tasks\NuGetPackager\0.1.56
2016-02-19T14:16:35.7966247Z Executing the powershell script: c:\tfsBuildAgent02\tasks\NuGetPackager\0.1.56\NuGetPackager.ps1
2016-02-19T14:16:36.0622413Z Checking pattern is specified
2016-02-19T14:16:36.0622413Z Pattern found in solution parameter.
2016-02-19T14:16:36.0622413Z Find-Files -SearchPattern c:\tfsBuildAgent02\_work\24\s\**\CanonicalSchema.csproj;c:\tfsBuildAgent02\_work\24\s\**\Client.csproj 
2016-02-19T14:16:36.2497577Z Found files: 1
```

**Comment by vtbassmatt** [comment]
Your latest snippet looks like it's passing the right string to Find-Files, but now only finding one .csproj. That's different from the snippet you pasted further up -- maybe that was a typo with a space at the beginning of the pattern?

**Comment by vtbassmatt** [comment]
PR #1258 will fix the issues I know about.

**Comment by tomkuijsten** [comment]
That latest snippet is the result when using ```**\CanonicalSchema.csproj;$(build.sourcesdirectory)\**\Client.csproj```.

Maybe I did have a space in front of my first try with ```$(build.sourcesdirectory)\**\CanonicalSchema.csproj;$(build.sourcesdirectory)\**\Client.csproj```, but even if that one worked, I guess that the output would be that same as my last result. I'll give it another shot on Monday at work.

**Comment by vtbassmatt** [comment]
OK, thanks @tomkuijsten. I think we may be dealing with multiple nested issues here. Sorry it's been such a process.

**Comment by tomkuijsten** [comment]
Not a problem, my build is running fine with two tasks now. So everything I can do to help fix some bugs, I'd be glad doing.

**Comment by tomkuijsten** [comment]
You were right about that space. I tried it again with ```$(build.sourcesdirectory)\**\CanonicalSchema.csproj;$(build.sourcesdirectory)\**\Client.csproj``` and checked for the space, this time the path was correctly read, but the output is still only CanonicalSchema:

```
Checking pattern is specified
Pattern found in solution parameter.
Find-Files -SearchPattern C:\tfsBuildAgent\_work\55\s\**\CanonicalSchema.csproj;C:\tfsBuildAgent\_work\55\s\**\Client.csproj 
Found files: 1
--File: C:\tfsBuildAgent\_work\55\s\CanonicalSchema\CanonicalSchema.csproj
```

I checked the second path on the server and it really should have found the Client.csproj. I changed the path again to C*.csproj to check if it could find Client.csproj this time, the output:

```
Find-Files -SearchPattern C:\tfsBuildAgent\_work\55\s\**\C*.csproj
Found files: 3
--File: C:\tfsBuildAgent\_work\55\s\CanonicalSchema\CanonicalSchema.csproj
--File: C:\tfsBuildAgent\_work\55\s\Client\Client.csproj
--File: C:\tfsBuildAgent\_work\55\s\ClientTestApp\ClientTestApp.csproj
```

**Comment by vtbassmatt** [comment]
I can't repro [this behavior](https://github.com/Microsoft/vso-agent-tasks/issues/1211#issuecomment-187051280). Once I put the $(build.sourcesdirectory) in both spots, the task picks up both .csproj files. It's interesting that it no longer throws the "path not of legal form" message even though it doesn't find your file.

Let's take the build system out of the equation temporarily. There's a standalone version of Find-Files (that Eric helped me find offline) which might give us some insight. Instructions for that are to run PowerShell and then:

```PowerShell
git clone https://github.com/Microsoft/vsts-task-lib.git
cd vsts-task-lib
Import-Module ./powershell/VstsTaskSdk
cd [directory containing your source]
Find-VstsFiles -LegacyPattern ".\**\CanonicalSchema.csproj;.\**\Client.csproj" -Verbose
```

I'm interested in the output of the above commands, but also feel free to poke around with `Find-VstsFiles`. It might be interesting to replace both of the ".\"s with the full source directory.
