### ISSUE TITLE
AzureFileCopy - File Storage destination

### ISSUE THREAD

**Issue by opt-andrel** [Microsoft/vso-agent-tasks#1213]
Hi guys,

As near as I can tell, using this task to copy build artifacts to an SMB file store on an Azure storage instance (instead of a blob) seems impossible.

I have searched the existing issues for any mention of this and I didn't find it. If this is a duplicate or simply not true, I'd be happy to close this.

Advice please?

Regards,
Andre

**Comment by opt-andrel** [comment]
I also wanted to add: if this task simply 'automates' AzCopy, supporting this should be a simple matter of generating a *.file.* destination url instead of a *.blob.* destination. If i'm correct here, is there any way to run AzCopy manually as a build task? I've considered executing a powershell script, but I see that this can't be done inline.

**Comment by opt-andrel** [comment]
Apologies, I'm used to having the OK button to the left. This is still open.

**Comment by niadak** [comment]
Hi Andre,
Thanks for your feed back. Today we are not supporting Azure File Store destination. I have created a work item for the same and we will take that according to priority order.

You can use AzCopy tool using AzurePowerShell task. The task will take your subscription details as service end point and provide you a AzurePowerShell session. You can run a PowerShell script that will get storage key using AzurePS Command and use that key to run AzCopy tool. This can not be done inline, you have to pass the script path.

Please let me know if you need any help.

Thanks,
Nilkamal

**Comment by opt-andrel** [comment]
Hi Nilkamal,

I appreciate the advice. It is good to know that I didn't diagnose this incorrectly then. What I can say however, is that you don't really need to support it.

I was able to utilize a 'Windows Machine File Copy' task step (effectively Robocopy) to get files into the share thanks to the SMB protocol it supports.

Regards,
Andre

**Comment by niadak** [comment]
Thanks for your reply.
