### ISSUE TITLE
Validate Customscript Extension Issue

### ISSUE THREAD

**Issue by ncipollina** [Microsoft/vso-agent-tasks#1223]
Line 781 of the Utility.ps1 script in the Validate-CustomScriptExecutionStatus function does not work with version 1.0 + of Azure Powershell.  The line is included below:
` $customScriptExtension = $status.Extensions | Where-Object { $_.ExtensionType -eq "Microsoft.Compute.CustomScriptExtension" -and $_.Name -eq $extensionName }`

The issue is that the property isn't called ExtensionType but just Type.  I'm having issues because I'm trying to run this on my own deploy agent and it has the latest Azure powershell version installed.  The Hosted agent has Azure Powershell version 9.7 and this Task works fine.  I changed the powershell script locally from ExtensionType to Type and it works.

**Comment by chrisrpatterson** [comment]
This issue has been resolved and will deploy with the next sprint in a couple of weeks https://github.com/Microsoft/vso-agent-tasks/commit/5e64eef3570423fb3955b732d1cf0d23e5bbb7ec
