### ISSUE TITLE
I cannot find the IIS Web Application Deployment task in Tfs2015.Update2.RC1.1?

### ISSUE THREAD

**Issue by ilovesoftware** [Microsoft/vso-agent-tasks#1229]
![tasks](https://cloud.githubusercontent.com/assets/16279480/13006312/75edbd2a-d188-11e5-8915-002fde732a60.PNG)

**Comment by bryanmacfarlane** [comment]
I think it's still in preview.  Adding Muthu to confirm

**Comment by kmkumaran** [comment]
Yes. It is still in preview. You can mail RM_Customer_Queries@microsoft.com if you would like to be enrolled for preview tasks.

**Comment by ilovesoftware** [comment]
Ok. Thank you. Do you know when it will be available in TFS?

**Comment by ilovesoftware** [comment]
I got this response from Shashank, after sending a request:

Hi Michael,

The preview tasks are being relooked at based on feedback. Some of these are likely to be breaking changes. At the moment, we are not entertaining more participants for the preview tasks.
In case you still would like to take a dependency on these tasks, then your best bet is to download the tasks from github & use tfs-cli to upload them into your account after changing the taskid/name in the json.

Thanks
Shashank

**Comment by ilovesoftware** [comment]
Closing this..........
