### ISSUE TITLE
Get-AzureWebSite throws error if VSO doesn't have access to its Azure subscription

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vso-agent-tasks#1232]
Here's the build step output:

> 2016-02-13T01:34:38.9593700Z Executing the powershell script: D:\agent\tasks\AzureWebPowerShellDeployment\1.0.23\Publish-AzureWebDeployment.ps1
> 2016-02-13T01:34:39.1043680Z Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1
> 2016-02-13T01:34:39.7053406Z AzurePSCmdletsVersion= 1.0.1
> 2016-02-13T01:34:39.7303401Z Get-ServiceEndpoint -Name <id> -Context Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext
> 2016-02-13T01:34:50.5152940Z subscription= PIAzurePilot
> 2016-02-13T01:34:50.5152940Z Get-X509Certificate -CredentialsXml <xml>
> 2016-02-13T01:34:50.5552712Z azureSubscriptionId= <id>
> 2016-02-13T01:34:50.5552712Z azureSubscriptionName= <name>
> 2016-02-13T01:34:50.5552712Z azureServiceEndpoint= https://management.core.windows.net/
> 2016-02-13T01:34:50.5602714Z Set-AzureSubscription -SubscriptionName <name> -SubscriptionId <id> -Certificate <cert> -Environment AzureCloud
> 2016-02-13T01:34:50.7102701Z Select-AzureSubscription -SubscriptionId <id>
> 2016-02-13T01:34:50.7402709Z ConnectedServiceName= <id>
> 2016-02-13T01:34:50.7402709Z WebSiteName= <name>
> 2016-02-13T01:34:50.7402709Z Package= D:\Builds\7\a\**\*.zip
> 2016-02-13T01:34:50.7402709Z Slot= 
> 2016-02-13T01:34:50.7402709Z AdditionalArguments= 
> 2016-02-13T01:34:50.7402709Z packageFile= Find-Files -SearchPattern D:\Builds\7\a\**\*.zip
> 2016-02-13T01:34:50.7402709Z packageFile= D:\Builds\7\a\drop\Api\Api.zip
> 2016-02-13T01:34:50.7452699Z Get-AzureWebSite -Name <name> -ErrorAction SilentlyContinue -ErrorVariable azureWebSiteError -Slot production
> 2016-02-13T01:34:53.2352542Z ##[warning]System.NullReferenceException: Object reference not set to an instance of an object.
> 2016-02-13T01:34:53.2352542Z ##[warning]   at Microsoft.WindowsAzure.Commands.Websites.GetAzureWebsiteCommand.Do(Action call)
> 2016-02-13T01:34:53.2352542Z ##[warning]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzureSMCmdlet.ProcessRecord()
> 2016-02-13T01:34:53.2352542Z New-AzureWebSite -Name <name> -Location West US -Slot production
> 2016-02-13T01:35:01.4352281Z ##[error]Conflict: Website with given name <name> already exists.
> 2016-02-13T01:35:01.4352281Z Publish-AzureWebsiteProject -Name "<name>" -Package "D:\Builds\7\a\drop\Api\Api.zip" -Slot "production"  -ErrorVariable publishAzureWebsiteError
> 2016-02-13T01:35:04.3602062Z ##[error]The website <name> was not found. Please specify a valid website name.
> 2016-02-13T01:35:04.3651834Z ##[warning]Cannot get website, deployment status is not updated

**Comment by yaananth** [comment]
Look #526
