### ISSUE TITLE
NuGetUpdater task

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#1235]
There is a NuGetInstaller, NuGetPackager and NuGetPublisher task available. There's currently no task available for the NuGet update command. Is there any plans or interest in providing a NuGetUpdater task with the OOTB build tasks? Or add a generic NuGet task, like the Npm task to run any NuGet command? If so I can provide a PR for this.

**Comment by bryanmacfarlane** [comment]
Adding Matt

**Comment by vtbassmatt** [comment]
No plans to ship such a task. I could be convinced, but don't quite see the value in a CI system. Seems you'd want to do update on a dev machine and check in the resulting changes.

**Comment by pascalberger** [comment]
@vtbassmatt My use case would be to have a CI build automatically update a solution to the latest (prerelease) Version of internal NuGet Packages before building and deploy the build solution to a specific site, so that it is easy to check if solution will still work as expected with updated packages once they were updated.

**Comment by vtbassmatt** [comment]
@pascalberger I see. Would the task do anything other than wrap `nuget update foo.csproj`? The current set of tasks are too unstructured and block our ability to make usability improvements. I'd be more inclined to take a narrow task, especially one that doesn't expose the implementation detail that nuget.exe is under the hood (so no "additional parameters").

We're going to update the current tasks to use the new task lib at some point. If you're going to build a new task, might as well start on the new framework.

**Comment by pascalberger** [comment]
@vtbassmatt Yes, generally it would be just a `nuget update foo.csproj`. But it still needs the possibility to add additional parameters (like eg. for defining inhouse nuget server as source).

How do you plan to provide all the advanced scenarios which currently require additional parameters? Separate inputs for all possibilities? 
How to make sure to support all new features introduced in new NuGet versions? Currently they all can be easily used with the additional parameters.

And does this plans also include eg. the npm task, which currently even is more generic.

**Comment by vtbassmatt** [comment]
Ah, good catch - we need to point to a nuget.config and run our credential extension against it, like the Installer task.

My team and I haven't totally solidified our point of view on the tasks. Taking a snapshot of our thinking, though: The existing NuGet tasks "provide" all the advanced scenarios by doing nothing -- asking the user to pass raw arguments to nuget.exe. That locks us into an unknowable compatibility matrix whenever we want to take new nuget.exe versions. It also leaves holes for unknowing users to fall into.

Going forward, we want to make simple things simple. Making complex things possible is (likely) outside the charter of the discrete tasks. Users with sophisticated needs can write shell scripts modeled on the existing tasks, and any tools we have should be available in the environment (for example the credential extension). More specifically, we've talked about making nuget.exe an implementation detail not exposed to the end user.

We haven't looked at the existing npm task(s). We do plan to take those over once our npm service gets closer to shipping.

@pascalberger I'd really appreciate your input on the above musings. You've clearly done a lot of thinking in this space. Thanks.

**Comment by pascalberger** [comment]
Just a remark regarding the shell script for advanced scenarios approach. This might work for a single repository, but for example in our case we have several hundred repositories in a single team project and maintaining shell scripts in them for build / deployment would be a nightmare. Git submodules are not really a solution with the missing support through the whole toolchain. Of course it would be possible to write custom task, but for simple stuff like eg. restoring NuGet packages from an internal server instead of the default gallery this seems like quite an overhead.

I see the point behind improving usability by simplyfying things, but on the other hand it would be a pity to sacrifice all advanced scenarios for this. I really appreciate the current state where eg. a NuGet task can be used which takes care to call the correct exe and which save me a shell script in every repository just for this. Therefor tasks which make simple things simple but still allow advanced scenarios would be the best solution for us :)

**Comment by mxa0079** [comment]
@vtbassmatt what do you think about Task versioning. If the VSTS team could add native support to task versioning in build/release definitions, do you think your compatibility matrix problems would be solved? Allow you to innovate rapidly without so many compatibility concerns?

**Comment by vtbassmatt** [comment]
@pascalberger Apologies, I meant a task wrapping a script. And I agree - for simple scenarios, the tasks should simply work :) I don't want to take that away. We'll do some more thinking about how to expose power tools to power users without compromising our ability to upgrade.

@mxa0079 Versioning is certainly an option. Depending on how it were done, it might solve this case. But on the other hand, instead of a customer compat matrix, we'd have a customer support matrix: Task version × agent tools version × TFS version (for on-prem). And that same support matrix would manifest as a development compat matrix :(

**Comment by pascalberger** [comment]
Task versioning would be nice indeed. I already discussed this once with @bryanmacfarlane. Already with the current state VSTS updates contain breaking changes, intentional or not. I generally can live with breaking changes, the bigger problem is that customers don't have any choice at which time they happen. Having a new build deployed and all build / release definitions stopped working from one day to another and requiring immediate action, while in the middle of an important project with already being behind schedule is not how one plans it day :) Having the possibility in this cases to switch back to older versions of the task for an immediate workaround and having time to plan in time for a proper fix would be a nice addition. To reduce customer support matrix you could restrict how long previous tasks are supported. This would still give customers the ability and time to react to breaking changes.

**Comment by mxa0079** [comment]
@pascalberger Exactly. [I added this item to VSTS User Voice](https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/12354090-enable-task-versioning-in-vnext-build-and-release). Please vote.

**Comment by pascalberger** [comment]
@mxa0079 I had unfortunately already provided too much feedback for the famous 10-vote-restriction-which-dont-even-allows-you-to-submit-eleven-ideas-restriction over at UserVoice :(

**Comment by vtbassmatt** [comment]
@pascalberger I'm closing the issue, but that doesn't mean I won't look at a PR for this. Thanks.
