### ISSUE TITLE
Retrieving artifacts from release task

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent-tasks#1238]
Hi all,

I'm building a task that should be used in the Release Management. My task needs to retrieve the available artifacts. How do I get a list of available artifacts and get the path/stream of those files?

Thanks

**Comment by chrisrpatterson** [comment]
The release definition will automatically download all artifacts to the build agent.  Can you give me the scenario where you are trying to complete

**Comment by mmajcica** [comment]
Hi @chrisrpatterson, I am trying to search for a particular extension in between available artifacts and I need to get the full path towards the files found in between the available artifacts. Is that possible? In case you would have an artifact uploaded by the build called my.zip, in the release task POsH script, how will you make sure the artifact is there and get it's full path?

Thanks

**Comment by chrisrpatterson** [comment]
Yes the artifacts are downloaded into a known location.  You can read about it here https://msdn.microsoft.com/en-us/Library/vs/alm/Release/author-release-definition/understanding-artifacts#Artifactdownload

**Comment by jonsnowax** [comment]
Can we retrieve multiple files by matching through pattern. If yes, please give example.
