### ISSUE TITLE
Azure File Copy hangs when trying to remove the custom script extension 'WinRMCustomScriptExtension'

### ISSUE THREAD

**Issue by tmccart1** [Microsoft/vso-agent-tasks#1262]
The files make it to the storage account, but not to the VM.  It eventually forces the build to time out.  

Here is the log from my Agent:

06:20:50.265737 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = Uploaded files successfully from source path: 'C:\Agent\_work\2\a\CompositionRoot' to storage account: 'vhdstoragesubom37k2dcds' in container: '1a5b38ca-17c8-439c-ac3b-5da69bb747e8' with blobprefix: '')
06:20:50.281364 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Getting resource group:PERFICIENT.COM-DEV RM virtual machines type resources)
06:20:51.489941 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Count of resource group:PERFICIENT.COM-DEV RM virtual machines type resource is 2)
06:20:51.505567 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]Filtering azureRMVM resources with filtering option:machineNames and filters:USWESTDEVCDCM)
06:20:51.724315 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Getting network interfaces in resource group PERFICIENT.COM-DEV)
06:20:53.763086 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Got network interfaces in resource group PERFICIENT.COM-DEV)
06:20:53.778707 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Getting public IP Addresses in resource group PERFICIENT.COM-DEV)
06:20:54.081128 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Got public IP Addresses in resource group PERFICIENT.COM-DEV)
06:20:54.081128 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Getting load balancers in resource group PERFICIENT.COM-DEV)
06:20:54.206147 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug][Azure Call]Got load balancers in resource group PERFICIENT.COM-DEV)
06:20:54.237397 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]Trying to get FQDN for the azureRM VM resources from resource Group PERFICIENT.COM-DEV)
06:20:54.299889 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]FQDN value for resource USWESTDEVCDCM is perficient-dev.westus.cloudapp.azure.com)
06:20:54.315540 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]Got FQDN for the azureRM VM resources from resource Group PERFICIENT.COM-DEV)
06:20:54.315540 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]Defaulting WinRmHttpsPort of USWESTDEVCDCM to 5986)
06:20:54.331149 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]Enabling winrm for virtual machine USWESTDEVCDCM)
06:20:54.331149 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]Adding custom script extension 'WinRMCustomScriptExtension' for virtual machine 'USWESTDEVCDCM')
06:20:54.346765 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]VM Location : westus)
06:20:54.346765 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = ##[debug]VM DNS : perficient-dev.westus.cloudapp.azure.com)
06:20:54.346765 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = [Azure Call]Getting the custom script extension 'WinRMCustomScriptExtension' for vm 'USWESTDEVCDCM')
06:20:54.726509 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = [Azure Call]Got the custom script extension 'WinRMCustomScriptExtension' for vm 'USWESTDEVCDCM')
06:20:54.741545 BaseLogger.LogConsoleMessage(scope.JobId = 266cd17d-916b-4438-93f2-728b9dce2c2a, message = [Azure Call]Removing the custom script extension 'WinRMCustomScriptExtension' for vm 'USWESTDEVCDCM')
07:19:20.976583 AgentWorkerIPCService.Connect

**Comment by tmccart1** [comment]
I just got a response from the RM team on this, and the fix was to uncheck the "Enable Copy Prerequisites" checkbox.  That did the trick.  Thank you @RoopeshNair !  

I don't want to close this just yet though, because the documentation for this says that it should be checked.  But I am glad that it works!

**Comment by pavanadepu2** [comment]
Could you please share the log file to debug further on the hang issue while removing the custom script extension.

**Comment by tmccart1** [comment]
Hi Pavan,

 

This has been resolved.

 

Thank you,

 

Tim

**Comment by kmkumaran** [comment]
Closing based on Tim's comment.
