### ISSUE TITLE
Set-TaskVariable and Get-TaskVariable cmdlets

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent-tasks#1264]
Hi all,

is there a reason why Set-TaskVariable cmdlet is in Microsoft.TeamFoundation.DistributedTask.Task.Common and Get-TaskVariable in part of Microsoft.TeamFoundation.DistributedTask.Task.Internal? Seems counter-intuitive, as those are complementary actions and should be in part of the same module.

Mario

**Comment by ericsciple** [comment]
This is fixed in the new PowerShell handler/SDK. https://github.com/Microsoft/vsts-task-lib/tree/master/powershell/Docs

**Comment by mmajcica** [comment]
Hi @ericsciple, when will this SDK be available? From which agent version will it be supported? If I read well in the documentation, we could package modules with our task in the future and import them easily, without referencing $PSScriptRoot?

Any blog posts about this argument?

Thanks

**Comment by ericsciple** [comment]
The new "PowerShell3Handler" is in the 94 agent, but doesn't take precedence over the "PowerShellHandler" until 95 agent. Also you can set a variable to control which handler to use (assuming your task carries both implementations): set system.preferpsoverps3 to true or false on the definition to explicitly choose.

I realize now I need to update the docs with this info. Thanks!

**Comment by ericsciple** [comment]
Sorry I missed half your comment. I'll go through your questions one by one this time :)

`when will this SDK be available`
It's available now.

`which agent version`
1.94

`If I read well in the documentation, we could package modules with our task in the future and import them easily, without referencing $PSScriptRoot?`
I'm not sure I understand the question. The SDK needs to be packaged with your task, and placed in the ps_modules folder. The agent will load the SDK packaged with your task, then uses the command Invoke-VstsTaskScript to run your entry script. By the time your entry script is run, the SDK is already imported. Let me know if you have ideas how to make this more clear in the docs, I'm not sure if all the technical details would add too much complication. It's touched on a little in the Testing and Debugging doc.

If you have other modules that you want to consume in your task, you need to import them yourself.

Also you can look at msbuild/vsbuild/publishsymbols which has been ported over. Those tasks currently carry two implementations - old handler and new handler. The older handler implementation will be deleted soon.

`Any blog posts about this argument?`
No blog posts that I'm aware of.
