### ISSUE TITLE
Visual Studio Test w/ coverage enabled doesn't cover the actual assembly

### ISSUE THREAD

**Issue by Allann** [Microsoft/vso-agent-tasks#1265]
Hi,
I have a very strange issue.  Whilst the tests all pass and a coverage file is created, It doesn't cover the working assembly, only the test and xunit assemblies.  Here are the parameters used:
Execution Options:
Test Assembly: **\$(BuildConfiguration)\Jbssa.Core.Tests.dll;-:**\obj\**
Code Coverage Enabled: checked
Run in Parallel: checked
VSTest version: Visual Studio 2015
Platform: $(BuildPlatform) - was set to any cpu
Configuration: $(BuildConfiguration) - was set to release

The coverage file includes the following assemblies:
jbssa.core.tests.dll 93.49%
xunit.assert.dll 8.87%
xunit.core.dll 7.53%
xunit.execution.desktop.dll 55.63%

But does not include jbssa.core.dll which is the actual assembly I'm testing.  When run from within VS2015, I get the following results:
jbssa.core.dll 34.46%
jbssa.core.tests.dll 93.42%

**Comment by nigurr** [comment]
Hi,

Can you mail us your dll directory structure and build definition?
Email: devops_tools at microsoft.com, vsttdta at microsoft.com

**Comment by allendm-msft** [comment]
HI Alan, 

You can download your .coverage file and do some analysis using codecoverage.exe, which is shipped as a part of visual studio. 

[Troubleshooting missing data in Code Coverage Results](http://blogs.msdn.com/b/allendm/archive/2012/06/05/troubleshooting-missing-data-in-code-coverage-results.aspx)

**Comment by Allann** [comment]
Will do.  Let you know soon.  I will send the files requested shortly

**Comment by Allann** [comment]
I have sent the requested email, but @allendm-msft  response was very useful, thank you.  It turns out that PDBs (symbol files) are unavailable/missing.  I'm assuming that's because this was a release build and my release is set to Optimize code.  Makes sense.

I am wondering if the Code Coverage check box in the definition shouldn't have the configuration field on it instead of just a checkbox.  When I build multiconfigurations, I shouldn't be spending time covering DLLs that I don't care about.  Or is there a better way to turn it off when optimized code is generated?

**Comment by jorrit** [comment]
I think there should be generic constraints settable for each build step, so I can skip executing the copy action for the debug build in a combined debug/release multiconfiguration.
