### ISSUE TITLE
Copy and publish build artifacts is quite slow for large amount of files

### ISSUE THREAD

**Issue by rosieks** [Microsoft/vso-agent-tasks#1271]
I'm following this instructions (https://msdn.microsoft.com/en-us/Library/vs/alm/Build/azure/deploy-aspnet5) to deploy my ASP.NET 5 application. The only change that I made is that a copy and publish build output as build artifact instead of publishing it to azure.

Unfortunately my build generate about 900 files. Copying files from output folder to artifacts takes about 10 seconds which is fine. But uploading these files takes about 2 minutes. Maybe it would be good idea to zip these files first and then copy single file and then extract them on the server.

I'm using my own build server hosted on Azure.

**Comment by bryanmacfarlane** [comment]
Sure.  You can add a step to zip the files to your build process.  The publish step is doesn't care about the files - it's just copy these files.  We already do gzip compression over the wire
