### ISSUE TITLE
Xamarin Test Cloud integration- Input required: userDefinedLocale

### ISSUE THREAD

**Issue by glennwester** [Microsoft/vso-agent-tasks#1283]
![screen shot 2016-02-23 at 10 27 06 am](https://cloud.githubusercontent.com/assets/1887597/13262095/0cdd8c6e-da18-11e5-80fd-82746967163e.png)

##[Error] 2016-02-23T18:17:25.183Z: Input required: userDefinedLocale

This parameter is defined in the xamarintestcloud.ts file, but to my knowledge there is no way to specify it? 

I even tried passing in an Optional Argument to satisfy the error (just experimenting) but I still get the same error. 

![screen shot 2016-02-23 at 9 52 50 am](https://cloud.githubusercontent.com/assets/1887597/13262277/e33b11b4-da18-11e5-852f-b6fb16033960.png)

The 'userDefinedLocale' is specified in source here:

https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/XamarinTestCloud/xamarintestcloud.ts
// Get inputs
var app = tl.getInput('app', true);
var dsym = tl.getInput('dsym', false);
var teamApiKey = tl.getInput('teamApiKey', true);
var user = tl.getInput('user', true);
var devices = tl.getInput('devices', true);
var series = tl.getInput('series', true);
var testDir = tl.getPathInput('testDir', true);
var parallelization = tl.getInput('parallelization', true);
var locale = tl.getInput('locale', true);
var userDefinedLocale = tl.getInput('userDefinedLocale', true);
var testCloudLocation = tl.getInput('testCloudLocation', true);
var optionalArgs = tl.getInput('optionalArgs', false);
var publishNUnitResults = tl.getInput('publishNUnitResults', false);

**Comment by yacaovsnc** [comment]
In the "System Language" field, there is an option called "Other" -- it's at the end of the available options.

Once you select "Other", an additional input field should appear, and you can put "da_DK" there.  

You can see how all the options are defined from the task.json file:
https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/XamarinTestCloud/task.json

**Comment by madhurig** [comment]
Fix is merged to master and should be available on Visual Studio Team Services soon: https://github.com/Microsoft/vso-agent-tasks/commit/c8e24979ad0dbd67f1a9af7e37d991a5128607b3

**Comment by madhurig** [comment]
Fix is deployed to Visual Studio Team Services
