### ISSUE TITLE
IISWebAppDeployment: CreateWebsite parameter should be used instead of checking WebSiteName

### ISSUE THREAD

**Issue by Preskton** [Microsoft/vso-agent-tasks#1287]
As part of MsDeployOnTargetMachines,ps1, there is:
```
-not (IsInputNullOrEmpty -str $WebSiteName)
```
 to determine if the task should create or update the target website.  Since the task.json requires the WebSiteName, this condition is always true, meaning the Create-Or-Update-Website function is always executed.  I would like to be able to uncheck the CreateWebsite parameter and skip the process of creating or updating the target website entirely - I have a different part of my pipeline handling that.

**Expected behavior**:

1. *Preferred* Use CreateWebsite to determine whether or not to run Create-Or-Update-Website (similar to how $AddBinding works).
2. Change task.json to allow WebSiteName (and other related parameters) to be not required. I suspect this is less desirable because WebSiteName is used in other places for purposes other than the Create-Or-Update check. Need a way to allow these fields to be not required when hidden but required when visible - not sure if that's currently supported.

**Comment by Preskton** [comment]
See above commit for an example of correcting behavior for 1 above.  I have not tested, but plan doing so later this week and will submit a PR if it feels like the right direction.

**Comment by mvvsubbu** [comment]
Preskton,

Thanks for your help in trying to fix the issue. The required websitename input is controlled by a visibility rule using CreateWebsite. When CreateWebsite is false websitename is not required to be provided and hence it won't call the create or update function. Are you seeing a different behaviour? Can you share the logs when this is happening?

**Comment by mvvsubbu** [comment]
I got your scenario, I think first time you check boxed it and then provided the website name and then disabled the create option. In this case it happens. I will review your PR and provide comments thanks for your contribution.

**Comment by mvvsubbu** [comment]
Fixed PR : https://github.com/Microsoft/vso-agent-tasks/pull/1404 and this will be available in next vsts deployment
