### ISSUE TITLE
Visual Studio Test task uses duplicate test adapters by default

### ISSUE THREAD

**Issue by olegsych** [Microsoft/vso-agent-tasks#1302]
The Visual Studio Test task uses the source root folder as the /TestAdapterPath by default. With [xUnit](https://www.nuget.org/packages/xunit.runner.visualstudio/2.1.0), this makes vstest.console.exe discover multiple copies of the xunit.runner.visualstudio.testadapter.dll, one for each project where the package is referenced, plus one for each instance of the nuget package. Each instance of the test adapter runs all tests in all projects.

**Comment by atinb** [comment]
The default behavior is designed to make sure we help users get their tests working by finding any adapters that exist. To override the default search, you can specify a path in the "Path to Test Adapters" field. Thanks!

**Comment by olegsych** [comment]
The default behavior is executing four thousand tests in a solution that has only four hundred. Test execution is unstable and ignores parallelization constraints. It took us weeks to notice and several days to understand the problem before we could identify the test adapter path as the culprit. AND WE HAVE TWO PEOPLE WHO USED TO WORK ON VSTEST ON OUR TEAM. This is a very bad user experience. Your competitor, AppVeyor just works, correctly, try it to see what the experience is supposed to be.
