### ISSUE TITLE
After updating build number the build rev number does not increase

### ISSUE THREAD

**Issue by MylesArkell** [Microsoft/vso-agent-tasks#1303]
I have found that when I use the ##vso[build.updatebuildnumber] it does update the version number but the build rev number does not update at the end of the build.
This causes me problems as I use this rev number in the prerelease info of my version number eg 1.0.0-meta2016010105
ie version-meta{date}{rev}

How can I update the build number and ensure that the build rev number is updated at the end of the build?

**Comment by chrisrpatterson** [comment]
The Rev is incremented at the beginning of the build based on the uniqueness of the rest of the build number string. If you want to manage the build number then it is up to you to make it unique. You could probably use the built-in scheme and then parse the Rev out to use in your own build number string.
