### ISSUE TITLE
Can't publish symbols to local folder

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vso-agent-tasks#1313]
When I specify ```$(Build.StagingDirectory)\symbols``` as the "Path to publish symbols" in the "Index Sources & Publish Symbols" task I get the following error:

```Unable to associate artifact with resource at location:C:\a\1\a\symbols.```

I want to publish the symbols to a local folder so that I can copy that folder into blob storage, and use the storage account as my symbol store.  I am thinking I will have to create a custom task or powershell script to call symstore.exe myself to accomplish this?

I am doing this all in VSTS.  Perhaps I am not understanding how you intended people to publish symbols with this task when running everything in Azure?

Here is a portion of the log when this happens:
```
2016-02-27T15:26:56.8142237Z ##[debug]Created symbol store path at C:\a\1\a\symbols since it did not exist.
2016-02-27T15:26:56.8472246Z ##[debug]Leaving Lock-Semaphore.
2016-02-27T15:26:56.8512223Z ##[debug]Asserting leaf path exists: 'C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\Agent\Worker\Tools\Symstore\symstore.exe'
2016-02-27T15:26:56.8582234Z ##[debug]Entering Invoke-VstsTool.
2016-02-27T15:26:56.8602246Z ##[debug] FileName: 'C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\Agent\Worker\Tools\Symstore\symstore.exe'
2016-02-27T15:26:56.8632225Z ##[debug] Arguments: 'add /f "@C:\Users\buildguest\AppData\Local\Temp\tmpD27.tmp" /s "C:\a\1\a\symbols" /t "Common" /v "1.0.16058.1"'
2016-02-27T15:26:56.8662248Z ##[debug] WorkingDirectory: 'C:\Users\buildguest\AppData\Local\Temp\'
2016-02-27T15:26:57.0130156Z ##[debug]Finding ID...  0000000001
2016-02-27T15:26:57.0190160Z ##[debug]SYMSTORE: Number of files stored = 1
2016-02-27T15:26:57.0215258Z ##[debug]SYMSTORE: Number of errors = 0
2016-02-27T15:26:57.0248176Z ##[debug]SYMSTORE: Number of files ignored = 0
2016-02-27T15:26:57.0275591Z ##[debug]Exit code: 0
2016-02-27T15:26:57.0324623Z ##[debug]Leaving Invoke-VstsTool.
2016-02-27T15:26:57.0414785Z ##[debug]Entering Unlock-Semaphore.
2016-02-27T15:26:57.0484790Z ##[debug] Semaphore: '@{Stream=System.IO.FileStream; Path=C:\a\1\a\symbols\_lockfile.sem}'
2016-02-27T15:26:57.0584789Z ##[debug]Leaving Unlock-Semaphore.
2016-02-27T15:26:57.1054790Z Start: AssociateArtifact
2016-02-27T15:26:57.1154789Z ##[error]Unable to associate artifact with resource at location:C:\a\1\a\symbols.
2016-02-27T15:26:57.1154789Z End: AssociateArtifact
2016-02-27T15:26:57.1174797Z ##[debug]Leaving Invoke-PublishSymbols.
2016-02-27T15:26:57.1174797Z ##[debug]Leaving C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\PublishSymbols\1.0.19\PublishSymbols.ps1.
```

**Comment by bryanmacfarlane** [comment]
Eric - can copy files task be used in combination of other tasks to achieve this?

**Comment by ericsciple** [comment]
@gregjhogan you can index without publishing (don't specify a publish path). Then, as Bryan suggested, you can use the Copy Files task to copy the instrumented PDB files.

**Comment by gregjhogan** [comment]
@gregjhogan that doesn't give me the folder structure you need for a symbol server.  I believe if I could specify a local folder, I would have exactly what I need to copy out to a blob that would act as a symbol server.

**Comment by gregjhogan** [comment]
@ericsciple that doesn't give me the folder structure needed for a symbol server. I believe if I could specify a local folder, I would have exactly what I need to copy out to a blob that would act as a symbol server.

**Comment by ericsciple** [comment]
I see. If you are using the hosted build machine, you may be able to use `net share` to create a local share during your build. Then you may be able to specify \\\\localhost\\\<share\> or \\\\127.0.0.1\\\<share\> as your publish path.

If you are on your own VM, then you shouldn't have any issues creating a share.

There are other things to consider as well. If you are on the hosted build machine (fresh machine every time), then the symbol store trasaction ID is going to be 1 every time. So you can't just overlay the publish content from multiple builds.

**Comment by gregjhogan** [comment]
I am using hosted agents because I don't want to have to manage my own agents.  When visual studio pulls symbols from a symbol server it seems like it doesn't care about the admin folder or transactions (I tested this out by only copying only the *.pdb folders recursively out to blob storage).  I ended up creating a custom build task to call symstore.exe using a local path.  It just seemed like an artificial limitation that the build task doesn't support this.

If you look at the log above, you can actually see the symstore.exe call succeeds, but then AssociateArtifact fails.  What fails is a call to [Write-VstsAssociateArtifact](Write-VstsAssociateArtifact) with a "-Type 'SymbolStore'".  I can't find the source code for this or any explanation of what this does, so I am wondering could this be skipped if a local path is specified?  If you find a way to support this I think people would be able to use the built-in tasks to easily create and host their debugging symbols in Azure.

**Comment by gregjhogan** [comment]
@ericsciple thanks for the info.



I am using hosted agents because I don't want to have to manage my own agents.  When visual studio pulls symbols from a symbol server it seems like it doesn't care about the admin folder or transactions (I tested this out by only copying only the *.pdb folders recursively out to blob storage).  I ended up creating a custom build task to call symstore.exe using a local path.  It just seemed like an artificial limitation that the build task doesn't support this.

If you look at the log above, you can actually see the symstore.exe call succeeds, but then AssociateArtifact fails.  What fails is a call to [Write-VstsAssociateArtifact](Write-VstsAssociateArtifact) with a "-Type 'SymbolStore'".  I can't find the source code for this or any explanation of what this does, so I am wondering could this be skipped if a local path is specified?  If you find a way to support this I think people would be able to use the built-in tasks to easily create and host their debugging symbols in Azure.

**Comment by ericsciple** [comment]
@gregjhogan Thanks. That's interesting. Looping in Chris to consider this scenario.

fyi - the source code for Write-AssociateArtifact lives here: https://github.com/Microsoft/vsts-task-lib The Vsts noun prefix is added at run-time. However you'll find the source code doesn't do much other than emit a "##vso[...]" logging command. It's really the agent that interprets the command.

I just tested out `net share` on my local machine, and I don't think that will work around your issue after all. I believe it requires you to be elevated.

One more thing to keep in mind. Without accurate transaction information, the transaction can't easily be deleted, i.e. can't leverage symstore.exe to do the delete work for you.

**Comment by gregjhogan** [comment]
@ericsciple good to know, but I personally have never had a need to delete or query a symbol server using symstore.exe.  Maybe other people are looking for more, but if I can put a URL in as a symbol server in the Visual Studio config and hit F11 to step into the code hosted in VSTS, I am golden.  Thanks for the info!

**Comment by chrisrpatterson** [comment]
@gregjhogan Are you simply creating a new container in Azure Storage for each builds symbols?  If so then this will probably work file.  The reason people use the file share mechanism with symstore is you can have symbols for multiple builds in the same store and if builds have dlls that don't change then you get some amount of dedup for storage.  Also symstore.exe lets use delete transactions when builds are deleted by retention policy.

Currently we don't have good symbol store support in VSTS but that is a feature that is being worked on.

**Comment by gregjhogan** [comment]
@chrisrpatterson I have a single container for blobs that I am using for all builds.  symstore.exe creates a folder structure that is unique to each compilation of a DLL (e.g. MyProject.pdb/6549D050E52F4713BDD6084A8116B2741/MyProject.pdb).  I am not sure why you think this is a limitation of my approach?  Blob storage is cheap, so I personally really don't care if I have a bunch of old symbols sitting on my symbol server that might not be referenced by anything (until there is an integrated VSTS solution).

Would you consider skipping Write-VstsAssociateArtifact if the path is a local path?  I was thinking there really wasn't any downside to supporting a local path.  Thanks!

**Comment by gregjhogan** [comment]
I now have multiple builds with multiple releases pushed out to a single container, and it works great.  No I can't delete based on transactions, but I don't see that as a problem.  It would be awesome if you added support for local paths by bypassing the Write-VstsAssociateArtifact call when a local path is specified.

Here is an example of a build that pushes symbols into a blob acting as a symbol server.  The "Publish Symbols" task below is my custom task that simply calls symstore.exe for a local directory.

![image](https://cloud.githubusercontent.com/assets/4112046/13467839/a1ca0778-e065-11e5-8eaa-6113ac897370.png)

**Comment by gregjhogan** [comment]
@chrisrpatterson are you opposed to my suggestion (skipping Write-VstsAssociateArtifact if it is a local path):

> If you look at the log above, you can actually see the symstore.exe call succeeds, but then AssociateArtifact fails. What fails is a call to Write-VstsAssociateArtifact with a "-Type 'SymbolStore'". I can't find the source code for this or any explanation of what this does, so I am wondering could this be skipped if a local path is specified?
