### ISSUE TITLE
[Question] OnPrem build steps for NuGet Packager and Copy Files

### ISSUE THREAD

**Issue by Allann** [Microsoft/vso-agent-tasks#1322]
Whilst having all these tasks here is great and gives us a head start in creating scripts will will run locally, converting them is quite a difficult task (at least for me).  Is there a timeframe for when some of these tasks will make it to On Premise TFS installations.  As a company we cannot use VSO and therefore are quite limited to what we can create as far as CI builds go.
For example, our build agent only includes the following tasks:

- NuGetInstaller v0.1.12
- PowerShell v1.0.5
- PublishBuildArtifacts v1.0.4
- PublishSymbols v1.0.4
- VSBuild v1.0.11
- VSTest v1.0.16

I have successfully added a script which applies the build version to the assemblies and nuspec files (copied from ApplyVersionToAssemblies.ps1).

The only thing that is missing now is the NuGet Packager and Copy Files tasks.  Has anyone been able to make them work locally like they do on vso?  If so, would you be willing to share the steps/scripts?

**Comment by vtbassmatt** [comment]
Each TFS update contains the most recent versions of the tasks. What TFS version and update are you on?

**Comment by Allann** [comment]
recently (3 months) did a new install of TFS 2015 (build 14.0.23128.0) running on Windows Server 2012 R2 with a SQL 2014 database backend.  The build tasks above were the only ones I found in the Agent\Tasks folder.

**Comment by vtbassmatt** [comment]
Update 1 is available, and update 2 is coming very soon. Those will both have updated versions of tasks.

Please file a separate issue on not being able to build the repo. I don't have any expertise there, but someone else will weigh in.
