### ISSUE TITLE
SonarQubePreBuild shows password in clear

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent-tasks#1325]
Hi I just noticed that if I do enable system.debug, I can see the password of the account set for the SonarQube endpoint in clear in the logs. The best thing will to show an asterisk or anything at all. It is a security issue that should be fixed as soon as possible.

**Comment by bgavrilMS** [comment]
Hi @mmajcica, thank you for reporting this. I cannot repro this however - I ran builds using the hosted agent and a local agent and I can see the password being starred out:

Arguments: begin /k:"test" /n:"test" /v:"2" /d:sonar.host.url="http://mysqserver:9000/" /d:sonar.login="********" /d:sonar.password="********" /d:sonar.verbose=true

Can you tell me what version of the agent you are using? You can find this by going to the Control Panel > Agent Pools, select your agent and go to the Capabilities tab. My Agent.Version is 1.95 on both hosted and local agent.

**Comment by mmajcica** [comment]
Well it may be then solved already. It is on-premise TFS 2015 with Update 1 applied. Taks version is 1.0.28 in that case and the agent version is 1.89.1.

**Comment by bgavrilMS** [comment]
I see. The fix is at the agent level. I have reported the problem a while back and it was fixed somewhere in sprint 91. It should definitely be available with TFS 2015 Update 2. I don't know the exact date of release for Update 2, but an RC has already been released, so it shouldn't be long now.

**Comment by bgavrilMS** [comment]
Oh - there is also a workaround for this until you get the fix. Open your build definition and create a build variable in the Variables tab. Any var name will do, and put the SQ password as value. Then mark it as secret. What will happen is that any occurrences of the password will be starred out. Be aware though that if someone deletes this variable then the password will be printed in clear again.

**Comment by mmajcica** [comment]
@bgavrilMS this will work only if I was passing this values into parameters to build tasks. This credentials are set on the Endpoint level, so variables can't be used. Can't they?

Mario
