### ISSUE TITLE
Could not depoy IISWebAppDeployment task to local TFS

### ISSUE THREAD

**Issue by arturas-peceliunas** [Microsoft/vso-agent-tasks#1345]
Hi, have issue with **IISWebAppDeployment** task in tfs2015 update 2 RC1

I have uploaded IISWebAppDeployment task with tfx utile to tfs (on site), but this task not visible in UI. 
When trying again upload, get error message, that this task already been uploaded.
When trying get uploaded tasks from server with **tfx build tasks list** this task also not visible.
When trying delete this task, get error that not found.

Any suggestion?

Thanks a lot,
Arturas

**Comment by kmkumaran** [comment]
IISWebAppDeployment task is marked as "preview" and is bundled in TFS. If you want a private copy of the same, please do following before you upload the task a) in task.json remove the "preview" in visibility. b) Change the Id (guid) to a new guid

**Comment by arturas-peceliunas** [comment]
thank you, it works

**Comment by gheeres** [comment]
I wrote a blog post on this yesterday: [TFS / Release Management: Enable IISWebAppDeployment Task (or deploy your own custom tasks)](http://blog.heeresonline.com/2016/03/tfs-upload-task/)
