### ISSUE TITLE
PowerShellOnTargetMachines: Error: Relative path is not supported. The related file/directory is: 'c:\inetpub\wwwroot

### ISSUE THREAD

**Issue by karlrissland** [Microsoft/vso-agent-tasks#1349]
I am using the PowerShellOnTargetMachines Task to run DSC on a remote server.  I can run the DSC file from a PowerShell Command prompt and an admin command prompt just fine however when I run it through the task I get the relative path error.  

I use the session variable option to setup some session variables for the following DSC script;

-----------------------------------------------------------------------------------------

Configuration SampleWeb
{
	Node $env:COMPUTERNAME
	{
		File CopyDeploymentBits
		{
			Ensure = "Present"
			Type = "Directory"
			Recurse = $true
			SourcePath = $SourcePath
			DestinationPath = $DestinationPath
		}
	}
}
SampleWeb -Verbose -OutputPath c:\dsc\web

Start-DscConfiguration -Path c:\dsc\web -Wait -Verbose

---------------------------------------------------------------------------------------------

Given that I can run the script from a local command line without issue and haven't found any other workarounds, I figured it was time to submit this as an issue.

**Comment by pryenugu** [comment]
Hi @karlrissland.
Your DSC configuration seems fine. Instead of specifying the -OutputPath while generating the mof simply just output the mof like this: "SampleWeb -Verbose". Also you do not need to explicitly do a Start-DscConfiguration, the task internally handles it (Mainly because of protocols like HTTP and HTTPS which need to be accounted for). So your DSC script should look something like this:

Configuration SampleWeb
 {
 Node $env:COMPUTERNAME
 {
 File CopyDeploymentBits
 {
 Ensure = "Present"
 Type = "Directory"
 Recurse = $true
 SourcePath = $SourcePath
 DestinationPath = $DestinationPath
 }
 }
 }
 SampleWeb -Verbose

Here is some documentation we had on ReleaseManagement on how to run the DSC script:
https://msdn.microsoft.com/en-us/library/vs/alm/release/previous-version/release-without-agents

**Comment by mvvsubbu** [comment]
Are you still facing issue with PowerShell On Target Machines task? Should I go ahead and close the issue?

**Comment by mvvsubbu** [comment]
Assuming that you are unblocked I am going ahead and closing the issue. If you still have issue you can mail to RM_Customer_Queries at Microsoft dot com or reopen the issue

**Comment by Mccrosoft** [comment]
I am also having this issue, where the $SourcePath is setup in a session level variable pointing to a UNC share that has my files on. Executing the MOF file via Powershell-ISE works correctly, but when the same DSC script is executed through RM2015 I get the Relative path issue described above.

The only difference I could see is some weird escaping/formatting that the system appears to perform when using session level variables, but not sure if this is causing the actual problem.

**Comment by karlrissland** [comment]
So the way I got around the problem was to write my DSC script as if I were going to run it as a script file from the command line.  i.e. not the way you would do it with the older release management DSC scripts.

So, I was getting the error when I just had;
```
Configuration SampleWeb
{
	Node $NodeName
	{
		#NOTE: IIS Role install and base feature config is done
		#      via the ARM template and associated DSC.  Perfectly ok
		#      to do that here instead

		File CopyDeploymentBits
		{
			Ensure = "Present"
			Type = "Directory"
			Recurse = $true
			MatchSource = $true
			SourcePath = $SourcePath
			DestinationPath = $DestinationPath
			Force = $true
			Checksum = "modifiedDate"
		}
	}
}
```

I had to add everything to the script;
```
#Parameters to pass to script file
Param(
[Parameter(Mandatory=$True)]
[string]$NodeName,

[Parameter(Mandatory=$true)]
[string]$SourcePath,

[Parameter(Mandatory=$true)]
[string]$DestinationPath
)

#Output parameters for debug
write-host $NodeName
write-host $SourcePath
write-host $DestinationPath

#Setting up node as trusted host prior to configuration
set-item WSMan:\localhost\client\trustedhosts -value $NodeName -force

Configuration SampleWeb
{
	Node $NodeName
	{
		#NOTE: IIS Role install and base feature config is done
		#      via the ARM template and associated DSC.  Perfectly ok
		#      to do that here instead

		File CopyDeploymentBits
		{
			Ensure = "Present"
			Type = "Directory"
			Recurse = $true
			MatchSource = $true
			SourcePath = $SourcePath
			DestinationPath = $DestinationPath
			Force = $true
			Checksum = "modifiedDate"
		}
	}
}

#create MOF File
SampleWeb -Verbose -OutputPath c:\dsc\web

#Apply Configuration
Start-DscConfiguration -Path c:\dsc\web -Wait -Verbose
```

Then it worked.
