### ISSUE TITLE
VsTest in parallel builds doesn't make sense for Windows Universal Apps that build non-Windows-server platforms such as ARM

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vso-agent-tasks#1353]
Parallel builds in VSTS builds are great, simple, and provide cheap optimizations for build times. However, we have trouble incorporating test in our UWP application as we build for x86, x64, and ARM, platforms. Ideally, the VSTest runner would 'skip over' ARM tests (as they cannot be run on the x64-based build agents) during the build, and running those tests can happen further down the line in the release automation.

How would incorporating a flag to 'skip' testing specific platform/configuration combinations work for people?

I am happy to do the work, but I'm looking for comments/better solutions first.

**Comment by atinb** [comment]
Hi Derek,

Does it not work if you specify exclusion patterns for ARM platform? For example,  **\$(BuildPlatform)\*test*.dll;-:**\ARM\*test*.dll

Thanks!

**Comment by atinb** [comment]
Closing as per comments in #1358
