### ISSUE TITLE
VsTest agent task doesn't work as expected for multiple UWP unit tests

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/vso-agent-tasks#1354]
Using a minimatch pattern on VsTest to obtain the .appx files that need to be executed for UWP unit tests using VsTest fails.

VsTest can only handle a single UWP unit test package on the command line at a time.

Would it be possible to add a switch to 'process resolved assemblies/packages individually' so that each resolved file from the minimatch pattern given to the task is executed one at a time? 

I am happy to do the work but I'm looking for comments/better solutions!

**Comment by atinb** [comment]
Hi Derek,

You can use the Multiconfiguration setting and supply comma separated values for each of the appx files or add multiple VSTest tasks and define a pattern that only matches one of the appx files.

Thanks!

**Comment by d3r3kk** [comment]
I don't understand what is meant by using the 'Multiconfiguration' setting.
- The Multiconfiguration setting in the options tab for the entire build definition itself? This might be useful if all you are doing is running vstest I suppose.
- I believe the more usual use case would be running vstest during a build cycle where the Multiconfiguration setting would be used as the list of configurations to build and then test. You would not be able to capitalize on this usage of the field for handling multiple appx files if you were using Multiconfiguration for this purpose.

For the other solution you provide, you are correct. This does work, however I believe this is a bad user experience for the designer/maintainer of the build system as they would have to:

1. Be involved to add another VSTest task each time a new test appx is added to the solution being built.
2. Create a lot of unnecessary noise in the build definition itself. Imagine a solution that produces 8 or more test appx files, the build definition quickly becomes unweildy for the user to get a clear overview of what's going on.
3. Breaks the usage pattern of VSTest with it's handling of DLLs versus handling APPX files. Users are used to giving minimatch patterns to match all DLLs, why can't they have the same for APPX files too? (Currently vstest.console.exe is the shortcoming here, but we can very simply correct this here, and if vstest.console.exe is ever corrected to handle multiple appx files at once this solution will not break anything).

**Comment by atinb** [comment]
Like you say, the root cause is that vstest.console.exe only handles one appx file at a time. I have added an item to our backlog to see if we can loop over all appx files discovered one at a time.
