### ISSUE TITLE
How to use git lfs with hosted agents

### ISSUE THREAD

**Issue by mabead** [Microsoft/vso-agent-tasks#1356]
I use git lfs to store the large files of my repo. I then try to build this repo with hosted agents. My build is pretty simple. It has a single task: Execute PowerShell. In the invoked script, the first thing that I want to do is to fetch my lfs dependencies. I therefore have the following in my script:

    & git lfs fetch

Unfortunately, my build fails with the following error: 

```
2016-03-04T19:49:05.7021988Z ##[error]git: 'lfs' is not a git command. See 'git --help'.
2016-03-04T19:49:05.7031986Z ##[error]Did you mean this?
2016-03-04T19:49:05.7041987Z ##[error]	flow
```

Since I can't install anything on hosted agents, how am I supposed to have git lfs available?

Then, once it will be available, I expect to have another problem... how to use the oauth token from the SYSTEM_ACCESSTOKEN environment variable. Issue  #962 talks about the oauth token problem but the solution is not clear.

**Comment by pascalberger** [comment]
For a possible solution how to use git-lfs with the OAuth token see https://github.com/github/git-lfs/issues/906#issuecomment-182910526. Putting the OAuth token in the remote url as suggested in #962 is currently not supported by git-lfs.

**Comment by mabead** [comment]
@pascalberger You are refering for a solution for the oauth token. But my first problem is that 'git lfs' is not even available from my powershell script. Have you done it yourself on hosted build agents?

**Comment by pascalberger** [comment]
@mabead Sorry I don't use the hosted agent. If you are allowed to install software and have internet access during build you might be able to install git-lfs using the [Chocolatey package](https://chocolatey.org/packages/git-lfs). This is a technique often used with AppVeyor for GitHub repositories, but don't know if it will work with VSTS hosted agent.

**Comment by mabead** [comment]
@pascalberger I finally understood that the command "git.exe lfs fetch" is equivalent to 'git-lfs.exe fetch'. I therefore added git-lfs.exe to my git repo to be able to use it during the build without having to dynamically download it. I can now correctly call 'git-lfs.exe fetch' and it now fails saying something different:

    Git credentials for https://xyz.visualstudio.com/DefaultCollection/_git/GitSandbox not found.

As you suggested, I read [github/git-lfs#906 (comment)](https://github.com/github/git-lfs/issues/906#issuecomment-182910526) that suggest to put the username + oauth token in a file and then configure the credential manager to use this file:

```
$psPath = Join-Path $PSScriptRoot 'pw.txt'
git config --global credential.helper "store --file=$psPath"
'https://username:oauth_token@xyz.visualstudio.com' > $psPath
.\GitLfs\git-lfs.exe fetch
```
Unfortunately, this still fails the same way. Have you tried this strategy yourself?

**Comment by pascalberger** [comment]
@mabead Your url looks wrong. Should be `https://xyz.visualstudio.com/DefaultCollection/xyz/_git/GitSandbox`

**Comment by mabead** [comment]
See [here](http://stackoverflow.com/a/35876645/2679757) and [here](http://stackoverflow.com/a/35876342/2679757) to see how I was able to make git lfs work with VSTS hosted agents.
