### ISSUE TITLE
System error 53 has occurred Deploying to Hosted Windows Server

### ISSUE THREAD

**Issue by eriksendc** [Microsoft/vso-agent-tasks#1370]
Hi All,

I'm trying to orchestrate a release using VSTS release management that deploys our .NET web application to a Windows server machine (2012 R2). I've configured a Windows Machine File Copy task to get the artifacts to the server. As per the Windows Machine File Copy help page (https://msdn.microsoft.com/en-us/Library/vs/alm/Build/steps/deploy/windows-machine-file-copy) I created a firewall configuration to allow port 5985 and 5986 traffic through, I also validated that UNC remote restrictions were disabled.

When my release runs it fails with "System error 53 has occurred" when it gets to the Windows Machine File Cop step. Any help with this would be greatly appreciated.

**Comment by eriksendc** [comment]
A little more on this... So I opened up our firewall completely for a few minutes. Ran my deployment, and the file copy did succeed. So there must be more than just ports 5985 and 5986 needing to be opened. What port(s) does Robocopy use?

**Comment by ericsciple** [comment]
probably the file share port, 445 IIRC

**Comment by eriksendc** [comment]
Yup. That's what I found. Did a trace at our firewall with no firewall rules in place and the traffic is coming on port 445. I added a rule for that and now things are working. Leaves me feeling a bit unsettled having port 445 open to the world, though. The traffic today came from a Microsoft IP address 23.99.88.94. It would sure be nice if there was a known IP address or address range that release traffic would be hitting me from so I could tighten the opening of port 445 to only that IP address or address range...

**Comment by eriksendc** [comment]
I do think that the document I mentioned in my initial post should be updated to let people know about the need to open port 445. And there wasn't any traffic on the ports that were mentioned (5985 and 5986).

**Comment by kmkumaran** [comment]
@eriksendc, for copying files into machines in Azure, you can use AzureFileCopy task. That would not require you to open SMB port.

**Comment by mvvsubbu** [comment]
Eric,

I am closing the issue as the windows file copy task is not designed for this purpose, instead you can use Azure File Copy task. If you face any issues with Azure File Copy task feel free to reach out us at RM_Customer_Queries at Microsoft dot com

**Comment by eriksendc** [comment]
I'm not deploying to azure, so I'm not understanding the suggestion to use Azure File Copy.

**Comment by eriksendc** [comment]
How else would one expect to copy files? Anyways, at this point my main suggestion to you all is to update the page of the documentation (see my original post on this thread) and include notes about needing port 445 open in addition to 5985/5986.

**Comment by froeschel** [comment]
@eriksendc I'm having the exact same issue. I get a System 53 error. I have opened the firewall, but the error remains. Maybe there is something wrong with my UNC setting. Can you share waht you have done to solve this?

**Comment by froeschel** [comment]
Thank you for the answer @eriksendc ! I will give it a try. Initially I had hoped it was much easier to deploy from VSTS to an non Azure server. Have a nice weekend!

Regards,
Christoph
