### ISSUE TITLE
Referencing an external nuget.config file

### ISSUE THREAD

**Issue by cwoolum** [Microsoft/vso-agent-tasks#1381]
I'm looking at the Nuget installer ps1 and it looks like this line implies that you can reference a file outside of the current git repository. Would I just reference that as an absolute path?

```
if($nugetConfigPath -and ($nugetConfigPath -ne $env:Build_SourcesDirectory))
```

**Comment by vtbassmatt** [comment]
Yes, I don't see why that wouldn't work.

**Comment by cwoolum** [comment]
Confirmed this works by using C:\pathtomy\nuget.config

**Comment by vtbassmatt** [comment]
:+1:
