### ISSUE TITLE
VS test runner tests running slower in VSO build compared to running locally on build agent

### ISSUE THREAD

**Issue by adityaj-msft** [Microsoft/vso-agent-tasks#1384]
Hello

We have own our build agent pools (azure VMs) for vso builds and unit tests. We are currently using VS2013 update 5. 

We have noticed that running unit tests through the Visual Studio test runner task (Invoke-VSTest) is considerably slower than if we were to run those tests directly via VisualStudio installed on the build agent machine. For our builds the test run times are three times longer when run through the VSO build instead of locally on the machine.

Any ideas/know issues on test or build settings that could be contributing to the difference in runtimes?

Aditya

**Comment by atinb** [comment]
Hi Aditya
How much of a time difference are we talking about? Can you send me the build logs? If possible, re-run the build with ‘system.debug’ as true in variables and send the logs to atinb at Microsoft dot com
Thanks!
