### ISSUE TITLE
possible to run PowerShellOnTargetMachines.ps1 from powershell to troubleshoot?

### ISSUE THREAD

**Issue by github-man** [Microsoft/vso-agent-tasks#1390]
Hi,

The line "$environment = Register-Environment -Enviro........." in PowerShellOnTargetMachines.ps1 fails when running for our Powershell on Target Machines task. 

Trying to debug this by running PowerShellOnTargetMachines.ps1 manually in powershell. However it fails because the  $distributedTaskContext parameter is null when it's run manually. Is there anyway to set this without running it in a build?

Cheers

**Comment by github-man** [comment]
Hi folks,

The workaround we are doing now is to run a local powershell task step (instead of a remote powershell task) and have that local powershell script call the powershell scripts to run on the remote servers. It works but ideally we would like to use "Powershell on Target Machines" directly. 

The fact that we can run remote powershell scripts from a local powershell script means we are confident all the security etc is set up correctly. It's a tricky one to figure out how to troubleshoot why "Powershell on Target Machines" task is failing. 


Many thanks

**Comment by chshrikh** [comment]
@ github-man
Hi ,

What error you are getting for "$environment = Register-Environment..." ? Is it possible for you to share the agent logs ?
You can also mail the details to - RM_Customer_Queries at Microsoft dot com

Thanks

**Comment by chshrikh** [comment]
@ github-man
Hi ,
As of now you will not able to debug 'PowerShellOnTargetMachines.ps1' . It will work only with agent context .

If you have any other issue you may mail to RM_Customer_Queries at Microsoft dot com.

Thanks
