### ISSUE TITLE
Can we add PSSessionOptions to the PowerShellJob.ps1 / Invoke-PsOnRemote

### ISSUE THREAD

**Issue by johnfleenor** [Microsoft/vso-agent-tasks#1394]
I would like to be able to pass session options like SkipRevocationCheck and change the OperationTimeout.  Not sure if it is possible to use one of the other parameters to accomplish this.  When I have tried to add -UseSSL or -SessionOption (New-PSSessionOption -NoEncryption -NoCompression -SkipRevocationCheck) that would normally be on Invoke-Command in the scriptArguments  I think the Invoke-PsOnRemote does not accept the parameter.  
Or maybe add a SkipRecocationCheck like the skipCACheckOption

**Comment by pryenugu** [comment]
Hi @johnfleenor,
Currently the task does not allow to expose those parameters like SkipRevocationCheck. The task internally add the UseSSL parameter if the WinRM protocol is HTTPS. What is the scenario you would want to SkipRevocation check? You would be better off using HTTP instead of HTTPS in that case, since it would be really insecure to skip revocation check.

**Comment by johnfleenor** [comment]
The exposing the PSSessionOption would also allow for Operation and Idle timeout.  When a script hangs it takes 3 minutes to timeout by default.  When I make a script call I can't see what it is doing. So I remote the the box and check the powershell logs for event errors then I queue up a build or cancel each of these take time.

**Comment by pryenugu** [comment]
@johnfleenor, In our implementation of the task the timeout is much more layered than just the Operation and Idle timeout. We currently do not have plans to expose the PSSessionOptions at the task or the cmdlet layer. Thanks for your feedback, for now if you would like more flexibility in the way your script runs in the remote machine you can consider using the normal PowerShell task and establish a remote session and execute scripts.
