### ISSUE TITLE
VS Test Task run parallel tests

### ISSUE THREAD

**Issue by TestO2015** [Microsoft/vso-agent-tasks#1399]
We configured MaxCpuCount to 0 (use max number of cores available) in the .runsettings file for the task but tests were still run sequentially.

The tests are contained in several assemblies which share a common base class and run on a single Test Agent with 12 cores using the default Microsoft.VisualStudio.TestService.VstestAdapter. The TFS version is 2015.1.

Is parallel execution supported?

**Comment by pvlakshm** [comment]
Yes, it is.
Can you tell me more about your scenario, please. Did you associate the .runsettings file with the run?
You can do that by providing the path to the file in the "Run Settings File" control in the Execution Options group.

**Comment by TestO2015** [comment]
Thanks for your reply,

Yes, the .runsettings file is specified but under the 'Test Settings' group. https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/RunDistributedTests/README.md.

Here's the contents:
<RunSettings>
  <RunConfiguration>
    <TargetPlatform>x64</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
    <MaxCpuCount>0</MaxCpuCount>
  </RunConfiguration>
</RunSettings>

**Comment by atinb** [comment]
@TestO2015 
Looks like you are using the Test Agent and not the VS Test task as mentioned in the subject. With Test Agent, each Agent is only given 1 dll to execute at a time. The parallel feature you are trying to use also works at the assembly level and hence the tests are being run serially.

**Comment by TestO2015** [comment]
Thanks @atinb that explains it.

I can see the VsTest task https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/VsTest/README.md runs on the Build Agent however.

We have need to run the tests on a separate isolated machine so we will continue exploring for a way to run them in parallel on the Test Agent. Please advise if there is another way to do it.

**Comment by atinb** [comment]
If you set up multiple Test agents, your assemblies will be distributed on those Test agents and will be run in parallel. The ability to make distribution to Test agents configurable is on our backlog but is 3-6 months out. This will help with the 1 Agent with parallel scenario

**Comment by atinb** [comment]
This feature to distribute tests based on the number of machines is now live on Visual Studio Team Services and will be available in the next version of TFS. See https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/21/remote-testing-distributing-tests-based-on-number-of-machines/ for information on enabling the feature.
 Thanks!
