### ISSUE TITLE
"XUnit" Test Reporting Option is Slightly Confusing

### ISSUE THREAD

**Issue by darthtrevino** [Microsoft/vso-agent-tasks#1401]
The 'Report Test Results' feature allows you to emit test results in a few formats: JUnit, XUnit, NUnit, and VSTest. XUnit in this case is XUnit.NET. (https://github.com/Microsoft/vso-agent-tasks/blob/ffe700401ac0ab9f4c2d50664ff3589f6025edda/Tasks/PublishTestResults/task.json#L39)

The problem with naming this "xunit" is that the Ant Project describes "xunit" as the standardized output format for JUnit, and other test runners like Mocha use that format. So in a NodeJS environment where I'm generating test results in Mocha using the "xunit" test reporter, it's a little weird to have to use the "JUnit" test reporter.

Feel free to file this issue straight to the trashcan, but I'd recommend renaming the "XUnit" option to "XUnit.NET".

https://google.github.io/rich-test-results/xunitxml
https://github.com/mochajs/mocha/blob/cb4248bbebee7b24dcafc774ff15b74f6a9c6973/lib/reporters/xunit.js

**Comment by atinb** [comment]
Thanks for the suggestion Chris. Most people know xUnit.net as xUnit. Hence I will keep the format name the same.

**Comment by mlabrum** [comment]
+1 as someone who doesn't use .net, this bit me and caused quite a bit of confusion.
