### ISSUE TITLE
Tests only running on 1 machine in machine group of 5

### ISSUE THREAD

**Issue by gschultz77** [Microsoft/vso-agent-tasks#1410]
So I have the following setup;
- Machine group with 5 VMs

A TFS 2015 build which includes;
- Task to deploy the test agent to the machine group
(works fine)
- Task to run Selenium based tests using the test agent on that machine group
This _works_, but only runs tests on 1 of the VMs in that machine group. Also it's not the same machine on each test run. 

I haven't specified a run or test settings file. Do I need to? Does the old config around testsettings files and bucket size still apply as it did pre VS 2015?

Also when the tests are running, there is no real-time reporting of test results when I view the active test run in TFS 2015 - it only updates with succeeded/failed tests when the test run completes?
The tests themselves are running and succeeding fine.

**Comment by acesiddhu** [comment]
Hi
Are you using Run Functional task to run these tests? Are all the test in one test assembly? Today RunFunctional test task only distributes based on test assembly. so if you have multiple tests in one dll it wont distribute across VMs.

**Comment by gschultz77** [comment]
Yes, although we're running TFS 2015 update 1, so I think the task has a slightly different name to "functional" tests as it's been named in update 2 RC 2. 

Yes, the tests are all in a single assembly. 

I'm surprised to hear that tests will only be distributed across VMs if you use multiple assemblies. That doesn't sound like a a typical use case.  

Our use case is approx 600 Selenium UI tests which in order to run reasonably quickly we'd like to distribute over several VMs. It sounded like targeting the test run against a machine group would achieve this. 

Are there any plans to support this?

Thanks.

**Comment by nigurr** [comment]
Hi,

It's in the plan however we don't have any timelines presently. :)

**Comment by atinb** [comment]
We are committed to doing this work. Like Nitin said, timelines are still fuzzy but you are looking at 3-6 month timeframe.
Thanks!

**Comment by gschultz77** [comment]
Thanks guys. It'll be great when this functionality is available.

**Comment by atinb** [comment]
This feature is now live on Visual Studio Team Services and will be available in the next version of TFS. See https://blogs.msdn.microsoft.com/visualstudioalm/2016/06/21/remote-testing-distributing-tests-based-on-number-of-machines/ for information on enabling the feature.
 Thanks!
