### ISSUE TITLE
Nuget Packager Build number Regex doesn't support Pre-Releases

### ISSUE THREAD

**Issue by TErenberger** [Microsoft/vso-agent-tasks#1411]
Pre-Release nuget packages are conventionally denoted by a trailing -{text}#. When this format is used in the build number, only the #.#.#.# format is parsed. 

The alternative, using -Version, does not work well enough as the $(Rev:r) variable is not exposed.

A change to the regex string used to parse the version number to allow for pre-release format would help with this issue.

**Comment by vtbassmatt** [comment]
Feel free to send a PR. I'm not spending cycles on it because I want to overhaul how we provide tools to version packages, and kludging in more regex stuff from the build number isn't aligned.

Note: The implementation looks for "\d.\d.\d" or "\d.\d.\d.\d" anywhere in the build number. It's possible to have any other text on either side of the version number, quite likely delimited by a dash. If I change the regex, I'll suddenly start adding -prerelease text to unknown customers' version numbers. This might have to be an opt-in feature (or at least opt-out).

**Comment by TErenberger** [comment]
@vtbassmatt Do you have any insight on why the variables allowed in the general>build number field are not available to be used in other parts of the build definition?

One workaround to the issue of pre-releases would be the ability to do -Version $(year:yyyy).X.X.X-beta$(Rev:r) but those variables are not exposed to the other tasks.

The lockdown of those variables essentially forces one to use the "Use build number as package version" option, which explicitly links the build number format to the package version scheme. In our team we try to keep all the general>build number formats the same for all builds and having that explicit link presents problems down the road when the need to change either one arises.

I have also experimented with the VSTS Packaging API preview, which looks to be very promising for usage in automating the versioning of internal packages. Is there any plans to improve the versioning capabilities of this VSO task type, or is that expected to fall on the individual team's shoulders?

An extra bonus question: Build.Repository.Name variable does not appear to be available to the general>build number format nor appeared to work in the tasks arguments (IIRC). Since build definitions have 1-1 relationship with repositories, is there a reason why this particular variable seems so elusive?

If there is a better place to bring the issue of general>build number variable parity, could you please point me in the right direction for that issue?

**Comment by vtbassmatt** [comment]
Hi @TErenberger. I can help with the package versioning questions. For the other build questions, please open a new issue and someone from the core build team will answer them.

PR #1253 adds the ability to specify your own version number as an environment variable to the Pack task. You could then layer in GitVersion or whatever custom logic you want for generating version numbers. What specifically were you looking for in terms of the packaging API? Feel free to email me at mattc@xbox.com if you want to discuss in detail.
