### ISSUE TITLE
Test using test agent task - test run details not updating in real-time

### ISSUE THREAD

**Issue by gschultz77** [Microsoft/vso-agent-tasks#1413]
I have a build setup in TFS 2015 update 1 that uses the "Visual Studio Test using Test Agent Task" to run Selenium tests on a machine group.

When the run starts the console window for the build provides a link to the test run;
![testrun1](https://cloud.githubusercontent.com/assets/17271552/13884692/1092c51e-ed27-11e5-9bfb-c1b699e9a2af.png)

The tests begin running on the VM (and working) but the tests in the test run page remain reporting "None" as the outcome;
![testrun2](https://cloud.githubusercontent.com/assets/17271552/13884794/763eb92c-ed27-11e5-8920-cb15d19ae8ef.png)

When the test run completes and I refresh the test run page all tests report as successful.

Why does the test run not report in real-time? Is their some specific config to make this work?

**Comment by atinb** [comment]
We upload results after finishing execution of the set of tests given to an agent. From #1410 it sounded like all your tests are currently going to 1 machine, which would mean all results are uploaded only at the end. 
Also, the Test Results tab in Build Summary (image you pasted above) only shows results once the run is complete. You can go to the Runs tab in the Test Hub to see test results as and when they are available, even for in progress runs (image below)

![testhub-runs](https://cloud.githubusercontent.com/assets/12844776/13944233/a070d220-f029-11e5-889e-32b3d1ccc86b.JPG)

**Comment by aivendor** [comment]
@gschultz77 
Did you get  a solution for it? I met the same problem and I've no idea.
And the test filters seem not to work for selenium test.
