### ISSUE TITLE
Hard-coded destination machine in Web Deploy task

### ISSUE THREAD

**Issue by kfrajtak** [Microsoft/vso-agent-tasks#1420]
Hi, 

the web deploy task has hard-coded destination of a synchronization operation (the value of `-dest` is always `auto`). Are there any plans to extend it and add parameters that will allow me to change it. The cmd (`myweb.deploy.cmd`) file created by `msbuild` with these parameters `/p:CreatePackageOnPublish=true /p:DeployOnBuild=true` has the capability of changing it.

Thanks for your answer,
Karel

**Comment by mvvsubbu** [comment]
Hi Karel,

Can you help me understand what is the scenario you are trying to achieve and how making destination user input will help?

**Comment by kfrajtak** [comment]
Hi @mvvsubbu,
I am trying to deploy a web site using msdeploy. Right now, I'm using CLI to execute the CMD file that is created during the build and since the deployment agent runs on a different machine I have to specify it as well (`/M` here or `-dest` for `msdeploy.exe`)

    Project\obj\Debug\Package\Project.deploy.cmd 
      /Y 
      "/M:https://MsDeployAgent:8172/MSDeploy.axd?site=DeploymentSiteName" 
      "-setParam:name='IIS Web Application Name',value='DeploymentSiteName/web'" 
      -allowUntrusted 
      /u:MsDeployUserName
      /p:MsDeployPassword 
      /A:Basic

But maybe be my approach is wrong and `-dest:auto` is okay when the deployment agent (i.e. machine configured for web deploy) is also a build agent and the deployment will be executed "locally".

**Comment by mvvsubbu** [comment]
IIS Web Deploy task deploys to a any remote machine (deployment machine) by running a powershell script locally on the deployment machine using ps remoting and hence in your scenario also you can use this task.

Let us say you have a build agent machine "Agent1" and deployment machine "deployment1" in this case your deployment of website happens on machine "deployment1" and the task execution happens on agent machine "Agent1", from Agent1 we connect to remote machine and run deployment script for website on "deployment1". Please try the task and let us know it worked or not. For any further queries you can mail to RM_Customer_Queries at Microsoft dot com.
