### ISSUE TITLE
DeployVisualStudioTestAgent fails after downloading the agent

### ISSUE THREAD

**Issue by huserben** [Microsoft/vso-agent-tasks#1432]
Hi

I'm trying to run my Automated UI Tests on a Virtual Machine.
For this I'm using the DeployVisualStudioTestAgent Taks.

Somehow it does not get very far and fails with the following error message:
##[error]Unable to resolve path $env:SystemDrive\TestAgent.

Do you have any idea why this could be happening?

It happens after the testagent is downloaded, then for some 10 minutes nothing happens and then the build fails:
2016-03-23T20:51:44.0401885Z DistributedTests: Starting to download testagent
2016-03-23T20:52:15.6457885Z DistributedTests: testagent is downloaded at: C:\..\Temp\78ca44ac-bf46-4c05-b140-3a011b037595
2016-03-23T21:01:18.3697885Z DistributedTests: files deleted from this location: C:\..\Temp\78ca44ac-bf46-4c05-b140-3a011b037595
2016-03-23T21:01:18.3697885Z ##[error]Unable to resolve path $env:SystemDrive\TestAgent.

**Comment by AshwiniChalla** [comment]
Please try with full name(along with domain name) of test agent if you havent already. Like machineName.domainName

**Comment by huserben** [comment]
I'm trying to access the VM only by its ip address, as it is not part of our domain (while the build server is)

**Comment by AshwiniChalla** [comment]
Are you able to ping the test agent from build agent machine with the ip address?

**Comment by huserben** [comment]
I have not tried pinging, but the copy file to machine task works, the files get copied to the specified folder on the vm

**Comment by AshwiniChalla** [comment]
What is the port you are using http or https?

**Comment by huserben** [comment]
I have not changed the default setting, where would I see this port?
But I assume its http

**Comment by AshwiniChalla** [comment]
You must have created a machine group in the test hub. Port will be just below the credentials fields when you create machine group.

**Comment by AshwiniChalla** [comment]
I hope you have PSRemoting enabled on test agent machine like mentioned [https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/README.md](url)

**Comment by huserben** [comment]
Yes I enabled PSRemoting

I see some ports in the machine group, but it is under "Tags":
[http://postimg.org/image/dy4kw5uxz/](url)

**Comment by AshwiniChalla** [comment]
Which TFS are you using? onprem or hosted?

**Comment by huserben** [comment]
It on prem

**Comment by AshwiniChalla** [comment]
version please. update 1 ?

**Comment by huserben** [comment]
Where can I see the version of TFS?
I'm not the admin of it.

But as far as I remember we did not yet install update 1

**Comment by huserben** [comment]
Yes it is Version 14.0.23128.0
which means it is "RTM"

**Comment by AshwiniChalla** [comment]
Can you quickly run following from your build agent.
Invoke-Command -ComputerName <ipaddress> -ScriptBlock { Get-ChildItem C:\ } -credential <username>

If it doesnt work execute following on test agent and retry .Meanwhile I will find an RTM setup to repro this.

>powershell -command "& Enable-PSRemoting -force"
> winrm quickconfig

**Comment by huserben** [comment]
So the first command gives me the output that unencrypted traffic is not supported on the client.
I guess that could be the overall problem?

I have to see if I can enable this on the build server and then try again

**Comment by huserben** [comment]
Sadly the admin of the build agent is not available this week, so I will follow this up next week and will let you know then if it solved the problem

Thanks for your help

**Comment by AshwiniChalla** [comment]
The powershell and the winrm commands I gave are to executed on test agent machine not build agent. If you access for test agent you can give it a try.

**Comment by huserben** [comment]
Yes, but the command on the build agent still failed with the same message

**Comment by AshwiniChalla** [comment]
You should add test agent ip address to trusted hosts on build agent.
Execute following powershell on build agent
>> set-item wsman:\localhost\Client\TrustedHosts -value <ipaddress> .

**Comment by huserben** [comment]
Hi

adding the test machine to the list of trusted hosts seems to have fixed the problem.
Thank you very much for your help
