### ISSUE TITLE
Windows Machine File Copy copies wrong files if correct mapping is missing

### ISSUE THREAD

**Issue by jesfer** [Microsoft/vso-agent-tasks#1434]
Using TFS2015 Update 1...

Using the step Windows Machine File Copy and specify $/some/path/in/tfvcrepo as source path but not having that specific path mapped in my build definition results in _all mapped paths being copied to target machine destination folder_!

Expected behaviour would be that the step fails due to incorrect  source path

**Comment by mvvsubbu** [comment]
I tried with latest VSTS task and it is working as expected.

There is a change in design of Windows file copy between update 1 and update 2., with the new design it should not be happening can you try with TFS 2015 Update 2 or VSTS account let us know the results.

**Comment by mvvsubbu** [comment]
Did you get a chance to try out?

**Comment by mvvsubbu** [comment]
Any update on this or can I assume it is working in latest and close the issue?

**Comment by mvvsubbu** [comment]
If you still face issue with latest version, feel free to re-open the issue
