### ISSUE TITLE
Bad minimum agent version on MSBuild, PublishSymbols and VSBuild tasks

### ISSUE THREAD

**Issue by arasium** [Microsoft/vso-agent-tasks#1438]
Hi,

in the latest version of MSBuild, PublishSymbols and VSBuild, the action handlers specified use node and/or powershell3. But the minimum agent version is the json file is 1.83.0. This is wrong since this agent doesn't have a powershell3 handler.

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vso-agent-tasks/pull/1457

**Comment by ericsciple** [comment]
fixed
