### ISSUE TITLE
Build several configurations, but need to have tests to be ran once

### ISSUE THREAD

**Issue by ghostinside** [Microsoft/vso-agent-tasks#1439]
Hello, 

i run builds for several configurations, but need to have tests to be ran once, not for each probably for particular one, can it possible?

**Comment by atinb** [comment]
Can you describe your scenario a little more? One way of doing this is described in #1353 
Thanks!

**Comment by ghostinside** [comment]
Thx a lot for the reference, it looks like exactly what i was looking for

Thx Alex
25 марта 2016 г. 18:46 пользователь "Atin Bansal" <notifications@github.com>
написал:

**Comment by atinb** [comment]
Great, thanks!
