### ISSUE TITLE
Xamarin iOS build fails after installing a brand new agent

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vso-agent-tasks#1448]
I just started experiencing an issue with the my xamarin ios builds so I decided to create a new agent on my mac. The XamariniOS build step fails with the following:
##[Error] 2016-03-28T17:30:53.815Z: Unhandled: Cannot find module './xcode-task-utils.js'

As far as I know I didn't change anything in the build that caused the failure. The build fails almost instantly when it reaches this step.

**Comment by madhurig** [comment]
Hi, sorry this is caused by a partial update to the task. To work around it please copy [this](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/Xcode/xcode-task-utils.js) file to the same folder as xamarinios.js on your build agent. We will fix the task.

Thanks,
Madhuri

**Comment by madhurig** [comment]
#1449

**Comment by rusty21** [comment]
Added the file to agent7/_work/tasks/XamariniOS/1.0.13/ which also contains xamarinios.js same error occurs.

**Comment by rusty21** [comment]
My apologies, this appears to have fixed the problem.

**Comment by madhurig** [comment]
@rusty21 : Thanks for reporting the issue and trying out the workaround, glad you are unblocked.
