### ISSUE TITLE
Infinite loop bug in "Windows Machine File Copy" and "Powershell on Target Machines"

### ISSUE THREAD

**Issue by jesfer** [Microsoft/vso-agent-tasks#1453]
The logic used in "Windows Machine File Copy" and "Powershell on Target Machines" to determine if all jobs are done can get stuck in an infinite loop. A stricter condition must be used (suggested solution further down in this issue).

**Background:**
One of  our on prem build agents suddenly failed to execute "Windows Machine File Copy" and "Powershell on Target Machines" build steps and gave this error as output:

> The command cannot remove the job with the job ID 15 because the job is not finished. To remove the job, first stop the job, or use the Force parameter.
Parameter name: Job

**Cause:**
For reasons still unknow (but we suspect canceled builds or bad PS scripts) there were multiple suspended [powershell jobs of type PSWorkflowJob](https://blogs.technet.microsoft.com/heyscriptingguy/2013/01/16/powershell-workflows-job-engine/) present in all PS sessions initiated by the build server account.
Apparently the build tasks imports the PSWorkflow module (or does the equivalent in a dll) which causes the Get-Job command to return more jobs than those created in the build task. The suspended PSWorkflowJobs cannot be removed and the `while(Get-Job)` statement turns into an infinite loop.

**Suggested solution:**
Replace this code (aprox. lines 196-207 and 372-399 in WindowsMachineFileCopy.ps1 and PowerShellOnTargetMachines.ps1 respectively)
```
While (Get-Job)
        {
            Start-Sleep 10 
            foreach($job in Get-Job)
            {
                if($job.State -ne "Running")
                {
                    Receive-Job -Id $job.Id
                    Remove-Job $Job                 
                } 
            }
        }

```

With something like this
```
While ($Jobs.Count > 0)
        {
            Start-Sleep 10 
            foreach($job in Get-Job)
            {
                if($Jobs.ContainsKey($job.Id) -and ($job.State -ne "Running"))
                {
                    Receive-Job -Id $job.Id
                    Remove-Job $Job
                    $Jobs.Remove($job.Id)                 
                } 
            }
        }
```
Stopping the extra jobs or using the -Force parameter like the error message suggests is probably a bad idea as there might be a valid reason for the existance of these jobs and to arbitrarily remove them is probably a bad idea.

**Comment by mvvsubbu** [comment]
Each instance of powershell based task creates new PS session. As the session is new and Get-Job returns only the jobs created in that session. Here there is a possibility that we may wait on a job that is not created by our task. I will take suggestion and floated a PR for that https://github.com/Microsoft/vso-agent-tasks/pull/1466

**Comment by mvvsubbu** [comment]
Fixed the code
