### ISSUE TITLE
File has not been uploaded to server

### ISSUE THREAD

**Issue by Liteolika** [Microsoft/vso-agent-tasks#1465]
When i run the publish artifacts on our on premesis TFS 2015 (14.95.25029.0), there are about 400 files with the status "File:<path> has not been uploaded to server.".
The folder "D:\TFSAgent\_work\21\a" on the server contains all files but they are not visible for the release management since they dont get published.

Logs attached.
[logs.zip](https://github.com/Microsoft/vso-agent-tasks/files/197185/logs.zip)

**Comment by TingluoHuang** [comment]
@Liteolika Can you check the folder you try to upload, is there any file with 0 file size?

**Comment by Liteolika** [comment]
@TingluoHuang yes there is. First i have an empty stylesheet but also numerous files named "_._" with 0 file size in the packages subfolders.

**Comment by Liteolika** [comment]
@TingluoHuang do you need anything more for troubleshooting this?

**Comment by ericsciple** [comment]
The 0 byte files are causing the issue.

**Comment by ericsciple** [comment]
The issue will be fixed in the CoreCLR agent (https://github.com/microsoft/vsts-agent), but is a limitation of the TFS 2015 Update 2 Windows agent.

**Comment by normanhh3** [comment]
Had this exact same issue just today.  Thanks for documenting the issue so I could get around it easily. :-)
