### ISSUE TITLE
Visual Studio TestDeploy Test Agent Fails

### ISSUE THREAD

**Issue by joselyncoe** [Microsoft/vso-agent-tasks#1475]
I receive the error: "TestAgent Configuration failed with exit code . Error code : -1"

Note: On my build definition I was able to perform a Visual Studio Build. 
But when I run the step "Visual Studio Test Agent Deployment" the build fails.

The configuration in TFS 2015 for this steps is:
-Iterativeprocess

**Configuration:**
**Server:**
-Team Foundation Server 2015 Update1
**Client (Test Machine)**
-Windows 7 Service Pack1
-Visual Studio Enterprise 2015
--Frameworks 4.5, 4.5.1, 4.6, 4.6.1
-Silk4NET (SilkTest) for Automated Test
-PowerShell Version 4 0 -1 -1 
--with PSRemoting enabled
-Build Agent downloaded from TFS 2015

Here Is The Log--------------------------------------------------------------------------------
[LogTestBuild.txt](https://github.com/Microsoft/vso-agent-tasks/files/200550/LogTestBuild.txt)

**Comment by acesiddhu** [comment]
Hi
Can you also share logs from test machine %temp%\TestAgentconfig.logs and c:\dtalogs

**Comment by acesiddhu** [comment]
Also can you confirm if Build agent is downloaded from tfs 2015 update 1 and not TFS 2015.

**Comment by joselyncoe** [comment]
Hi,

The build agent was downloaded from our TFS (see attached photo): 
 - Product Version 14.0.24712.0 (TFS2015.Update1)

Note: We dont have a configuration in TFS Console for LabManagement 


![tgs version and config](https://cloud.githubusercontent.com/assets/18222075/14226377/680de8d6-f8ae-11e5-9862-fddc8dc5440c.png)

**Comment by joselyncoe** [comment]
These are the logs:

[DTAExecutionHost.txt](https://github.com/Microsoft/vso-agent-tasks/files/200825/DTAExecutionHost.txt)
[TestAgentConfig.txt](https://github.com/Microsoft/vso-agent-tasks/files/200826/TestAgentConfig.txt)

**Comment by joselyncoe** [comment]
Another thing, the Test Machine has the Windows Firewall Service Stopped.

**Comment by nigurr** [comment]
Seems like issue with Windows Firewall service is not being run. Can you try turning on it?

Firewall exception could not be removed for application(s) 'Microsoft Visual Studio Test Agent Service'.
E, 2016/03/31, 19:49:54.521, System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

**Comment by joselyncoe** [comment]
Hi
  I enabled the Firewall Service. Now at some point the error is "_The job has been abandoned because the agent AgentTestMachine did not renew the lock. Ensure agent is running, not sleeping, and has not lost comunication with the service"

I try to execute the build definition in two ways:
-With a user logged in the test-machine
-Without user logged in the test machine


**Visual Studio Test Agent Deployment Result**
![build definition error](https://cloud.githubusercontent.com/assets/18222075/14266475/7a711310-fa96-11e5-9b0c-fbb7d0548b7d.PNG)

**-With a user logged in the test-machine (the following error appears)**
![execution error in testmachine](https://cloud.githubusercontent.com/assets/18222075/14266476/7a73e40a-fa96-11e5-9066-d708c2541c93.PNG)

**Updates TestAgentConfig log (firewall enabled)**
[TestAgentConfig.xt.txt](https://github.com/Microsoft/vso-agent-tasks/files/203492/TestAgentConfig.xt.txt)

**Comment by nigurr** [comment]
Can you please let us know the Test Agent OS Version?

For build agent error, just queue the build again. Seems like Build agent went offline or not picked up the tasks.

**Comment by joselyncoe** [comment]
Test agent machine with Windows 7 Professional Service Pack 1 (64 bit)

**Comment by nigurr** [comment]
Can you please re-post the DTA logs after enabling the firewall service? Please do clear any previous logs before running this.

**Comment by joselyncoe** [comment]
The DTA log is empty.

**Comment by nigurr** [comment]
Are there any error messages under Applications group in Events Log. You can view them in [Control Panel -> Event Viewer]

**Comment by joselyncoe** [comment]
Thanks for your support on this Gurram. 
Attached are the logs (previously cleared)

![tfs build details error](https://cloud.githubusercontent.com/assets/18222075/14298239/d6a505ae-fb51-11e5-838e-f721ef7c3cee.PNG)
Note: No DTA Log data was generated
[First EventLog Error.txt](https://github.com/Microsoft/vso-agent-tasks/files/205357/First.EventLog.Error.txt)
[Second Event Log Error.txt](https://github.com/Microsoft/vso-agent-tasks/files/205356/Second.Event.Log.Error.txt)
[TestAgentConfig.txt](https://github.com/Microsoft/vso-agent-tasks/files/205358/TestAgentConfig.txt)

**Comment by nigurr** [comment]
can you drop a mail to devops_tools at microsoft.com with your skype id
I will take it from there

**Comment by joselyncoe** [comment]
Nigurr

 My Skype is joselyncoe@gmail.com.
   I tried to send a mail but it was not delivered "The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists"

**Comment by joselyncoe** [comment]
I was able to run successfully the following build steps:
-Visual Studio Test Agent Deployment
-Visual Studio Test using Test Agent.

Here are the performed steps: 
-Begin with a clean Windows 7 machine
-Windows FIrewall Service needs to be enable
-No build Agent Installation
-Clean the %temp% directory
-Install TestAgent 2015 https://www.microsoft.com/en-us/download/details.aspx?id=48152
-Install Silk Test Open Agent (runtime only)
-Execute PowerShell Command Enable-PSRemoting –Force as administrator
-Make sure 5985 port is listening winrm e winrm/config/listener (PowerShell Command)

**Thanks Gurram for your support **
