### ISSUE TITLE
Variables based on other variables

### ISSUE THREAD

**Issue by enricforn** [Microsoft/vso-agent-tasks#1479]
I'd like to set variables values based on value of other variables. E.g.:

variable: environment.
value: "STAGING"

variable: targetpath
value: "C:\targetpath\$(environment)"

When accessing from tasks to "targetpath" variable, value should be:

value: "C:\targetpath\STAGING"

This helps to clone build defintions with similar parameters.

Right now this is not supported. Is possible to add this feature ?

**Comment by bryanmacfarlane** [comment]
The new agent which will preview soon supports this

https://github.com/Microsoft/vsts-agent 

It's not a tasks issue.

**Comment by enricforn** [comment]
We installed **[extension Variable Toolbox](https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks)**, and we can initialize dynamically variable for the current version of agent.
