### ISSUE TITLE
RunDistributedTests fails with UnExpected error

### ISSUE THREAD

**Issue by huserben** [Microsoft/vso-agent-tasks#1483]
Hi

I'm trying to run a distributed test on currently one virtual machine.
The tests I want to run are UI Tests that are created with TestStack.White and are declared as "normal" unit tests. Locally they run without a problem.

When I'm running them as part of the TFS build it fails with the following exception:
DistributedTests: Test run is aborted. Logging details of the run logs.
DistributedTests: New test run created.
Test Run queued for Project Build Service.
DistributedTests: Test discovery started.
DistributedTests: UnExpected error occured during test execution. Try again.
DistributedTests: Error : Some tests could not run because all test agents of this testrun were unreachable for long time. Ensure that all testagents are able to communicate with the server and retry again.
DistributedTests: Test run aborted. Test run id: 288
The test run was aborted, failing the task.

I cannot see why it fails and i did not find any meaningful log messages...

What is strange is that in the beginning it recognizes 6 tests (which is the amount i actually have):
DistributedTests: Test run '288' is in 'InProgress' state.
DistributedTests: Total Tests : 6, Passed Tests : 0

But after time they seem to increase:
DistributedTests: Total Tests : 12, Passed Tests : 0
...
DistributedTests: Test run '288' is in 'InProgress' state.
DistributedTests: Total Tests : 18, Passed Tests : 0
...
DistributedTests: Test run '288' is in 'Aborted' state.
DistributedTests: Total Tests : 24, Passed Tests : 0

After this, the task fails...

It would be nice if you could give me some assistance in finding the error

Regards and thanks for your help

**Comment by nigurr** [comment]
Can you please post the Build Log along with DTAExecutionHost log from the test agent machine. It will be under C:\Dta folder.

**Comment by huserben** [comment]
Hi
I have attached the DTAExecutionHostLog and the "distributed test" part of the build log.
Hope it helps, thanks for your help anyway.
[distributedTestBuildLog.txt](https://github.com/Microsoft/vso-agent-tasks/files/203875/distributedTestBuildLog.txt)
[DTAExecutionHost.exe .log.txt](https://github.com/Microsoft/vso-agent-tasks/files/203876/DTAExecutionHost.exe.log.txt)

**Comment by huserben** [comment]
Hi
I just saw that the DTAExecutionHost contains a lot of logs from all my build attempts. I created a fresh log with only one build log which might be easier to analyzer.
[DTAExecutionHost.exe.log.txt](https://github.com/Microsoft/vso-agent-tasks/files/203933/DTAExecutionHost.exe.log.txt)

**Comment by nigurr** [comment]
Sorry to ask again. Can you please do the fresh build and share the DTA log specific to this build [cleanup the log in Test Agent machine before queuing the build].

The logs in build and dta are pointing to different runs.

**Comment by huserben** [comment]
Hi
the second dta execution host is already a cleaned one.
Find here the build log for the same build attached.

Hope this helps
[7_Run Tests on Test Machines.txt](https://github.com/Microsoft/vso-agent-tasks/files/204627/7_Run.Tests.on.Test.Machines.txt)

**Comment by nigurr** [comment]
Hi,

From the error it looks like the Request Object is incompatible. 
Can you give this info?
* TFS Version
* Test Agent Version
* OS Version

**Comment by huserben** [comment]
Hi
the TFS Version is 14.0.23128.0 (TFS 2015 RTM)
The test agent is actually donwloaded from the web and installed as part of the Deploy TestAgent task.
See the attached image with a screenshot of the installed program.
This test agent runs on a Windows 7 SP1 machine.
![testagentversion](https://cloud.githubusercontent.com/assets/5486874/14310049/27ab42c2-fbe0-11e5-8f35-861da58961c4.PNG)

**Comment by huserben** [comment]
I now uninstalled this TestAgent and tried to let it be installed from the "DeployTestAgent" task again.
Now this task already fails with the following message:
Failed to update TFS Team Project Collection http://tfs:8080/tfs/xyz as the service account could not be granted required permission. To fix this error, run this tool with an account that has "Project Collection Administrator" rights and try again.

Which service account is meant here? The one that is running the build on the build agent? or something on the test machine?

**Comment by nigurr** [comment]
can you drop a mail to devops_tools at microsoft.com

**Comment by huserben** [comment]
Hi
I cannot drop you any mails there cause I'm not authorized for the group...

**Comment by nigurr** [comment]
Hi, Please do send a mail, we will receive it.
I am expecting that your Build Agent and Test Agent are different machines and not single machine.

**Comment by nigurr** [comment]
Ping

**Comment by huserben** [comment]
Hi
I'm sorry I was not available last week.
I did send 2 mails, but I guess you did not receive it?

Shall I try again?

**Comment by nigurr** [comment]
yes. please do send

**Comment by huserben** [comment]
Ok I sent a mail with the problem description + logs.

**Comment by huserben** [comment]
Hi
did you have any time to look into it?
I suspect that it is a problem with the access rights on TFS? Do you know what permissions the user I declare in "Agent Configuration" must have on the TFS?

**Comment by nigurr** [comment]
sent mail to you. please do respond. will close this issue once we identify the problem.

**Comment by Jerry06** [comment]
Can you update result of this issue ? I am having similar problem

**Comment by huserben** [comment]
It boiled down to the problem that we don't have TFS 2015 Update 2 installed yet. We want to run the tests on virtual machines which are not in our domain (where the TFS is) and apparently that does not work in versions before Update 2.

**Comment by nigurr** [comment]
Closing this thread. If there's any other problem, please do open new issue.

**Comment by sailajacharan** [comment]
@nigurr I am having similar issue, cld you plz share the solution. Thank you.
[DTAExecutionHostExeLog.txt](https://github.com/Microsoft/vsts-tasks/files/579092/DTAExecutionHostExeLog.txt)
![tfsversion](https://cloud.githubusercontent.com/assets/20461864/20112471/1c9a70de-a5b2-11e6-80ad-2b03dc666381.png)

**Comment by gusdewa** [comment]
Hi @nigurr , I am also having similar issue. Can I send you the logs?

**Comment by nigurr** [comment]
@gusdewa can you please send the logs to devops_tools at microsoft.com
Please include your VSTS build url along with it.

**Comment by gusdewa** [comment]
hi @nigurr , i have sent the email. However, turns out that the sender should be from the same organisation.

Please see [this screenshot](https://imgur.com/i8aDCIT):

**Comment by nigurr** [comment]
We did receive your mail.

From the logs:  

> ##vso[task.logissue type=warning]DistributedTests: Error : No tests were discovered from the specified test sources

Are you using any custom adapters for your Tests? if yes, did you copy them to Test machines?

**Comment by gusdewa** [comment]
Hi @nigurr, sorry for the late response. What do you mean by custom adapter? 
We use selenium C# wrapper with chrome, IE, and firefox driver. 

We run it one the Azure VM by deploying the standard test agent to run the provided test.dll.

**Comment by nigurr** [comment]
@gusdewa Can you please attach 

> DTAExecutionHost.log from C:\DTALogs (Test Agent machine)

W can quickly troubleshoot by logging to Test Agent machine and run the "vstest.console.exe with your test dlls" and see if they are running.

**Comment by gusdewa** [comment]
hi @nigurr , thanks. Just sent the file through email.

**Comment by prawalagarwal** [comment]
@gusdewa @nigurr We will have only one thread to discuss this issue: https://github.com/Microsoft/vsts-tasks/issues/4076.
