### ISSUE TITLE
IISWebDeploy cannot deploy to existing IIS Virtual Application

### ISSUE THREAD

**Issue by colindembovsky** [Microsoft/vso-agent-tasks#1493]
I don't think that this is possible - I have a web app that I want to deploy to "Default Web Sites/FabFiber" (an existing virtual application).

I add the webdeploy zip file and uncheck "Create or Update Website" since the virtual app exists. The task however fails saying that "website '' does not exist". I then tried to add the website name (leaving "Create or Update Website" unchecked) and the task gets further - but of course it's not a website, it's a virtual app.

Any way to deploy to a virtual app?

**Comment by mvvsubbu** [comment]
You need to check box Create or Update Website and enter only sitename for website field. In your case enter "Default Web Sites". And use override params to specify virtual app details  as below.

name="IIS Web Application Name",value="Default Web Sites/FabFiber"

**Comment by colindembovsky** [comment]
Thanks @mvvsubbu - I see. I did manage to get it to work, but it's really not a great UI experience.

I've got the `IIS Web Application Name` configured in my SetParameters.xml file, but it appears that the task essentially ignores this setting. I had to duplicate the setting in the override parameters. Then I had to further specify the Website name in the "Create or Update" website section, even though I didn't want to create or update the website.

![image](https://cloud.githubusercontent.com/assets/1932561/14321200/84a26c66-fc18-11e5-899b-5952b7093633.png)

The task should see if there is a `IIS Web Application Name` in the SetParameters file, and if so, extract the site name from there. Otherwise, the WebsiteName should be surfaced outside the "Website" group in the UI so that I can specify the name even without checking the checkbox.

**Comment by mvvsubbu** [comment]
If you have website already created and you want to simply deploy bits, you don't need to click that checkbox. If you provide either override params or setparam file it should allow you to deploy. Once of our recent fix broke this behaviour, I have floated a PR for fixing the regression along with another fix. You can refer line 621 https://github.com/Microsoft/vso-agent-tasks/pull/1502/files#diff-9aa5df19859239867441aca91c0ba062 . This PR once checked your concern will be addressed.

**Comment by mvvsubbu** [comment]
Fix committed it will be available in next deployment
