### ISSUE TITLE
Visual Studio Test task doesn't prefix $(Build.SourcesDirectory) like other tasks

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vso-agent-tasks#1510]
Whenever I use the VS Test task, I have to remember to prefix the "Test Assembly" or "Path to Custom Test Adapters" paths with `$(Build.SourcesDirectory)` because unlike so many other tasks, the VS Test task doesn't prefix the paths I specify  here with that macro. When I leave that macro off, it searches the `c:\windows\system32` folder for tests instead of my source directory's bin folder.

**Comment by nigurr** [comment]
Hi,

I tried testing this. By default its pointing to $(Build.SourcesDirectory).
Can you check again?

**Comment by AArnott** [comment]
My report isn't about what it defaults to. It's about what it prefixes when I change the default.
The default doesn't work because (for example) when the build definition builds both debug and release, searching from the default location leads to at least one of those configs to find the test assemblies (or custom test adapters) in the *other* config which is already built. So each config ends up executing all the tests 2X or 4X. So I must constrain the search to my `$(Build.SourcesDirectory)/bin/$(BuildConfiguration)` folder.

**Comment by nigurr** [comment]
I understood the point. Since it's open source you can take look at the code https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/VsTest/VSTest.ps1

even if you change the default value. You should end the "Test Assembly" field with "*", in such case it falls to Build Sources Directory.

Ex:
C:\BuildAgent\Sources\ - build source dir
if you want to execute tests under bin folder only
Test Assembly: \bin\**\*test.dll   -> search inside build source\bin recursively

**Comment by AArnott** [comment]
I already have a workaround to the issue I filed here: prefix all my paths with `$(Build.SourcesDirectory)`. I file this issue because I find it confusing and and in fact impossible to predict (as a user of VSTS) which Tasks will automatically prefix the `$(Build.SourcesDirectory)` to paths I specify and which ones will not. Since most tasks I use tend to prefix it, it's always trial and error to discover that a task doesn't, and that takes a while to figure out. 

This issue is my suggestion that this task adopt the pattern so many other tasks use: prefixing paths with `$(Build.SourcesDirectory)`

**Comment by bryanmacfarlane** [comment]
It's pretty simple.  A file path input (has ...) defaults to relative paths.  A relative path is relative to the root of the repo in build and root of artifact downloaded in RM.  build sources directory happens to point to the root of the repo.

Non file path inputs are just strings.  You have to format in what you want.  I would argue that anything that you would format sources directory into is a strong candidate for a filePath input (even if the browse only browses part of the path - can't browse build output folders yet).

**Comment by nigurr** [comment]
Closing the issue. if you are still having any queries, feel free to reopen this

**Comment by AArnott** [comment]
@nigurr What did you think of @bryanmacfarlane's suggestion? IMO it seems reasonable to fix this issue by changing the field type to `filePath` to fix this.
