### ISSUE TITLE
NuGet Publisher fails with 409 due to publishing symbols packages twice

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vso-agent-tasks#1511]
When using the NuGet Publisher task with a wildcard pattern of **\*.nupkg, the step inevitably fails when symbols packages are present. For example, if I have these packages:

```
bin\my.1.0.nupkg
bin\my.1.0.symbols.nupkg
```

This task will find both files and try to publish them both. But nuget.exe push will automatically push the symbols package when you push `bin\my.1.0.nupkg` so when this task then tries to push the symbols package itself, a 409 inevitably results.

I workaround this by using this search pattern instead of the default: `**\*.nupkg;-:**\*.symbols.nupkg` but it would be nice if the task was smart enough to suppress symbol packages from being uploaded twice.

**Comment by vtbassmatt** [comment]
Your workaround is the correct way to achieve what you want.

At some point, NuGet will probably [change how symbols packages work](https://github.com/NuGet/Home/issues/2122). Per their design that a package is uniquely identified by id + version, it's pretty broken that the client emits two packages with the same id + version but different contents.

**Comment by AArnott** [comment]
Shouldn't this workaround be the default value though? It seems broken that the vso task's default will always lead to failure in the presence of symbols packages. And if there are no symbols package, the new default value would not have any adverse effect.

**Comment by vtbassmatt** [comment]
Symbols packages aren't emitted by default. There's no harm in your PR, though, so I'll take it :) Thanks!

**Comment by AArnott** [comment]
In NuProj projects which produce nupkg, [symbols packages *are* emitted by default](https://github.com/nuproj/nuproj/blob/master/src/NuProj.Targets/NuProj.props#L15). So I'm hitting it a lot. Thanks for accepting.

**Comment by bkwdesign** [comment]
what am I doing wrong? 
I'm using a `dot net push` task step in my Azure CI pipe and am getting this 409 error.
I see this task is closed as if it's all good, but I don't think so.

```
Active code page: 65001

SYSTEMVSSCONNECTION exists true

SYSTEMVSSCONNECTION exists true

SYSTEMVSSCONNECTION exists true

"C:\Program Files\dotnet\dotnet.exe" nuget push D:\a\1\a\Ross.Manifest.PdfSplitter.OpenSource.1.0.0-CI-20201030-190639.nupkg --source https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v3/index.json --api-key VSTS

Pushing Ross.Manifest.PdfSplitter.OpenSource.1.0.0-CI-20201030-190639.nupkg to 'https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v2/'...

  PUT https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v2/

  Accepted https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v2/ 21430ms

Your package was pushed.

"C:\Program Files\dotnet\dotnet.exe" nuget push D:\a\1\a\Ross.Manifest.PdfSplitter.OpenSource.1.0.0-CI-20201030-190639.symbols.nupkg --source https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v3/index.json --api-key VSTS

Pushing Ross.Manifest.PdfSplitter.OpenSource.1.0.0-CI-20201030-190639.symbols.nupkg to 'https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v2/'...

  PUT https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v2/

  Conflict https://pkgs.dev.azure.com/RossEnvironmentalServices/_packaging/1631486d-2386-7339-ae02-4bbae3d4a949/nuget/v2/ 4221ms

To skip already published packages, use the option --skip-duplicate

error: Response status code does not indicate success: 409 (Conflict - The feed already contains 'Ross.Manifest.PdfSplitter.OpenSource 1.0.0-CI-20201030-190639'. (DevOps Activity ID: 7978D218-A115-4018-987E-A10F1E93E14C)).





Usage: dotnet nuget push [arguments] [options]



Arguments:

  [root]  Specify the path to the package and your API key to push the package to the server.



Options:

  -h|--help                      Show help information

  --force-english-output         Forces the application to run using an invariant, English-based culture.

  -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.

  -ss|--symbol-source <source>   Symbol server URL to use.

  -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).

  -k|--api-key <apiKey>          The API key for the server.

  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.

  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.

  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.

  --no-service-endpoint          Does not append "api/v2/package" to the source URL.

  --interactive                  Allow the command to block and require manual action for operations like authentication.

  --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.

##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1

##[error]Packages failed to publish

```

**Comment by XtremeOwnageDotCom** [comment]
> This is still an issue in 2024. Why has it been closed?

I feel your pain right now. Hitting exact same issue, and finding dozens of tickets from 2016/2017/2018/2019 for this issue....

All of which were closed/skipped, auto-closed, or closed without any actual solution, other then "don't include symbols"

**Comment by rainiersvn** [comment]
Microsoft is being a doos again 🗡️
