### ISSUE TITLE
Not setting Website Name in IISWebAppDeployment task always fails the task

### ISSUE THREAD

**Issue by jshepler** [Microsoft/vso-agent-tasks#1512]
Even if "Create or Update Website" is not checked, MsDeployOnTargetMachines.ps1 still uses the $WebSiteName to check for the existence of the website.

```
if($CreateWebSite -ieq "true")
{
    ...
}
else
{
    $doesWebSiteExists = Does-WebSiteExists -siteName $WebSiteName
    if (-not $doesWebSiteExists)  
    {
        throw "The website '$WebSiteName' does not exist and you did not request to create it - deployment cannot continue."  
    }
}
```

Even if passing the website name as an override ("IIS Web Application Name"), the above code will still fail the task.

I see three options:

1. Move the website name field out of the website group and into the general group, as a required field.

2. Remove the else block above.

3. Keep the else block above but parse the overrides for the "IIS Web Application Name" and set $WebSiteName to that value.

Personally, I like option 1. DeployIISWebApp.ps1 already has code to take $webSiteName and add it to $overRideParams so web deploy works. I like the checking if the website exists before attempting to deploy. Having a field that just takes the site name(/path) is much easier to use than the bulky override.

**Comment by mvvsubbu** [comment]
This is a regression to existing behaviour happened recently. I checked in a fix to master just yesterday you can upload that your account and continue.

**Comment by jshepler** [comment]
Removing the throw and changing the message is good enough, I guess. At least it gets to the deployment code and uses the override parameter to set the website name.

Thanks.
