### ISSUE TITLE
AzureFileCopy no longer sets output variables unless in Verbose mode

### ISSUE THREAD

**Issue by antmeehan** [Microsoft/vso-agent-tasks#1523]
As of https://github.com/Microsoft/vso-agent-tasks/commit/7929b0a685ff532c15fe6ef23ca03a92e38a814e the AzureFileCopy task no longer sets the output variables for outputStorageURI and outputStorageContainerSASToken, unless you turn on Verbose mode (setting `system.debug` variable to `true`).

The problem seems to be that the script is using `Write-Verbose` instead of `Write-Host` when emitting the variable setting command.

**Comment by KrishnaAdityaB** [comment]
@antmeehan Thanks for reporting. Thanks a lot for suggesting work around and fix.
We will take the fix in the next release.

**Comment by KrishnaAdityaB** [comment]
ETA for fix 5/6

**Comment by KrishnaAdityaB** [comment]
This is hotfixed today. Removing the 'bug' label.
