### ISSUE TITLE
Warn:Unable to run "git clean -fdx" and "git reset --hard HEAD" successfully, delete source folder instead.

### ISSUE THREAD

**Issue by chsword** [Microsoft/vso-agent-tasks#1540]
But I have installed the msysgit and set the %Path% include c:\Programe Files\Git\cmd

**Comment by ericsciple** [comment]
@chsword did you follow these instructions to use git.exe? https://msdn.microsoft.com/en-us/library/vs/alm/build/scripts/git-commands

I think it requires a 1.98 agent, so you may need to restart your agent process so it will update, or you can update a pool all at once from the agent pools admin web ui.

Also, I can't remember for sure, but I think `git.exe clean` may return a non-zero exit code if there is a long path to cleanup. It's been a while, so I can't remember for sure. That could be what's causing it.

**Comment by chsword** [comment]
I re run the ConfigureaAgent.cmd ,It works well.
