### ISSUE TITLE
Update SonarQube Scanner to the latest version

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vso-agent-tasks#1546]
With SonarQube Scanner for MSBuild v2.0 support for third-party Roslyn analyzers is added. It will be beneficial if the relate build task would use the latest available version of the runner. Are there any issues in using the latest version?

**Comment by bgavrilMS** [comment]
Hi Mario! The SonarQube scanner for MSBuild is embedded in the C# plugin not in the tasks. Make sure you are using the latest SonarQube C# plugin to get the latest features of the new scanner.

**Comment by mmajcica** [comment]
Hi @bgavrilMS,

sorry I messed up the terminology. SonarQube PreBuild build task ships with MSBuild.SonarQube.Runner.exe in version 1.1. Version 2.0 is available for some time now (http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild).
It would be nice to have it part of the build task as some important features are added to the scanner as support for third-party Roslyn analyzers (https://blogs.msdn.microsoft.com/visualstudioalm/2016/02/18/sonarqube-scanner-for-msbuild-v2-0-released-support-for-third-party-roslyn-analyzers/).

Thanks,
Mario

**Comment by bgavrilMS** [comment]
Hi again Mario. The tasks embed a single "bootstrapper" executable, not the whole sbuild scanner. The bootstrapper downloads the MSBuild scanner from SonarQube every time you perform an analysis. The  bootstrapper is also versioned but we haven't changed anything in it from 1.1. I agree this is confusing so I'll change the directory name.

You can confirm that you are using the latest msbuild scanner if you look in the build logs.

It's there a specific feature you aren't able to get working using the tasks?
