### ISSUE TITLE
Custom task based on a bash shell script hang

### ISSUE THREAD

**Issue by LiohAu** [Microsoft/vso-agent-tasks#1551]
I am trying to create a new task that handle versioning of iOS apps (I would like to publish it here later).
This task is really simple as it only uses a bash shell script (and basically I copy/pasted some parts of the CocoaPods one).

My issue is when I try to run a build with that task, the agent just seems to be hanging and the last output I get is this (until I cancel the build..) : 

> 
******************************************************************************
Running iOSVersioning
******************************************************************************
cwd: /Users/.../OSX-Agent/_work/2/s/App-iOS
majorVersion: 1
minorVersion: 1
revisionVersion: 1
>

Any idea of how I can debug what's happening here? I already use the "system.debug" parameter, and my .sh script begins with an dummy echo which is not being displayed (so it looks like the .sh script is not even being executed).

My task.json file contains this section (the filename is correct) : 

>
  "execution": {
    "Bash": {
     "target": "agvtool.sh",
     "argumentFormat": ""
    }
  }
>

**Comment by bryanmacfarlane** [comment]
Only node and powershell are supported as execution handlers.

See the lib repo for docs on writing a typescript/node/js task and refer to other examples in this repo like gulp, grunt, cmake as reference examples.

https://github.com/Microsoft/vsts-task-lib

Finally, it can't be in this repo, since this repo contains the in-the-box tasks in TFS/VSTS.  You should write your task as an extension.  The contribution docs in this repo cover that.

**Comment by LiohAu** [comment]
@bryanmacfarlane So the "Bash" section in this file https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/CocoaPods/task.json is not supported ?

**Comment by ericsciple** [comment]
I don't know why it has that (perhaps historical?). There is no such execution handler and AFAIK never has been.

**Comment by LiohAu** [comment]
Ok i'm going on a node.js one so.

**Comment by bryanmacfarlane** [comment]
Correct - it was left for compat with an old agent where we started.  I will delete that today :)
