### ISSUE TITLE
Provide NuGet Deploy

### ISSUE THREAD

**Issue by stas-sultanov** [Microsoft/vso-agent-tasks#229]
I would like to suggest to add a Deploy step that will pack and push build output to NuGet feed
Also it would be nice if there would be some sort of prebuild step that will replace version in *.cs files with value from the Build Number

**Comment by jbattermann** [comment]
+1

Ideally and optionally (on/off checkbox) packing and publishing of Symbol packages should be performed in the same task.

**Comment by lawrencegripper** [comment]
I'm looking for the similar behaviour, I'll try and put something together in a pull request over the next couple of weeks. 

Initially will look to take a Nuspec or sln, package to nupkg and publish to a nuget server.

@bryanmacfarlane contributor guide  doesn't mention creation of completely new Tasks, is this something your happy to accept? Is there anything I should do/not do?

**Comment by stas-sultanov** [comment]
@lawrencegripper it would be nice if this task will allow to avoid use of nuspec file at all.
it could be generated using metadata from assembly and adding some data from Task metadata

**Comment by lawrencegripper** [comment]
Got this working, you can either specify a nuspec file or package a csproj file, the task looks at the build  information and uses this to version the resulting package. 

Pull request is in, in the meantime you can clone the fork, use gulp to build the and the taskuploader to publish to your own VSO for testing. 

#381

**Comment by s093294** [comment]
Do you know a blog post or anything explaining how to build and upload a task? Just found this post and wanted to try do the same. I forked the project and created a new Task. Got all the tooling installed, but unsure what I need to do after creating my task. I have run the clean and compile tasks in the gulp file.

**Comment by bryanmacfarlane** [comment]
@s093294 
https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md

**Comment by s093294** [comment]
Thanks. @bryanmacfarlane 

Just found that also.  the generated file task.loc.json, I cant seem to figure out how to generate that. Since I copied one of the other tasks and just edited a few things like guids and want to test uploading that to my VSO. But the .loc.json file is not changed accordingly.

**Comment by bryanmacfarlane** [comment]
@s093294 let's get this conversation of this PR about the Nuget task. 

 But the short answer is you don't have to create a task.loc.json but you can if you want to localize that task in n langs.  Microsoft does that for our in the box tasks and we have a loc team that does it.  And our gulp build process in our repo creates it and extracts the strings.

**Comment by s093294** [comment]
Thanks @bryanmacfarlane Got everything working and my tasks into VSO.

**Comment by onovotny** [comment]
For versioning, can I suggest using GitVersion? It has a VSO build step now: https://github.com/GitTools/GitVersion/blob/master/docs/more-info/build-server-setup/tfs-build-vnext.md

The GitVersion build step will write variables that should be usable by other build steps/tasks, including a NuGet version variable.

**Comment by stas-sultanov** [comment]
@onovotny yeap, it would be nice.

**Comment by pascalberger** [comment]
@onovotny Why would you like to make a dependency between GitVersion and the NuGet Publish task? IMHO the solution provided in #381 is sufficient with the possibility to overwrite the version in the NuGet Package Task through additional arguments.

**Comment by onovotny** [comment]
Sorry, I didn't mean to imply a dependency between the two tasks Rather, I was suggesting that GitVersion could be used to obtain a version number parameter to counter the second half of the suggestion:
> Also it would be nice if there would be some sort of prebuild step that will replace version in *.cs files with value from the Build Number

**Comment by stas-sultanov** [comment]
I belive that GitVersion may be used for AssemblyVersion and NuGet Package version.

**Comment by SamJongenelen** [comment]
+1 on the task for assembly file version! 
The ms build targets make it possible to generate build numbers from a variable in your product file. Msbuild targets is on github too. 
It would be awesome to do this from a vso agent build step!

**Comment by pascalberger** [comment]
@SamJongenelen You can already use the GitVersion task to determine the version, update AssemblyInfos or pass this to the NuGet pack task. Or for a generic solutions see the task in #554

**Comment by SamJongenelen** [comment]
@pascalberger thanks! That's exactly what I meant

**Comment by vtbassmatt** [comment]
Closing this one since there are now NuGet Pack and NuGet Publish steps. Thanks!
