### ISSUE TITLE
Azure cloud service deployment template fails staging deployment when diagnostics is used

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vso-agent-tasks#254]
(Brought this issue over from the xplat agent repo)

**kaspernortoft** *commented an hour ago*
*The Azure cloud service deployment script fails the second deployment if the service uses the diagnostics extension and is swapped from staging to production.
ConflictError: The extension ID RoleName-PaaSDiagnostics-Staging-Ext-0 is already in use for this deployment.
It seems possible to use the Set-AzureServiceDiagnosticsExtension instead to set the diagnostics, but it is pretty slow*

Thanks for reporting this issue.  I'll investigate this.  If possible, could you set the "system.debug" variable to true on your definition (on the Variables tab), run that definition again, then send me downloaded logs?  The Azure PS cmdlets will write a lot of diagnostics information that I can go through and see exactly where it's failing.

**Comment by jeffyoung** [comment]
It looks like this issue was reported and fix very recently.

An initial report is at https://social.msdn.microsoft.com/Forums/en-US/5a37b1fc-86ec-4b26-be2e-75ab5360d20d/bug-with-diagnostics-extensions-in-azure-sdk-26-myrolepaasdiagnosticsstagingext0-is-already-in?forum=azureautomation.

A good explanation of the repro steps and the bug is at https://github.com/Azure/azure-powershell/pull/361 and the final pull request looks to have happened at https://github.com/Azure/azure-powershell/pull/466/files.

Once those changes get into an Azure PS cmdlet update, we can get them out on to the hosted pool.  Before then, if you've got your own Build agent, you can update to the version of the Azure PS cmdlets that have the fix (the Azure PS cmdlets changelog is at https://github.com/Azure/azure-powershell/blob/dev/ChangeLog.txt and it doesn't look like the change has been released yet).

**Comment by kaspernortoft** [comment]
I'm using azure-powershell 0.93 cmdlets. 
The New-AzureServiceDiagnosticsExtensionConfig ->  Set-AzureDeployment or New-AzureServiceDiagnosticsExtensionConfig -> Remove-AzureDeployment -> New-AzureDeployment fails.
If I use Set-AzureDeployment (without extensionConfiguration) -> Set-AzureServiceDiagnosticsExtension it seems to work.

**Comment by baywet** [comment]
Just for information we still have this issue with the August release of AzurePS (0.9.6).

**Comment by thechrisjohnson** [comment]
They have released AzurePS 0.9.7 which fixes the issue. The hosted agents should also have this fix.

**Comment by baywet** [comment]
just updated azure ps to 0.9.7 and still running into the issue. agent version is 1.86
