### ISSUE TITLE
Variable name mismatch in NuGet Restore task.

### ISSUE THREAD

**Issue by aarondandy** [Microsoft/vso-agent-tasks#264]
The arguments variable is defined as "nuGetRestoreArgs" in the NuGetInstaller task but as "nuGetArgs" in the ps1. I think this may be what is causing my arguments to be ignored in VSO.

**Comment by teves-castro** [comment]
Same here! I guess until this is fixed the only way to work around this issue would be to deploy our own agent and in it configure nuget globally the way we need.

**Comment by aarondandy** [comment]
We were able to work around by creating a template nuget config file. We then have a vso-1337-hax.ps1 where we replace our API key and replace a config in ./.nuget/nuget.config . NuGet looks here by default.

**Comment by aarondandy** [comment]
I moved this item to Connect so it can be addressed: https://connect.microsoft.com/VisualStudio/feedback/details/1488167

**Comment by bryanmacfarlane** [comment]
This is fixed and will be in the next VSO update

https://github.com/Microsoft/vso-agent-tasks/commit/aa3b5a672cb5862e568ef52449425d6e739a4705

**Comment by aarondandy** [comment]
Thanks for the update.
