### ISSUE TITLE
VSTest task is invoked with working dir prepended to the TestAssembly field

### ISSUE THREAD

**Issue by hallipr** [Microsoft/vso-agent-tasks#265]
Given the following input:
TestAssembly: \*\*\\\*.tests.dll;\*\*\\\*.specs.dll;-:\*\*\\obj\\\*\*;-:.\\tests\\FunctionalTests\*\*

I would expect it to run tests that end in tests.dll, or specs.dll, except for assemblies in obj folders, or assemblies in the relative .\\tests\\functionaltests folder

Instead, VSTest.ps1 is invoked with the following parameter
testAssembly=D:\\agents\\agent1\\_work\\871969cb\\super-project\\\*\*\\\*.tests.dll;\*\*\\\*.specs.dll;-:\*\*\\obj\\\*\*;-:.\\tests\\FunctionalTests\*\*

When the testAssembly parameter is split for file finding, we get this:

include D:\\agents\\agent1\\_work\\871969cb\\super-project\\\*\*\\\*.tests.dll
include \*\*\\\*.specs.dll
exclude \*\*\\obj\\\*\*
exclude .\\tests\\FunctionalTests\*\*

The PWD for the task is the parent directory for the VSTest.ps1 script, not the working directory.

The first include will work because the file finder starts at the non-wildcard portion of the string: D:\\agents\\agent1\\_work\\871969cb\\super-project  and finds all descendant files that match the pattern \*\*\\\*.tests.dll

The second include fails to find any tests because it's looking in the agent's tasks folder, no the working directory.

The first exclude works because it's a wildcard prefixed match.
I'm not sure if the second exclude would work, again because the root for path comparison isn't the working directory.

**Comment by atinb** [comment]
Update: with S87 deployment, we have made a few improvements in VSTest task, including how we handle multiple assemblies. Like you noted, when specifying multiple assemblies, only the 1st assembly used to be relative to the Sources Directory. All others were defaulting to Agent directory. This is fixed

Please give it a try and let us know if you have more feedback
 Thanks!
