### ISSUE TITLE
Upload custom agent tasks to VSO account

### ISSUE THREAD

**Issue by WaelHamze** [Microsoft/vso-agent-tasks#273]
Hi, any documentation on how to upload custom build agent tasks to my vso account so I can use them in my templates? Thanks

**Comment by bryanmacfarlane** [comment]
This is coming.  I've assigned this issue to me to track the work

**Comment by WaelHamze** [comment]
Perfect. Looking forward to this.

**Comment by mediafreakch** [comment]
@bryanmacfarlane Am I missing something or is the documentation for TFS on premise missing as well?

**Comment by WaelHamze** [comment]
Do you know when this is likely to come? Are we expecting a feature on the UI to upload tasks similar to the concept of plug-ins in Jenkins? Or is this a matter or using some tool or script that uses the TFS API to upload the tasks?

**Comment by chrisrpatterson** [comment]
We will have a tool soon and that is still a stop gap until we get the VSO/TFS extension gallery in place which will be the final solution.  This will give you an experience like you see in Jenkins where you can browse available extensions and install them into your account or server.

**Comment by pascalberger** [comment]
Is https://github.com/Microsoft/tfs-cli the current proposed solution to this?

**Comment by bryanmacfarlane** [comment]
Yes, but we're finishing it up.  upload worked for the first time yesterday - adding tracing, more error handling and finally docs.  Should be announced on Monday.

You can give it a spin but realizewe're finishing it up

just type `tfx` for help
`tfx build tasks` for available commands

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md
