### ISSUE TITLE
Support for publishing test results in the xUnit XML format...

### ISSUE THREAD

**Issue by dmccaffery** [Microsoft/vso-agent-tasks#302]
Currently, the publish test results to TFS/VSO task only supports publishing of the following formats:

* JUnit
* VSTest
* NUnit

Most of us playing around with DNX are using xUnit since they already support dnx with a task runner from the CLI, which makes xUnit support a fairly big deal.

**Comment by MiguelAlho** [comment]
+1. The fact that the asp.net team has been pushing xunit foward (any therefore pretty much any sample has xunit tests associated) justifies first class support for this.

**Comment by atinb** [comment]
My understanding is that the xunit result format is very similar to Junit. Have you tried using the result publisher task to see if it works?
Thanks
Atin.

Sent from my Windows Phone
________________________________

**Comment by MiguelAlho** [comment]
Still trying (hard) to get the tests to run in TFS (on-premise)....

**Comment by dmccaffery** [comment]
I can execute the tests without issue; it's just that TFS does not understand the xunit format and thus does not display the test results as part of the CI build.

I have tried all the formats available, including JUnit. None of them work (XML is uploaded, but isn't parsed).

See: https://github.com/xunit/dnx.xunit/issues/42 and https://github.com/dotnet/corefx/issues/2189.

If xunit were supported as a first-class citizen within TFS, the XML transforms would be unnecessary. Given Microsofts heavy usage of xunit within DNX itself, it really should be promoted to a first class citizen (imho).

**Comment by andremarques023** [comment]
In fact you can translate your .xml file to one of the acceptable formats (eg NUnit ) using any transformation tool. I have been using the msxsl.exe command line utility, it gets the job done.

You can put it on a powershell script and call it after run your dnx test command. Something like:

dnx $PSScriptRoot\test\MyTestProject test
.\msxsl.exe $PSScriptRoot\OldTestResults.xml .\NUnitFormat.xslt -o NewTestsResults.xml

And then use NewTestsResults.xml on the Publish Test Results build step. It works.

**Comment by atinb** [comment]
Thanks André. We are investigating supporting XUnit natively also
Atin.

**Comment by dmccaffery** [comment]
André:

You're assuming that I am building only on Windows, which I'm not. msxsl.exe is not cross platform -- I'm sure I could find some external tool to get the job done, but I'd rather put the feature request out there so it doesn't have to be a hassle. Microsoft supports NUnit in the OOBE; but XUnit is the test runner of choice for cross-platform development at the moment.

Regardless, without support for XSLT in .NET Core or first-class support for the native XUnit format in TFS/VSO, there is currently no good way to do this while supporting a cross-platform build system (not without a lot of specialized checks for different platforms, which kind of defeats the purpose).

Thanks for the info, though.

**Comment by dmccaffery** [comment]
I see that the publish test results task now includes XUnit in the drop down (yay!); however, all attempts to publish using the new option are failing with an error: Failed to publish test results: Unknown Test Runner.

![format option](https://cloud.githubusercontent.com/assets/1803684/10033591/450a8076-613f-11e5-8c18-7a8c1b3559e3.png)
![error](https://cloud.githubusercontent.com/assets/1803684/10033596/4af2a69e-613f-11e5-8097-ff25b2c74c2e.png)

**Comment by atinb** [comment]
We are in the middle of the Sprint 88 deployment. The build agent needs to be updated to S88, which I think should happen by Friday. Thanks!

**Comment by acesiddhu** [comment]
@dmccaffery can you update the build agent and give a try one more time. you will need 1.88 version of build agent for it to work.

**Comment by dmccaffery** [comment]
I am using the hosted agent in VSO, which is reporting as version 1.88, and I'm still seeing the issue.

![agent](https://cloud.githubusercontent.com/assets/1803684/10091088/a2938fe6-62eb-11e5-9e82-1146feccf7fc.png)

**Comment by Stavrakakis** [comment]
I'm seeing this issue too, so it would be really helpful to know if the in-built support will be available soon or if I should implement a transform to a supported format.

**Comment by dmccaffery** [comment]
@Stavrakakis Are you using the XUnit test runner for DNX like I am? I'm starting to wonder if this issue is being caused by a change in the XUnit format used for their next generation test runners.

**Comment by Stavrakakis** [comment]
@dmccaffery Yes I am.  We have some tests in older projects (non VNext) that use XUnit, and they are picked up by the Visual Studio Test task, so I'm just trying to see what's needed to get my DNX runner tests recognized.

**Comment by dmccaffery** [comment]
Here is a gist of an example xUnit test run from the DNX-based test runner:

https://gist.github.com/dmccaffery/dbc1cd0ed35c50deac1d#file-xunit-dnxcore-example-xml

And the project.json file:

https://gist.github.com/dmccaffery/dbc1cd0ed35c50deac1d#file-project-json

Hope this is helpful in some way.

**Comment by atinb** [comment]
Even though the hosted Build agent page says 88, the build agent on the hosted machines is still 87. This scenario should work as soon as 88 build agent is deployed and I will circle back when that happens (hopefully very soon)
Thanks!

**Comment by dmccaffery** [comment]
No worries. I'm not in any hurry -- DNX isn't go-live yet. I appreciate the effort!

**Comment by dmccaffery** [comment]
I did test against a locally deployed build agent on OSX and it works!

**Comment by Stavrakakis** [comment]
Thanks for the update! I'm just using msxsl to transform the results for the time being.

**Comment by atinb** [comment]
The functionality to upload xUnit results should work now with hosted agents. Appreciate the patience
Thanks!

**Comment by dmccaffery** [comment]
Confirmed. Works. :100: :+1:

**Comment by beufordy3k** [comment]
Is this included in an update to TFS 2015 on-prem yet?

**Comment by chrisrpatterson** [comment]
Will be in update 2

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Mon, Feb 1, 2016 at 7:14 AM -0800, "beufordy3k" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this included in an update to TFS 2015 on-prem yet?

-

**Comment by beufordy3k** [comment]
Excellent, thanks!
