### ISSUE TITLE
Support NuGet based test adapters in the VSTest task

### ISSUE THREAD

**Issue by kjbartel** [Microsoft/vso-agent-tasks#311]
With the old XAML build definitions tests could be run using test frameworks which used NuGet packages for distribution of their test adapter and test runner. This includes XUnit and NUnit, both which have moved away from using VSIX extensions.
With the new build definitions these frameworks no longer work. Instead you need to specify the path to the test adapter. Obviously this won't work unless the contents of the NuGet packages are in source control, and even if they are you wouldn't want to point to the dlls under the packages directory as the path will change whenever a new version is released.
Yes of course we could copy the required dlls to a different directory and point the build definition to this path but that defeats the whole purpose of using NuGet packages.

**Comment by atinb** [comment]
@ kjbartel

The nuget packages for NUnit or XUnit still work with the new build definitions. In the path to test adapter, you can use something like "$(Build.SourcesDirectory)\Packages and it should work. http://www.donovanbrown.com/post/2015/06/15/how-to-run-xunit-test-with-vnext-build has a good example with screenshots on getting this working. Thanks!

**Comment by kjbartel** [comment]
@atinb
I did eventually get it to work. However, the requirement for setting the path like that really is not very clear. There certainly isn't any indication that it will search all sub-directories of the path specified as it does. I also found that the path needs to have no spaces (including the repository name) or be specified with quotes (on the VSO build definition editor page). Again not at all clear.
What I'm wondering is is why doesn't it work the same way as Visual Studio? The test adapter dll will be right next to the test dll in the same folder but this task doesn't find it. May I suggest that when you a test dll path that you check for a test adapter in the same folder? Then NuGet based test adapters will work out of the box without having to go to a blog post on a completely different website to work out what needs to be done.
The fact it doesn't work as expected means that it is still an issue. Most people would expect this to work and it doesn't.

**Comment by atinb** [comment]
Hi Kuan,

I completely agree and we are looking at making this experience simpler and more intuitive.
I am not sure if I agree that the Nuget based adapters will work automatically if we search in the test dll path. People have different ways of storing test dlls, and the nugets are downloaded to the packages folder.

Thanks
Atin.

**Comment by atinb** [comment]
Update: with S87 deployment, we have made a few improvements in VSTest task, including how custom adapters are loaded. 
-	If there is a packages folder in the sources directory, it is automatically searched for testadapters. Hence, any testadapter downloaded as a Nuget package will automatically be used
-	Handle common error cases like specifying the full path to the dll. 
-	When specifying multiple assemblies, only the 1st assembly used to be relative to the Sources Directory. All others were defaulting to Agent directory. This is fixed
-	Paths in the task do not need to be enclosed in quotes

Please give it a try and let us know if you have more feedback
Thanks!

**Comment by kjbartel** [comment]
@atinb 
Sorry wasn't able to get back to you sooner.

I've updated my build definition to not specify the path to custom adapters, however the nuget test adapters weren't found as I have my projects under a `src` directory. Hence the path to the `packages` directory is `$(Build.SourcesDirectory)\src\Packages` not `$(Build.SourcesDirectory)\Packages`. I think this a a fairly common directory layout. I can confirm that the path no longer needs quotes added though.

**Comment by atinb** [comment]
@kjbartel 
It seems we had a bug on our side. If you try without specifying the a path now for the custom adapters, it will work. The path to the packages folder under src should not matter.
Thanks!

**Comment by kjbartel** [comment]
@atinb
All working now with the src\packages path. Thanks.
