### ISSUE TITLE
Can't split gulp tasks in diferents gulpfiles

### ISSUE THREAD

**Issue by AbraaoAlves** [Microsoft/vso-agent-tasks#350]
Hello,
I config my linux machine as build agent to VSO_Build and run very well. 
But when I split my gulp tasks in diferents files, VSO not found the tasks out of gulpfile.
Eg:
```
gulpfile.js
tasks/
├── dev.js
├── release.js
└── test.js
```

`gulpfile.js` file:
```js
var requireDir = require('require-dir');
var tasks = requireDir('./tasks');
```

And `./tasks/dev.js` file
```js
var gulp = require('gulp');
gulp.task('bower:install', function(){ .... });
```

Whe run task `gulp bower:install`, I see this log:
![My Build Log](http://s4.postimg.org/efl2lmb59/BUILD.png)

Anyone else had this same problem?

**Comment by chrisrpatterson** [comment]
Can you provide an example?  It is not clear what issue you are hitting.

**Comment by bryanmacfarlane** [comment]
On a devbox, what happens when you clone your repo to a separate clean folder, run npm install in the root and then run gulp in the root?

**Comment by bryanmacfarlane** [comment]
asked questions - no answer.  closing

**Comment by bryanmacfarlane** [comment]
no a CI issue - boils down to working with gulp
