### ISSUE TITLE
Document PowerShell Modules

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#352]
It would be helpful if you can provide documentation of the functions provided by the Microsoft.TeamFoundation.DistributedTask.Task.Internal and Microsoft.TeamFoundation.DistributedTask.Task.Common PowerShell modules

**Comment by jessehouwing** [comment]
I'd love it if we could use (at least some) of these modules in our own scripts. Especially the Find-Files task which would help porting existing MsBuild scripts to powershell.

**Comment by chrisrpatterson** [comment]
You should be able to use them in your own tasks, however, as the modules are currently written they have too many dependencies to be loaded outside of the agent.

**Comment by jessehouwing** [comment]
But I can't seem to use them in my own powershell script, as that uses the powershellexe host. It would be *very* useful if we could use (at least some) of the functions in those type of scripts.

It would also make it a lot easier to test the task.ps1 scripts stand-alone to make them work as expected. Right now creating and debugging tasks by triggering builds is far from ideal.

**Comment by bryanmacfarlane** [comment]
Agreed!  And that's why we're starting an effort to be able to run, test and debug tasks even outside the agent.  We've made good progress on the xplat side and we're about to start a new powershell handler in the agent that offers the equivalent on PS side

Here's how we do it on the JS side - coming soon to PS
https://www.youtube.com/watch?v=Ta2c3sUbJ18

**Comment by chrisrpatterson** [comment]
Yes we know that is an issue and it is something we are working on fixing, I don’t have an ETA yet but there are some other task model things we are working on for the fall.

**Comment by jessehouwing** [comment]
Great news!

**Comment by DaveSullivanAtWork** [comment]
Just watched the video, can't wait for it to be available for PS development too.

**Comment by bryanmacfarlane** [comment]
closing as we're tracking this work on our backlog

**Comment by peder** [comment]
@bryanmacfarlane: this item was closed since it was tracked on your backlog, but was there ever an update to this? Any blog post or wiki article we could use as a technical reference?

**Comment by ericsciple** [comment]
The PowerShell task execution handler still works for back-compat, but has been superceded by the "PowerShell3" task execution handler. The source and docs are [here](https://github.com/Microsoft/vsts-task-lib).
