### ISSUE TITLE
Sign and Align Android

### ISSUE THREAD

**Issue by ShaneCarr** [Microsoft/vso-agent-tasks#354]
Hello I am hoping someone here can help me with a problem. I am trying to use the sign and align plug in in vso. I can't seem to find a value that works for Keystore file location. I always get an error indicating that it can't find the file. I checked the file in my case in a number of places under app/java etc. Is there any example of what to pass for that value in terms of environment variables etc? I know the key file is good because i can use it and sign just great in android studio.

**Comment by chrisrpatterson** [comment]
$(Build.SourcesDirectory) will point at the location we synced your sources to on disk.  So in your case it seems the path might be $(Build.SourcesDirectory/app/java/<keyfilename>
