### ISSUE TITLE
Azure Powershell causes invalid attribute character error

### ISSUE THREAD

**Issue by kowsheek** [Microsoft/vso-agent-tasks#358]
Based on the document [here](https://msdn.microsoft.com/Library/vs/alm/Build/azure/deploy-aspnet5), I get this error on VSO while trying a build & publish:

`'<', hexadecimal value 0x3C, is an invalid attribute character. Line 10, position 42.`

 The Powershell script for prebuilding works and builds the target project correctly but adding the Azure Powershell script causes this issue.

I've been able to reproduce this with a new build definition as well. Any ideas on how this can be tackled?

Thanks!

**Comment by chrisrpatterson** [comment]
in that handler we don't run powershell.exe we use our own host which is built against PowerShell 4.  Do you have a script that repros this issue you could give me?

**Comment by kowsheek** [comment]
I'm using the script from the docs:

    param($websiteName, $packOutput)

    $website = Get-AzureWebsite -Name $websiteName

    # get the scm url to use with MSDeploy.  By default this will be the second in the array
    $msdeployurl = $website.EnabledHostNames[1]


    $publishProperties = @{'WebPublishMethod'='MSDeploy';
                            'MSDeployServiceUrl'=$msdeployurl;
                            'DeployIisAppPath'=$website.Name;
                            'Username'=$website.PublishingUsername;
                            'Password'=$website.PublishingPassword}


    $publishScript = "${env:ProgramFiles(x86)}\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\Publish\Scripts\default-publish.ps1"


    . $publishScript -publishProperties $publishProperties  -packOutput $packOutput

**Comment by chrisrpatterson** [comment]
I am not able to repro that, is there anymore context around the error?

**Comment by kowsheek** [comment]
What would help you further?

The build passes for every time I've tried, whenever I add `Azure PowerShell` as one of the steps and specify `publish.ps1` (which contains the above script) as the target script and `-websiteName dev-yakshaving -packOutput $(Build.SourcesDirectory)\YakShaving\artifacts\bin\$(BuildConfiguration)\Publish` as the argument, the build fails with `'<', hexadecimal value 0x3C, is an invalid attribute character. Line 10, position 42.`

The other steps in the build are:
![steps](https://cloud.githubusercontent.com/assets/164881/9000479/b1ed317e-3715-11e5-9876-c987f6d1fe15.png)

Happy to provide any further information.

**Comment by chrisrpatterson** [comment]
can you download the logs and email them to me at chrispat at Microsoft dot com?

**Comment by kowsheek** [comment]
When I download the logs, it only has empty Build folder. Is there anywhere else I could send you diagnostic information from? I am happy to share information about the account via email.

Thanks.

**Comment by kowsheek** [comment]
Hey @chrisrpatterson, any pointers on how to tackle this issue?

**Comment by chrisrpatterson** [comment]
@kowsheek sorry, I was not able to repro and have been swamped.  I will try to take a look again later today.

**Comment by kowsheek** [comment]
No worries @chrisrpatterson. Do let me know if there's anything I can help with. Thank you!

**Comment by kowsheek** [comment]
This issue seems to have been fixed. Thanks!

**Comment by chrisrpatterson** [comment]
Yep it is, we put out an update to the build VMs.  Sorry I didn't get back to you.
