### ISSUE TITLE
NuGetInstaller task is a little restrictive.

### ISSUE THREAD

**Issue by DaveSullivanAtWork** [Microsoft/vso-agent-tasks#367]
Hi,

Currently the task checks for a packages.config within the sub-tree that the solution file is in.
This does not account for solutions that reference projects outside of their own sub-tree.

I suggest removing all the logic from within the solution file loop and just invoking nuget on each solution found.

I could create a pull request if that is preferable, but I'm completely new to github.

Thanks
Dave

**Comment by chrisrpatterson** [comment]
That is a good suggestion.  Should be easy enough to fix.

**Comment by ljani** [comment]
I encountered the same restriction. The same patch should be applied not only to [`NuGetInstaller`](https://github.com/Microsoft/vso-agent-tasks/blob/b865a2087a65da15f8b3f7f7bd533bcfcf534a0e/Tasks/NuGetInstaller/NuGetInstaller.ps1#L80-L92), but also to [`MSBuild`](https://github.com/Microsoft/vso-agent-tasks/blob/b865a2087a65da15f8b3f7f7bd533bcfcf534a0e/Tasks/MSBuild/MSBuild.ps1#L145-L157) and [`VSBuild`](https://github.com/Microsoft/vso-agent-tasks/blob/b865a2087a65da15f8b3f7f7bd533bcfcf534a0e/Tasks/VSBuild/VSBuild.ps1#L189-L201).

**Comment by ericsciple** [comment]
fixed
