### ISSUE TITLE
Please introduce $(Build.BinariesDirectory) for migration purposes

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vso-agent-tasks#369]
I understand this is something we might be trying to move away from, but in order to upgrade old XAML builds to the new engine and to even old style TFS2008 builds which depend on redirectinr the Project output, it would be nice if there were a $(Build.BinariesDirectory) which we can substitute.

Right now I’m depending on $(Agent.BuildDirectory)\Binaries and $(AGENT_BUILDDIRECTORY)\Binaries to set these values and then pass them to MsBuild. That way the old packaging scripts, Wix scripts and other things that expect to find a temporary folder in a certain format all “just work”.

I don’t want to use the $(Build.StagingDirectory) for that, as that gets cleared after each build and breaks incremental builds.

I tried defining my own variable $(Build.BinariesDirectory) = $(Agent.BuildDirectory)\Binaries, but it looks like we can’t (yet) create “self-expanding” variables.

**Comment by bryanmacfarlane** [comment]
We'll discuss.  Thanks

**Comment by bryanmacfarlane** [comment]
This has been checked in.  You should see it in the next sprints rollout in a week or two.

See: https://github.com/Microsoft/vso-agent/blob/master/docs/workfolder.md
