### ISSUE TITLE
Support for recursively expanding variables

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vso-agent-tasks#370]
I tried defining my own variable $(Build.BinariesDirectory) = $(Agent.BuildDirectory)\Binaries, but it looks like we can’t (yet) create “self-expanding” variables.

Build just substitutes the literal "$(Agent.BuildDirectory)\Binaries" when calling tasks.

**Comment by bryanmacfarlane** [comment]
Yes, we don't support self expanding variables.  We don't have it in our near term backlog

**Comment by jessehouwing** [comment]
I implemented this myself using a very simple build task:

https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks
