### ISSUE TITLE
Logging command for setting the version of the build

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#380]
It would be useful to have a logging command available for settings the version of the build. Use case is that I want to determine the version of the build in a task and show this version also in TFS.

**Comment by pascalberger** [comment]
I tried to pass the determined version as a variable to TFS:

`##vso[task.setvariable variable=SemVer;]1.1.0-unstable.2`

And use `$(SemVer)` as Build number format. But this results in a build called $(SemVer)

**Comment by bryanmacfarlane** [comment]
Yes, this is in our plans.  Not supported yet.

**Comment by chrisrpatterson** [comment]
Even when we have a command to update the build number using variables you create on the agent in the build number format likely will not be possible.  The server expands the build number when the build is queued and that variable will not exist yet.

**Comment by pascalberger** [comment]
I think it is quite a common use case to determine the version based on the code or repository and not from the build system, and therefore would expect a build system to be able to adopt the build version accordingly.

Why not use a temporary build number while running the build and define the final build number after the build finishes?

**Comment by onovotny** [comment]
Maybe it's worthwhile to distinguish between TFS's internal build number, which understandably cannot be changed by a build agent/task and a "user/display" build number/name.

I don't expect to change TFS's calculated build id, but we do need something that can be used as a variable in the display name for the build. In terms of behavior, if that variable is not yet defined, then I'd expect it to be blank, just like any other MSBuild variable. When a task updates/sets that variable, the display name of the build should change though -- re-evaluate based on the current variable content.

**Comment by pascalberger** [comment]
It seems like there is already an internal build number (which you see for example in the file name if you download the logs as ZIP, which contains an incrementing number). This number already cannot be defined. 
The problem is that the user displayed build number at the moment also is expanded at the beginning of the build, which in my opinion should be done at the end. I won't have a problem also if until then the UI shows only the internal build number.

**Comment by bryanmacfarlane** [comment]
When we add the feature to be able to set the build name through a cmd, it will be the user/display build number - not the internal id.  That would allow you to overwrite it.  The server will still set a default one.

**Comment by onovotny** [comment]
That's great! Is there any rough idea when this will be ready? 

Also, would setting the build name be instead of the variables currently available for that go into BuildNumber or would there be a way to combine evaluation of the two? 

I'd prefer to have both, so that I could use a set of variables to include a branch name, build defn name, etc, as I do today, but then also include a variable that gets set later with the specific version. I don't want the task that sets the version to also dictate the rest of the displayed build name -- just part of it that I'll use via a variable.

**Comment by JakeGinnivan** [comment]
```
******************************************************************************
Starting: Get sources
******************************************************************************
Syncing repository: GitVersionTest (Git)
Checking out 3a758fbe17c12b7c01a3d271e78d04d4fd29d180 to C:\a\c129b6ca\GitVersionTest
Checked out branch refs/pull/2/merge for repository GitVersionTest at commit 3a758fbe17c12b7c01a3d271e78d04d4fd29d180
******************************************************************************
Running tasks
******************************************************************************
******************************************************************************
Starting task: GitVersion for
******************************************************************************
Executing the following commandline. (workingFolder = C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\tasks\GitVersion\3.0.11)
C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\tasks\GitVersion\3.0.11\GitVersion.exe C:\a\c129b6ca\GitVersionTest /output buildserver /updateAssemblyInfo false /nofetch 
Error message highlight pattern: 
Warning message highlight pattern: 
INFO [08/15/15 7:53:22:32] Working directory: C:\a\c129b6ca\GitVersionTest
INFO [08/15/15 7:53:22:34] Applicable build agent found: 'VsoAgent'.
INFO [08/15/15 7:53:22:34] Branch from build environment: refs/pull/2/merge
INFO [08/15/15 7:53:22:38] One remote found (origin -> 'https://ginnivan.visualstudio.com/DefaultCollection/_git/GitVersionTest').
INFO [08/15/15 7:53:22:38] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
INFO [08/15/15 7:53:22:39] Creating local branch refs/heads/pull/2/merge from ref refs/pull/2/merge
INFO [08/15/15 7:53:22:46] Creating local branch from remote tracking 'refs/remotes/origin/feature/foo'.
INFO [08/15/15 7:53:22:48] Skipping local branch creation since it already exists 'refs/remotes/origin/master'.
INFO [08/15/15 7:53:22:49] Creating local branch from remote tracking 'refs/remotes/origin/release/2.0.0'.
INFO [08/15/15 7:53:22:49] HEAD is detached and points at commit '3a758fbe17c12b7c01a3d271e78d04d4fd29d180'.
INFO [08/15/15 7:53:22:49] Local Refs:
refs/heads/feature/foo
refs/heads/master
refs/heads/pull/2/merge
refs/heads/release/2.0.0
refs/remotes/origin/feature/foo
refs/remotes/origin/master
refs/remotes/origin/release/2.0.0
refs/tags/1.0.0
INFO [08/15/15 7:53:22:51] Checking out local branch 'refs/pull/2/merge'.
INFO [08/15/15 7:53:22:53] Project root is: C:\a\c129b6ca\GitVersionTest
INFO [08/15/15 7:53:22:54] Using latest commit on specified branch
INFO [08/15/15 7:53:22:55] Begin: Attempting to inherit branch configuration from parent branch
  INFO [08/15/15 7:53:22:56] Begin: Finding branch source
  INFO [08/15/15 7:53:22:58] End: Finding branch source (Took: 26.00ms)
  INFO [08/15/15 7:53:22:59] Found possible parent branches: release/2.0.0
INFO [08/15/15 7:53:22:59] End: Attempting to inherit branch configuration from parent branch (Took: 41.00ms)
INFO [08/15/15 7:53:22:60] Running against branch: pull/2/merge (3a758fbe17c12b7c01a3d271e78d04d4fd29d180)
INFO [08/15/15 7:53:22:61] Begin: Calculating base versions
  INFO [08/15/15 7:53:22:63] Fallback base version: 0.1.0 with commit count source 148ba03b2c80a79ea09e839d9c5610bcec12855e
  INFO [08/15/15 7:53:22:67] Git tag '1.0.0': 1.0.0 with commit count source 278db3a1e84f5bb47dfa379c3f027b65719deab7
  INFO [08/15/15 7:53:22:67] Git tag '1.0.0': 1.0.0 with commit count source 278db3a1e84f5bb47dfa379c3f027b65719deab7
  INFO [08/15/15 7:53:22:69] Found multiple base versions which will produce the same SemVer (1.0.1), taking oldest source for commit counting (Git tag '1.0.0')
  INFO [08/15/15 7:53:22:69] Base version used: Git tag '1.0.0': 1.0.0 with commit count source 278db3a1e84f5bb47dfa379c3f027b65719deab7
INFO [08/15/15 7:53:22:69] End: Calculating base versions (Took: 78.00ms)
INFO [08/15/15 7:53:22:70] 10 commits found between 278db3a1e84f5bb47dfa379c3f027b65719deab7 and 3a758fbe17c12b7c01a3d271e78d04d4fd29d180
INFO [08/15/15 7:53:22:70] Applicable build agent found: 'VsoAgent'.
Executing GenerateSetVersionMessage for 'VsoAgent'.
Executing GenerateBuildLogOutput for 'VsoAgent'.
******************************************************************************
Finishing task: GitVersion
******************************************************************************
******************************************************************************
Starting task: Run cmd
******************************************************************************
Filename doesn't indicate a full path to a executable file.
Executing the following commandline. (workingFolder = C:\a\c129b6ca\GitVersionTest)
cmd /c echo semver: %gitversion_semver% 
Error message highlight pattern: 
Warning message highlight pattern: 
semver: 1.0.1-PullRequest.2 
******************************************************************************
Finishing task: CmdLine
******************************************************************************
******************************************************************************
Finishing Build
******************************************************************************
```

Boom.

**Comment by JakeGinnivan** [comment]
I ended up going down a similar road to what you were suggesting @onovotny. I added `string GetCurrentBranch();` to `IBuildServer` which pulls the branch from the env variable. I am going to sort out the other build servers and investigate if I can reduce the scope of then dynamic repositories need to be used.

**Comment by pascalberger** [comment]
But this hasn't anything to do with this specific issue? This issue is about the capability to set the build version of a TFS vNext build which needs to be fixed inside the TFS build agent. I think your findings belong to GitTools/GitVersion#562?

**Comment by JakeGinnivan** [comment]
Oops, yeah. Wrong tab. Will delete that.

Sent from my Windows Phone
________________________________

**Comment by pascalberger** [comment]
It seems like this is implemented now: https://github.com/Microsoft/vso-agent-tasks/commit/815986b0f28ae56a522943127c3a18c016e0666b.

With which agent version will it be released? Since it is not in one of the release branches yet will it be m90?

**Comment by JakeGinnivan** [comment]
According to a mailing list im on, it all works fine already!

![img](https://cloud.githubusercontent.com/assets/453152/10275841/51b20d2e-6b7d-11e5-8034-142a072e508d.png)

**Comment by pascalberger** [comment]
It doesn't work on my tenants yet (which are on ring2). On my tentant I receive the following message:

`##[warning]Unable to process logging event:##vso[build.updatebuildnumber]1.4.0-unstable.135`

It would be helpful if on the documentation is the agent version mentioned from which on a certain command is supported, so that custom tasks can which use a message can set the minimumAgentVersion accordingly.

@bryanmacfarlane, @chrisrpatterson Can you help here?

**Comment by onovotny** [comment]
Definitely want variables in this. In my "build number" for VSO, I want to include the branch name as I use a single build definition for multiple branches. Even better is if there's a way to just a way to put a placeholder in the VSO build format string and have this build task read/insert the SemVer into that.

**Comment by pascalberger** [comment]
Any info how to get the updatebuildnumber command working? 

@TingluoHuang?

**Comment by chrisrpatterson** [comment]
You need the 1.88 agent.

**Comment by pascalberger** [comment]
Thanks @chrisrpatterson. I added #635 for documenting this properly.

**Comment by pascalberger** [comment]
This was implemented with https://github.com/Microsoft/vso-agent-tasks/commit/815986b0f28ae56a522943127c3a18c016e0666b and deployed with m88

**Comment by pascalberger** [comment]
@onovotny You can use variables when calling updatebuildnumber from a script. It should be also easy to write a custom wrapper task, which accepts build number format / or variables and calls updatebuildnumber accordingly

**Comment by MylesArkell** [comment]
@chrisrpatterson I have found that when I use the ##vso[build.updatebuildnumber] it does update the version number but the build rev number does not update at the end of the build. this causes me problems as I use this rev number in the prerelease info of my version number eg 1.0.0-meta2016010105
ie meta date + rev

How can I update the build number and ensure that the build rev number is updated at the end of the build?
