### ISSUE TITLE
npm install fail:"A parameter cannot be found that matches parameter name 'WarningPattern'"

### ISSUE THREAD

**Issue by vegar** [Microsoft/vso-agent-tasks#383]
My npm install-tasks have started to fail with the following message:

> 2015-08-07T19:49:13.1703608Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\tasks\NpmInstall\0.1.3\NpmInstall.ps1
> 2015-08-07T19:49:15.3210712Z ##[error]A parameter cannot be found that matches parameter name 'WarningPattern'.

I'm using the hosted build agent.

Previous builds, using the 0.1.2 version of the `NpmInstall` task does not have this problem.

My guess would be that the `Invoke-Task` powershell cmdlet is fetched from an outdated ps module? 
Will this error stop appearing after some time when changes are propagated ?

**Comment by chrisrpatterson** [comment]
I apologize for that.  We are currently rolling out a VSO update and the build machines have not yet updated to the latest version of the agent.  They will be updating soon.

Thank you for your patience.

**Comment by vegar** [comment]
Guess I wasn't patience enough ;-)
Thanks for feedback. The new build stuff is really great!

**Comment by sonalipat** [comment]
Hi Team,

Can I execute coded ui automated testcase on azure virtual machine using ‘visual Studio Test Using Test Agent’ in VSO Releases* hub???
