### ISSUE TITLE
IIS Web Application Deployment not available in VSO

### ISSUE THREAD

**Issue by wertzui** [Microsoft/vso-agent-tasks#387]
The "IIS Web Application Deployment" task is not available in Visual Studio Online although the Readme states, that all tasks found in this repo are available in VSO.

**Comment by bryanmacfarlane** [comment]
Code gets checked into master, then goes to a release branch, then it will go in the next sprints deployment.

That means the task will show up in VSO, but of course checking the code in doesn't mean it's live yet

**Comment by cwoolum** [comment]
Can you guys tag when you release? That way people can see what has made it to the current release?

**Comment by chrisrpatterson** [comment]
We branch for release under the releases namespace.

You will also notice some tasks are have a visibility of Preview which hides them from accounts that don’t have the preview tasks feature enabled.
