### ISSUE TITLE
Use hidden / secret variables in commands

### ISSUE THREAD

**Issue by MiguelAlho** [Microsoft/vso-agent-tasks#388]
Do secret / hidden variables defined at the build level get excluded from calls to commands, if they are a part of that command, in TFS?

for instance, in order to tag the repo with the version number, I'm trying to do the following:

git push https://${env:tagUser}:${env:tagPass}@${env:tagUrl} $versionString

in a powershell script. The three env:<name> variables are defined as build variables. tagPass is the only one that is hidden. tagUser and tagUrl get substituted in the command; tagPass may or may not - the logged error message message excludes the text (as expected). The command fails only if tagPass is marked as hidden. If I save it as unhidden, the push works correctly.

My thought here is that since it is a call to a command (something that may interact with stdout), the variable value is stripped from the command, and authentication fails because of that. Is my assumption correct, and if so, any recommended work arounds?

**Comment by bryanmacfarlane** [comment]
Does 
$(tagUser)@$(tagPass)... work?
note our vars are replaced with parens and no env:

**Comment by bryanmacfarlane** [comment]
@(var) should get replaced on all inputs including secrets

**Comment by chrisrpatterson** [comment]
You need to use $(tagUser) not ${env:tagUser}

**Comment by MiguelAlho** [comment]
With:
```
 git push https://$(tagUser):$(tagPass)@$(tagRepoUrl) ...
´´´

I get a bunch of errors: such as 

```
tagUser : The term 'tagUser' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
´´´

Same if I use the @(tagPass) syntax : 
```CategoryInfo : ObjectNotFound: (tagPass:String) [], CommandNotFoundException´´´

**Comment by MiguelAlho** [comment]
After I had posted the issued, I went out a different path, that seems to work (I did test your suggestions though).

What workd for me:

Set local variables with the arguments passed to the script:

```
[string]$tagUser = $args[0]
[string]$tagPass = $args[1]
[string]$tagRepoUrl = $args[2]
```

add use the local vars in the script:

```
git push https://${tagUser}:${tagPass}@${tagRepoUrl} $GitVersionJson.MajorMinorPatch --porcelain
```

this actually works and the log message has the password replaced with *'s

**Comment by chrisrpatterson** [comment]
I see you are trying to use variables in your script, I missed that somehow.  The variable replacement we do is on the inputs on the tasks, we don't parse the scripts.  To use secret variables you will have to take those as inputs into your script we explicitly do not populate those into the environment.  Other variables you should be able to reference as normal environment variables if you want.

**Comment by MiguelAlho** [comment]
Thanks guys! I think this might be worth including in some future documentation, since it isn't clear (and to a powershell noob like myself, tough to discover).

**Comment by tuespetre** [comment]
+1 @MiguelAlho

**Comment by dennisroche** [comment]
@MiguelAlho 

If using PowerShell, you can access secret variables using `Get-TaskVariable` function from `Microsoft.TeamFoundation.DistributedTask.Task.Internal` module.

Example:

```ps1
Import-Module "Microsoft.TeamFoundation.DistributedTask.Task.Internal"

$username = Get-TaskVariable -Context $distributedTaskContext -Name "ApiUsername"
$password = Get-TaskVariable -Context $distributedTaskContext -Name "ApiPassword"

$cred = New-Object System.Management.Automation.PSCredential($username, (ConvertTo-SecureString -String $password -AsPlainText -Force))
```

The `ApiPassword` is marked as secret in the build definition and will be logged to the console as `*******`.

**Comment by chrisrpatterson** [comment]
That will only work from a task it will not work from a arbitrary powershell script.

**Comment by carlosrfernandez** [comment]
@chrisrpatterson can you expand on your last comment?

I'm actually creating a build task, and upon executing the associated Powershell script, I'm getting this 
`Cannot bind argument to parameter 'Context' because it is null.`

Thanks

**Comment by tuespetre** [comment]
@carlosrfernandez ask on StackOverflow or get on [the AspNetCore Slack](http://tattoocoder.com/aspnet-slack-sign-up/) (I created a `#vsts-tfs` channel in there.) I will be glad to help.

**Comment by carlosrfernandez** [comment]
@tuespetre Thanks, I've joined the Slack team. 

In the end I've solved the issue by reading up on the new SDK documentation. 

I can get access to the secret variable using this:
`$sourcesDirectory = Get-VstsTaskVariable -Name "Build.SourcesDirectory"`
