### ISSUE TITLE
Build task for SharePoint Add-Ins

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#389]
I've created a custom build task for building SharePoint Add-Ins at https://github.com/iozag/sharepoint-build-tasks. Is there any interest to put this into this repository? If so I'm happy to create a PR.

**Comment by chrisrpatterson** [comment]
Hi Pascal,

this will be something that will be good for the public gallery later this year.  It is a bit too specialized for in the box as the scenario is easily accomplished by adding a couple of MSBuild arguments to the existing MSBuild or VSBuild task

**Comment by pascalberger** [comment]
OK. But never use the word easily together with SharePoint :)
