### ISSUE TITLE
MSBuild step is not a clean MSBuild task

### ISSUE THREAD

**Issue by lukas-ais** [Microsoft/vso-agent-tasks#398]
Configuration of a step of type MSBuild requires providing a solution file (*.sln).
So it is not really a MSBuild task.
I would like to run a MSBuild script, not a specific solution.

Is it possible to change the task accordingly? If not, the current one may be renamed and a a new new one created instead.

**Comment by pascalberger** [comment]
You should be able to pass any MSBuild script to the MSBuild task, since this will be straightforward passed to msbuild.exe (See https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/MSBuild/MSBuild.ps1#L165).

**Comment by lukas-ais** [comment]
Ok, I'll try if it works.
Anyway, I think you should switch behavior and description: A task which is named "MSBuild" should **focus** on MSBuild and **allow** solution files.

**Comment by pascalberger** [comment]
I think this can be closed with db9f229ec5ebd7a65786994b88c49cc2e0000ae3
