### ISSUE TITLE
Locating help on TFS Powershell commands 

### ISSUE THREAD

**Issue by staticcat** [Microsoft/vso-agent-tasks#413]
When writting a custom action I seem to be unable to find information on commands like; 

Invoke-Tool

Also I am unable to find any help on the majority of imported modules, like;

import-module "Microsoft.TeamFoundation.DistributedTask.Task.Internal"
import-module "Microsoft.TeamFoundation.DistributedTask.Task.Common"

I was wondering if someone would be able to point me at the API documentation for all the custom commands/cmdlets used for VSO/TFS tasks. 

Thanks.

**Comment by staticcat** [comment]
It also seems that the help file relating to the environment variables setup for the tasks has been removed from the repository. 

variables.md

**Comment by pascalberger** [comment]
See also #352

**Comment by bryanmacfarlane** [comment]
Documenting tasks is in the works.  We will also be creating a new PS lib that's more testable

**Comment by bryanmacfarlane** [comment]
using #352 to track
