### ISSUE TITLE
VSTest Task does not quote the testFiltercriteria if the value includes spaces

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/vso-agent-tasks#416]
The VSTest task allows you to specify test filter criteria as part of the `testFiltercriteria` property.

If the value of this property includes spaces, running the build will fail because the test filter criteria are not quoted.

For example, setting the `testFiltercriteria` property to `/TestCaseFilter:TestCategory !=ThriftRequired` will result in the following command line:
```
Executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe (...)  /TestCaseFilter:TestCategory !=ThriftRequired
```
and the following error:
```
2015-08-17T13:36:36.7199841Z ##[error]Error: The test source file "!=ThriftRequired" provided was not found.
```

Manually quoting the `testFiltercriteria` in the settings works as a temporary workaround.

**Comment by atinb** [comment]
Hi Frederik,
This is already fixed and you should not see this behavior once Sprint 87 deployment is complete (most likely end of this week)
Thanks!

**Comment by atinb** [comment]
S87 is now deployed. Please take a look and let us know if you have more feedback. Thanks!
