### ISSUE TITLE
The AzureWebPowerShellDeployment task needs to fail properly if the Get-AzureWebsite command fails.

### ISSUE THREAD

**Issue by dimkanewtown** [Microsoft/vso-agent-tasks#423]
Right now with VS2015 out already some website configs have the unreleased "VS2015" option for remote debugging checked in the configuration (neither VS 2012 or VS2013 option is checked) and that causes the Get-AzureWebsite command to fail. (http://www.brandonmartinez.com/2015/07/14/resolve-a-requested-value-vs2015-was-not-found-get-azurewebsite-error-in-powershell/)

When that happens the task tries to create a new website with the same name and then that task fails.

Example code 
    2015-08-19T00:05:18.2923740Z Get-AzureWebSite -Name myportal -Slot staging -ErrorAction SilentlyContinue
    2015-08-19T00:05:32.3355539Z New-AzureWebSite -Name myportal -Location East US -Slot staging

Whomever put the -SilentlyContinue switch is assuming that the Get-AzureWebSite can only fail for one reason, that the site is not provisioned yet.

**Comment by yaananth** [comment]
#526 closing as duplicate
