### ISSUE TITLE
Is quoting of $(currentDirectory) required?

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#427]
I see that in the tasks target and working directories for the execution tasks are not quoted (eg. https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/VSBuild/task.json#L113). Is this by design? Do the tasks still work like this if the build agent is installed in a directory containing spaces in its name?

**Comment by bryanmacfarlane** [comment]
It should work fine since it's not a CL arg - it's data that we then do a programmatic replace on.  We did testing with folders with spaces, projects with spaces etc...  So, if you hit an issue, reopen this issue
