### ISSUE TITLE
Does it make sense to have a cspack vso agent task

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/vso-agent-tasks#433]
I use Octopus Deploy extensively and it's handling of Cloud Services deployments is a bit clunky (http://docs.octopusdeploy.com/display/OD/Azure+Cloud+Services), I basically need to package the Azure Cloud Services bits with cspack which are then rolled into a NuGet package and sent to the Octopus deploy server.

Since I now have a working custom NuGetPackage and NuGetPublish steps (this to the community here) and I'm thinking to create another custom step which runs right before these to create the package.

Does this sounds sensible, does anyone know if this has been done already and I've missed it ? Are the Azure deployment tools like cspack already on the VSO hosted agent or should I ship cspack with my code.

**Comment by chrisrpatterson** [comment]
There is an octopus deploy task that you could use and I believe it takes care of running octopack to create the package.  Is that what you are looking for?

**Comment by marklnz** [comment]
Chris, are you referring to https://github.com/OctopusDeploy/OctoTFS? If so, I can report that this definitely does not run Octopack for you - it's currently only for creating a release and optionally deploying it.

**Comment by bryanmacfarlane** [comment]
We don't plan on creating a cspack task.  You can however script it yourself
