### ISSUE TITLE
Azure Cloud Service Deployment missing "Affinity group" setting

### ISSUE THREAD

**Issue by DHoefakker** [Microsoft/vso-agent-tasks#446]
When i add the task "Azure Cloud Service Deployment" i can configure "Service Location".
But i cannot define a Affinity group.
When i specify the affinity group in service location it fails.
The command executed by the deployment script is : 
New-AzureService -ServiceName ServiceName -Location AffinityGroupName

This needs to be :
New-AzureService -ServiceName ServiceName -AffinityGroup AffinityGroupName

**Comment by yaananth** [comment]
Addressed in PR
