### ISSUE TITLE
VSBuild task does not support compiling Typescript with decorators on hosted build agent

### ISSUE THREAD

**Issue by chrisswan-rm** [Microsoft/vso-agent-tasks#452]
When using the hosted build agent to compile Typescript that uses decorators, the build fails at the "CompileTypeScript" stage with error TS1219 ("Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.")

When building locally in Visual Studio you can set the "TypeScriptExperimentalDecorators" property to true in your .csproj file to make the Typescript compiler run with the "--experimentalDecorators" option. However, this does not seem to be passed through properly when building using the hosted agent - I suspect this is due to the "Microsoft.TypeScript.targets" file on the hosted agent not containing an entry to convert the "TypeScriptExperimentalDecorators" property to the appropriate command line option.

The way I worked around it was to pass " --experimentalDecorators" along with one of the properties that is converted properly (e.g. "\<TypeScriptTarget\>ES5 --experimentalDecorators\</TypeScriptTarget\>", resulting in the command line option "--target ES5 --experimentalDecorators") - but this is a bit of a hack!

**Comment by ericsciple** [comment]
What about when you build locally from the command line? I would expect the Hosted build to be consistent with that.

**Comment by ericsciple** [comment]
Closing the issue for now. Will reopen if you find Hosted build diverges from what you see when doing a build from your local command line.

There's multiple places where building from within Visual Studio does not match building from the command line. The VSBuiild tasks just runs msbuild on the SLN and passes /p:VisualStudioVersion=14.0 or whichever version number you choose.
