### ISSUE TITLE
Uploading Custom Task failed

### ISSUE THREAD

**Issue by Br41n88** [Microsoft/vso-agent-tasks#465]
So i was trying to upload the "Azure File Copy" task to VSO via TFX.

But after getting this message

>user:Tasks *username*$ tfx build tasks upload ./AzureFileCopy
>Copyright Microsoft Corporation
>
>task at: ./AzureFileCopy uploaded successfully!

it was nowhere to be found in VSO (and neither in the task list via TFX).
So i tried to upload it again but received the following error

>user:Tasks *username*$ tfx build tasks upload ./AzureFileCopy
>Copyright Microsoft Corporation
>
>Error: Failed Request: Conflict(409) - https://****.visualstudio.com/_apis/distributedtask/tasks/EB72CB01-A7E5-427B-A8A1-1B31CCAC8A43?overwrite=false

So it seems to me that there was something uploaded but not correctly...

Trying to overwrite it with --overwrite produces the first message again but the task is still not visible.
And deleting it with the ID from the error message doesnt work (task not found error message).

I do have the necessary admin privileges and creating and uploading the "Hello World" task worked.
Any ideas what might be the problem?
Is it even possible to upload a single task out of the repository?

Thanks in advance
Br41n

**Comment by chrisrpatterson** [comment]
The AzureFileCopy task is in preview and not enabled in all accounts but it is installed.  You can't install two tasks by the same id in you account which is why you get a conflict.

**Comment by pascalberger** [comment]
@chrisrpatterson Is there a way to switch a VSO tenant in preview mode to have access to the preview tasks?

**Comment by RoopeshNair** [comment]
@pascalberger  
We are currently previewing this service to some customers. If you are interested in participating in the preview, send us an email to rm_customer_queries at microsoft dot com
