### ISSUE TITLE
Skipped JUnit tests are reported as passed

### ISSUE THREAD

**Issue by adriaanthomas** [Microsoft/vso-agent-tasks#470]
Using the _Publish Test Results_ task, _Test Result Format_ as JUnit, given a skipped test (fragment):

```xml
<testcase name="should return a promise" time="0" classname="given the contractAccountAuthorizationService initialise">
  <skipped />
</testcase>
```

VSO reports the test as passed (using Windows agent).

**Comment by bryanmacfarlane** [comment]
assigning to madhuri

**Comment by TwoToneBytes** [comment]
It looks like there is no explicit check for `<skipped/>`:

![image](https://cloud.githubusercontent.com/assets/611695/9645916/c82059d4-5183-11e5-8598-c1441c5df1ad.png)

This is from JUnitResultReader.

**Comment by madhurig** [comment]
That's right, we only do a check for Failed, I will try to get fix in today. Thanks!

**Comment by madhurig** [comment]
Fix for windows agent is committed to our internal repo, it will be deployed to VSO with the next update in a couple of weeks. @TwoToneBytes , thanks for creating the pull request for the OSX/Linux agent.
