### ISSUE TITLE
Run two Azure PowerShell tasks fails on the second

### ISSUE THREAD

**Issue by FabienLavocat** [Microsoft/vso-agent-tasks#476]
I have the following issue with the Azure PowerShell tasks (and a workaround). I can reproduce the problem on a self hosted build server or the VSOnline one.

##### Steps to reproduce
- I create a new Build Definition
- Add an Azure PowerShell task, link it to a script.
- Add a second Azure PowerShell task, linked to the same script (to make it simple)

To reproduce the problem, you can just have one line in the script: `Get-AzureVM`. This should connect to your Azure subscription and list the VMs of your account.

##### Problem
If you run this build definition, the first script will execute without issue. The second script will not be able for some reason, to run the `Get-AzureVM` commandlet. I always get this error message `##[error]An error occurred while sending the request.`
Adding other tasks in between doesn't change anything.

##### Workaround
Set the first task as an Azure PowerShell task, and the second one as a simple PowerShell task (without having to change the code). The Azure context is passed to the second PowerShell task.

**Comment by bryanmacfarlane** [comment]
Sounds like a bug.  Add Yaswanth to investigate

**Comment by FabienLavocat** [comment]
If it is a bug, I have something that might be related.
If I create an `Azure PowerShell` task followed by a `Cloud-based Load Test` task (or a `Cloud-based Web Performance Test` task) I get the following error:

```
##[error]The underlying connection was closed: An unexpected error occurred on a receive.
##[error]Connection '30298abc-dde6-0000-0000-xxxxxxxx' failed for service 'https://xxx.visualstudio.com/'
```

**Comment by bryanmacfarlane** [comment]
That sounds unrelated - create another issue

**Comment by FabienLavocat** [comment]
Ok, I'll create a different issue

**Comment by yaananth** [comment]
I tried this locally, cannot repro, what am I missing?

![image](https://cloud.githubusercontent.com/assets/12280011/9664993/450fd98a-523b-11e5-95f9-318298605c55.png)


Tried with M87 and M88 agent.
My powershell script has just this:
 Get-AzureVM

and I tried with muliple commands as well -
 Get-AzureSubscription
 Get-AzureVM

Could this be a problem with azure certificate it's self?
May be update the certificate or create new one?

**Comment by FabienLavocat** [comment]
Actually, just doing a script with Get-AzureVM and run it in two different `Azure PowerShell` task works. I have a more complex script that I run twice and the second fails on `Get-AzureVM`.
I am trying to reduce the size of the script so I can share it with you.

**Comment by yaananth** [comment]
Thanks that would be helpful, I tried on Vsonline as well, as you mentioned simple command works.

**Comment by FabienLavocat** [comment]
I found the problem. I was using the following line:
`[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}`
Because I am downloading a file on a VM but the SSL certificate is not valid. It seems I don't need it. Removing this line and the code works again.
