### ISSUE TITLE
Azure PowerShell task followed by a Cloud-based Load Test task fails

### ISSUE THREAD

**Issue by FabienLavocat** [Microsoft/vso-agent-tasks#480]
I am facing the following issue with the new build definition system in VS Online.
##### Steps to reproduce
- I create a new Build Definition
- Add an `Azure PowerShell` task, link it to a script.
- Add a second task that can either be `Cloud-based Load Test` or `Cloud-based Web Performance Test`

##### Problem
If you run this build definition, you will see the first script working well, but the load test task failing with the error: 
```
##[error]The underlying connection was closed: An unexpected error occurred on a receive.
##[error]Connection '30298abc-0000-0000-0000-xxxxxxxxxxxxx' failed for service 'https://xxx.visualstudio.com/'
```
If I disable the Azure PowerShell task, the load test works well.

##### Workaround
Unfortunately, I don't have a workaround on this one.

**Comment by bryanmacfarlane** [comment]
assigning to CLT owner to investigate

**Comment by FabienLavocat** [comment]
Actually, I found the error I have in one of the PowerShell script. (See issue #476 )
Having the line ` [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true} ` make almost every following task to fail.
