### ISSUE TITLE
The type or namespace name 'Azure' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by Bartmax** [Microsoft/vso-agent-tasks#494]
I think the azure sdk is not installed by default on Hosted Agent. Does it make sense to have it pre installed by default? specially when you have a Windows Azure Web Deploy template.

**Comment by bryanmacfarlane** [comment]
Azure Deploy and other scenarios work on the hosted agent.  If you're having an issue/error, can you add more context and details?

**Comment by Bartmax** [comment]
you are right. problem was my project. Closing. I will re open another issue with one error I couldn't get past.
