### ISSUE TITLE
Nuget Packager - remarks

### ISSUE THREAD

**Issue by Pitterling** [Microsoft/vso-agent-tasks#501]
Hi, i just tried the Nuget Packager on my OnPremise TFS and have a couple of remarks.

1. )
my nuspec file is not within my build output directory. It seems that it is expected to have the nuspec files along with all the other files in the same directory.

I got this solved by specifying a Nuget Argument within the Advanced section, like this:
-BasePath $(Build.SourcesDirectory)\bin\$(BuildConfiguration)

Maybe its worth including a "BasePath" parameter?

2.) I also create PreRelease Nuget Packages - this is handled by adding a string like "-dev" to the package name. With the current implementation i don't see a way to handle this. Maybe its worth to add another Parameter?

Thx, keep up the good work

**Comment by pascalberger** [comment]
For 2). You should be able to define the version yourself by using the -version parameter in the additional arguments section.

I already have created a PR for having a link to the NuGet documentation in the help markdown for the additional arguments (#491). I don't know if it is a good idea to have inputs for every possible command line parameter.

**Comment by Pitterling** [comment]
ah, thx. I wasn't aware of that.
I'm still struggeling to provide the version dynamically. Unfortunately there is no variable available which just contains the BuildVersion - (something like BuildNumberFormat without the BuildDefinitionName). So it seems i have to rely on something else like GitVersion to provide such a variable to be used in the -version parameter.

**Comment by bryanmacfarlane** [comment]
@pascalberger - we map inputs to common/mainline paths - and then typically offer some sort of "additional args" advanced option.

**Comment by pascalberger** [comment]
Thanks @bryanmacfarlane, I'm aware of that. I think #491 would go well with this "architecture"

**Comment by chrisrpatterson** [comment]
#491 is merged
