### ISSUE TITLE
Tasks documentation

### ISSUE THREAD

**Issue by Pitterling** [Microsoft/vso-agent-tasks#510]
more and more tasks are coming up. Is there any central place where all the tasks will be documented?
So far i have seen some Tasks having a link to furhter help documentation. Is that the way it should go?

**Comment by bryanmacfarlane** [comment]
We will be adding more scenario based markdown docs (and videos) on the front page of the repro.  Also, tasks will optionally carry a task specific markdown document in each folder.  We started with a handful and we have an event planned to document the rest.
