### ISSUE TITLE
PublishBuildArtifacts.ps1 - just copy files from artifact to target, instead of folder?

### ISSUE THREAD

**Issue by Pitterling** [Microsoft/vso-agent-tasks#511]
using this task always creates a folder on the Fileshare, e.g. my artifact is called "drop". If i copy that to a fileshare folder, a subfolder drop will be created. Is there any way just to copy the content of the artifact to a target folder?

**Comment by chrisrpatterson** [comment]
No, we create an folder named for the artifact at the location specified.  You could publish multiple artifacts to the specified location.
