### ISSUE TITLE
The build has been queued and is waiting to start. for ages

### ISSUE THREAD

**Issue by ghostinside** [Microsoft/vso-agent-tasks#512]
Have three steps 

1 - build project
2 - run tests
3 - deploy azure web app

if i enable just first two ones the build starts in a few seconds 
if i enable all 3 ones, i just see "The build has been queued and is waiting to start", i also see the alert that build agent can be offline, but again disable azure deploy step will allow me to run build successfully

**Comment by yaananth** [comment]
You are likely missing capability "azureps" ( I believe when you queue this is one of the capabilities it's complaining about? ) You would have to install "Azure power tools" on agent machine ( you can install from Web platform installer ). We should document this..

**Comment by ghostinside** [comment]
will try, would appreciate if agent will reise an error in this scenario

**Comment by yaananth** [comment]
The alert should mention it already. It would talk about capabilities, It couldn't find any agent satisfying all those capabilities, so no agent can pick it up .

**Comment by ghostinside** [comment]
yeh, but you know it was not obvios for me, i checked agens and found them online. could you please add message like ..... or you dont have all requred tools installed on the agent machine, something like that

**Comment by yaananth** [comment]
Yes, we should definitely improve the message and document it..

**Comment by ghostinside** [comment]
have installed azure-powershell on the agents machine, did not help

**Comment by bryanmacfarlane** [comment]
It registers capabilities on start up of the agent.  If you go to the web admin UI, does it advertise that capability yet?

**Comment by ghostinside** [comment]
ha, i have installed Power Shell for VS.Net 2015 and it suddenly start working, hm would appreciate for developers if it would be possible to have some diagnostics logs to figure our what missed to start each task

**Comment by ghostinside** [comment]
brian mcfarlane, when i install Azure PowerShell the alert disappeared, but the build process was pending, only PowerShell for vs.net helped (i thought)

**Comment by yaananth** [comment]
Can you paste the capabilities it displayed before if you remember?  ( or the screenshot of the dialog? ) Does it show azureps at all?

**Comment by ghostinside** [comment]
It showed as exists

Thx Alex
09 сент. 2015 г. 22:29 пользователь "yaananth" <notifications@github.com>
написал:

**Comment by yaananth** [comment]
I meant the queue dialog ( where it complained about capabilities before ).
You said after installing azure powershell tools, the alert was gone, but the build process was pending, meaning build was not picked up? May be it was just waiting to be picked up and wasn't picked up yet, i would think, build should be picked up if there are no alerts ...Also I don't know what powershell tools for VS will install, can you also send screen shot of all capabilities listed in the web UI

**Comment by michaelgwelch** [comment]
I see this on VSO many times. I'm waiting 15 minutes now.  (Just before that I was getting a build to run after just a few seconds). Not sure what is meant by the missing capability "azureps". I see no alerts or warnings when I queue the build.

**Comment by yaananth** [comment]
@michaelgwelch that would be separate vso service issue. I believe you were using hosted agent, there would be one agent per account, and there might be service related issues during that time, please open support tickets if the delay is more and you see it often.

@ghostinside  if you could paste the list of capabilities it complained before, it would help.
Installing Azure powershell satisfies "azureps" capability, you wouldn't need to install Azure PowerShell Tools for VS 2015.
If you can confirm that, we can close this issue with a take away of adding more info in the error messages.

**Comment by ghostinside** [comment]
sorry, was busy. i dont remember the whole flow, but agent showed that azureps exists, but the build did not start. then i have install "WindowsAzurePowerShell.3f.3f.3fnew" at 04:43 and run the commands to be authorized according to the instruction, the alert disapiried but it did not help then i have install  "PowerShellTools.14.0.vsix" at 5:09 not sure why but the build ran successfully

**Comment by yaananth** [comment]
I would say installing "PowerShellTools.14.0.vsix"  shouldn't make the build to start, but it would have made the build to succeed depending on your build process. It would help if you could send the _diag logs  ( for the build you were mentioning ) to confirm that. ( if you still have the build :D )

**Comment by ghostinside** [comment]
Will try to find
14 сент. 2015 г. 17:56 пользователь "yaananth" <notifications@github.com>
написал:

**Comment by yaananth** [comment]
closing this as issue it'self is resolved, please send any logs that would help to my email.
Thanks!
