### ISSUE TITLE
Error running powershell task in TFS Build

### ISSUE THREAD

**Issue by naeemsarfraz** [Microsoft/vso-agent-tasks#520]
I have a very simple script which spits out environment variables like this:

    Write-Host "SYSTEM_TEAMPROJECT: $ENV:SYSTEM_TEAMPROJECT"

My build has one step, the PowerShell task. The task script filename is set to the path to the script in TFSVC e.g. $/Main/BuildProcessTemplates/AllProps.ps1.

When I queue a new build it fails reporting the following error: *"The term 'C:\Builds\agent_work\cb535ea3\Main' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."*

Have I configured the task incorrectly?

**Comment by bryanmacfarlane** [comment]
Did you use the browse (... button) to get that path?  Just want to make sure repo etc... is configured properly.

**Comment by naeemsarfraz** [comment]
Tracked down the problem. I needed to include the repository location of the powershell script in the Mappings section of the Repository tab. Working fine now.

See http://stackoverflow.com/a/32453564/40986.
