### ISSUE TITLE
Publish-AzureWebDeployment fails to detect existing web site

### ISSUE THREAD

**Issue by ChristianRygg** [Microsoft/vso-agent-tasks#526]
A VSO build which worked a few days ago has started failing on the Publish-AzureWebDeployment step. It seems it doesn't detect that the target site exists and tries to create it - which fails because it does in deed exist. When it worked, I saw:

```
2015-09-07T06:59:39.7014443Z Get-AzureWebSite -Name [appname] -ErrorAction SilentlyContinue
2015-09-07T06:59:49.2099687Z Publish-AzureWebsiteProject -Name "[appname]" -Package "C:\[path]\[projectname].zip" 
```

However, now I see:

```
2015-09-08T08:52:56.7203746Z Get-AzureWebSite -Name [appname] -ErrorAction SilentlyContinue
2015-09-08T08:53:04.4459153Z New-AzureWebSite -Name [appname] -Location West Europe
2015-09-08T08:53:08.9519867Z ##[error]Conflict: Website with given name [appname] already exists.
```

I suspect the "-ErrorAction SilentlyContinue" swallows an error, but no idea what. As far as I know, there has been no change to the deployment access to the site since the build last ran OK.

Ref. thread from the "Azure App Service - Web Apps" forum, where one other had the same issue arise around the same time: [Azure Deployment to Web App - Conflict: Website with given name <web app name> already exists.](https://social.msdn.microsoft.com/Forums/en-US/c0f6a4d8-a307-466c-ba75-5b292663d43b/azure-deployment-to-web-app-conflict-website-with-given-name-web-app-name-already-exists?forum=TFService)

**Comment by ChristianRygg** [comment]
It seems this is related to:

https://github.com/Azure/azure-powershell/issues/462
http://www.brandonmartinez.com/2015/07/14/resolve-a-requested-value-vs2015-was-not-found-get-azurewebsite-error-in-powershell/

Workaround: When I disabled remote debugging for VS2015, the build worked. Turning it off while still set to 2015 apparently isn't enough.

**Comment by gorillapower** [comment]
I having the exact same problem. I have been having this issue for about a month now, I posted the problem on the msdn forums:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/ca1c9aec-260a-44cf-b590-4211ea49a849/azure-deployment-fails-azureconflict-website-with-given-name-sitename-already-exists?forum=windowsazurewebsitespreview


I will confirm if turning off remote debugging works. VSO Build Service experiencing issues...

**Comment by abatishchev** [comment]
Hello,
Our (MPSIT) build in VSO was working fine just few days ago but now constantly fails with the same error. Nothing was changed in neither the building step nor the website.
Please advise.

**Comment by abatishchev** [comment]
Ping @yaananth

**Comment by yaananth** [comment]
@abatishchev Can you try what was already discussed above? If still fails, you try the same command on your local azure powershell and see if you get same error.

**Comment by abatishchev** [comment]
No, not really, I wish it would.

Here's some errors I'm getting once disabled remote debugging (vs2015:

>2016-02-09T18:44:59.2419483Z Get-AzureWebSite -Name bla -ErrorAction SilentlyContinue -ErrorVariable azureWebSiteError -Slot production
>2016-02-09T18:45:20.4504239Z ##[warning]System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 23.102.135.246:443

and

>2016-02-09T18:50:18.8947121Z Get-AzureWebSite -Name bla -ErrorAction SilentlyContinue -ErrorVariable azureWebSiteError -Slot production
>2016-02-09T18:50:21.9447860Z ##[warning]System.ArgumentException: Requested value 'VS2015' was not found.

**Comment by yaananth** [comment]
@abatishchev Switch to 2013 debug mode. There was a bug in azure, looks like it isn't fixed yet.
http://www.brandonmartinez.com/2015/07/14/resolve-a-requested-value-vs2015-was-not-found-get-azurewebsite-error-in-powershell/

**Comment by abatishchev** [comment]
That helped, thanks!
