### ISSUE TITLE
Passing build properties to NuGetPackager task

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#529]
The `nuget pack` command allows to set properties for the build. With the current implementation of the NuGetPackager task they cannot be used, since the task already fix sets the configuration property and a passing a second `properties` parameter in the NuGet arguments results in invalid command line arguments for nuget.exe.

To handle this case, I would suggest to introduce a new input in the advanced section of the task for build properties which in the PowerShell script can be added to the existing Configuation property.

Would this make sense? If so I can provide a PR for the necessary changes.

**Comment by pascalberger** [comment]
@chrisrpatterson Any opinion about this?

**Comment by chrisrpatterson** [comment]
Yes that would make sense, pretty much all of the tasks we have that drive a command line have this sort of ripcord parameter where you can just pass additional command line parameters.

**Comment by pascalberger** [comment]
@chrisrpatterson Thanks, I've submitted a PR. Any chance to have this merged (and the other NuGet related PRs I've submitted: #491, #492)?
