### ISSUE TITLE
Run *unit tests out of the box

### ISSUE THREAD

**Issue by trailmax** [Microsoft/vso-agent-tasks#538]
I'm trying to get Nunit tests running on VSO and having a bad time. Could not find a task that could do it, could not find a definite guide on how to get this done anywhere. I have seen this article: http://www.donovanbrown.com/post/2015/06/15/how-to-run-xunit-test-with-vnext-build

But this no longer works - when I set `$(Build.SourcesDirectory)\Packages` into **Path to Custom Test Adapters** I get build error `Could not find file 'C:\a\dd5f97d6\MyProjectName\Packages`. 

It would be good if there was a simple way to add task runners for Nunit/Xunit or at least an up-to date guide on how to get these working with the new VSO build process.

**Comment by atinb** [comment]
trailmax, can you tell me if you are using a Nuget package for NUnit? Does this directory exist on your build agent machine: 'C:\a\dd5f97d6\MyProjectName\Packages? Thanks!

**Comment by trailmax** [comment]
@atinb that's a good point you have raised!

I've checked the logs and the path should be `C:\a\dd5f97d6\MyProjectName\MyProjectName\Packages` (note deeper folder structure) because of the project structure.

This have fixed the issue, but amount of time and magic dances I had to do is prohibitive. I was hoping for an easier way to migrate my projects into VSO.

**Comment by atinb** [comment]
In the last deployment, we made changes so that you do not have to specify the path for Nuget restored packages. If you are on VSO, you can try running NUnit tests without specifying anything in the Custom adapter field.
More feedback is welcome.

**Comment by trailmax** [comment]
I have removed the path to Packages and no tests were found - just tried that. I presume your last change assumes that Packages folder is in root, but does not look in a nested folder structure. 

_Honestly, I have no idea why my folder structure is like that - that is not intentional_
