### ISSUE TITLE
Are these really the default tasks in TFS?

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vso-agent-tasks#541]
The readme states that these are the default tasks when installing TFS, but there are some missing in mine, e.g. NuGet packager.

**Comment by pascalberger** [comment]
The tasks are not all released/deployed yet or some are in preview state and only visible on certain tenants. NuGet packager task [should be deployed in the next release end september](https://github.com/Microsoft/vso-agent-tasks/pull/381#issuecomment-137135117).

**Comment by bryanmacfarlane** [comment]
correct.  Also, if you're installing TFS on-prem, those tasks are from ~ releases/m83 branch.  QU1 will likely contain releases/m89 branch which will be created next week or so ...  master is current development and we branch off releases/m## branch for each 3 week release to visual studio online.  A CI process packages for ingestion into the TFS/VSO build process

**Comment by tomkuijsten** [comment]
Got it, thanks.
