### ISSUE TITLE
How to install these build tasks in TFS

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vso-agent-tasks#542]
I found the tfx command line utitlity, but that's not applicable for me as it doesn't support NTLM yet.

**Comment by bryanmacfarlane** [comment]
The tasks in the master branch represent code 3 months ahead of your RTM server and are slated to be delivered in the on-prem QU1 update (soon).

We're open sourcing so we're open and provide reference examples on how best to write your own custom tasks. 

If you find a task that has minimum agent of m83 (approx. RTM) then it may work.  tfx is the way to upload and you are correct that you need to enable basic auth to do that (it's documented from the readme).  If that's not an option, then yes, you need to wait for ntlm support

**Comment by tomkuijsten** [comment]
Very clear answer, thanks!
