### ISSUE TITLE
How to add npm dependencies to build tasks

### ISSUE THREAD

**Issue by milliamp** [Microsoft/vso-agent-tasks#551]
I am very new to node so I might be just simply missing something really obvious here. 

Is there a mechanism for pulling NPM dependencies for build tasks? I've had a read through the tasks in this repo but can't find any that depend on things other than the standard list provided by the `vso-agent`.

I am writing a custom build task and would like to depend on an NPM module.

If not, is there a standard pattern that makes sense for this?
I haven't tried any of these options but these are the patterns I can think of to try next:

* Include `node_modules` folder within the task with full resolved package in it
* Provide a `package.json` and try and run `npm install` on task start before requiring the module
* Hack the `package.json` for the `vso-agent` on the machine and run `npm install` for each agent

**Comment by bryanmacfarlane** [comment]
We are not pulling from npm during the build.  We discussed it.

Right now, the solution is the task is self contained.  Create the node_modules folder and package it up.

it gets interesting when you want many tasks to use that same dependency.  not as much of an issue with small js tasks but more interesting with windows with large binary/SDKs.

In the next release, we have the concept of a module being added which is just a package of files that can be uploaded to the service/server and pulled down during the build.  We also have a team working on different private packaging within VSO/TFS so we're looking at that as well.  Still an open topic.  So, package it up for now.
