### ISSUE TITLE
input task field - visible rule - multiple rules

### ISSUE THREAD

**Issue by matizk144** [Microsoft/vso-agent-tasks#552]
Hi!
I just creating new task, but I have problem, because I don't know how should I create visibleRule with two rules with AND/OR operator. Is it possible? Additionaly, is it possible to compare value with greater or less comparator?

**Comment by yaananth** [comment]
visibility rules are of format: "a" <relational operators> "b".
No logical operators are supported ( &&*, ||, ! )
Supported relational operators : ==, != , <, >, >=, <= after S88 is rolled out.
also note that "=" will be considered as "==" to support all rules before S88.
We have a story on improvising the task authoring.

**Comment by matizk144** [comment]
Thanks a lot, but I have another question:
How to use greater operator. I have first input field, which I can to input numer (type was setted to string, int is not supported), and on next field i want to set visible rule, that firstField > 1. Probably, the problem exist, because I trying to compare int with string. How to resolve it?

**Comment by jessehouwing** [comment]
I'd love this feature. Especially in combination with Pick Lists this is needed.

**Comment by KrishnaAdityaB** [comment]
@jessehouwing 
Take a look at EnvironmentName input type in AzureFileCopy task. https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/AzureFileCopy/task.json
