### ISSUE TITLE
input task field - visible rule greater operator

### ISSUE THREAD

**Issue by matizk144** [Microsoft/vso-agent-tasks#558]
Hi, guys,
Sorry for new issue, but previous issue (https://github.com/Microsoft/vso-agent-tasks/issues/552) was closed to fast.
How to use greater operator. I have first input field, which I can to input numer (type was setted to string, int is not supported), and on next field i want to set visible rule, that firstField > 1. Probably, the problem exist, because I trying to compare int with string. How to resolve it?

 During upload task, TFS respond: "Task definition visible rule 'NumbersCount > 1' is invalid. It should be of format "A = B" for Task with id '393124d0-5c71-11e5-a34e-4fe729340108'."

Example:
  "inputs": [
    {
      "name": "NumbersCount",
      "type": "radio",
      "label": "Numbers count",
      "defaultValue": "",
      "required": true,
      "options": {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4"
      },
      "visibleRule": "VersionType = AssemblyInfo"
    },
    {
      "name": "Number2Zero",
      "type": "boolean",
      "label": "Clear number 2",
      "defaultValue": "",
      "required": false,
      "visibleRule": "NumbersCount > 1"
    }

I need to show 'Number2Zero' input when NumbersCount have values (2,3,4). Is it possible?

**Comment by chrisrpatterson** [comment]
@yaananth I know you made some updates here but I can't remember when.  Can you comment here?

**Comment by yaananth** [comment]
Probably, the problem exist, because I trying to compare int with string. How to resolve it
>> Not really, in visible rules value is always a string
>> NumbersCount > 1 is correct, but it will be supported after Sprint 88 roll out.
