### ISSUE TITLE
editable variable during build

### ISSUE THREAD

**Issue by matizk144** [Microsoft/vso-agent-tasks#559]
I just thinking about sharing variables between build steps. For example (idea):
One build step increase version in assembly info and save increased version to build variable
Then, next build, which copy files, create specific folder using version numer and copy files to this folder. I remember, using XAML build, it was possible. Does exist possibility to use it in this build system? First think -> use temp files or database (any external environment), but at first I prefer to ask.

**Comment by chrisrpatterson** [comment]
That is fairly straight forward.  It is in the docs in the repo.

Set variable in variable service of taskcontext. The first task can set an variable, and following tasks are able to use the variable.
 Example: 
 ##vso[task.setvariable variable=testvar;]testvalue
