### ISSUE TITLE
How can we pass -verbose through to a task?

### ISSUE THREAD

**Issue by naeemsarfraz** [Microsoft/vso-agent-tasks#565]
I want to enable verbose logging for the Visual Studio task, how do we pass "-verbose" through to the VSBuild.ps1 task?

**Comment by naeemsarfraz** [comment]
I edited the powershell script VSBuild.ps1 and added "$VerbosePreference ='Continue'" and all the extra logging is available in the build logs.

I'd still like to know if there is a way to pass a "-verbose" arg from the build config screen.

**Comment by chrisrpatterson** [comment]
Add  variable to your build called system.debug and set the value to true.

Sent from my Windows Phone
________________________________
