### ISSUE TITLE
Azure Web App Deployment - Set DoNotDelete flag by default

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/vso-agent-tasks#567]
I used the [old-school continuous deployment from VSO to Azure](https://azure.microsoft.com/en-us/documentation/articles/cloud-services-continuous-delivery-use-vso/) for my Azure website.

I migrated my build from this continuous deployment to use the new build system, including the Azure Web App Deployment task.

The old way of deploying the website preserved additional files that were not present in the web deployment package; the Azure Web App Deployment task does not. It was a bit surprising to find out that my additional content was removed by the Azure Web App Deployment task.

You can influence this behavior by setting the `-DoNotDelete` value in the Additional Arguments value of the Azure Web App Deployment. That solved the issue for me.

I'd suggest you'd either set the -DoNotDelete flag by default, or expose it in the Azure Web App Deployment task UI by default, so users are aware about this task potentially deleting additional files in their website.

There are some other flags the `Publish-AzureWebsiteProject` takes that may be worth exploring; you can find them [here](https://github.com/Azure/azure-powershell/blob/master/src/ServiceManagement/Services/Commands/Websites/PublishAzureWebsiteProject.cs).

**Comment by kowsheek** [comment]
As far as I've seen on our builds the `-DoNotDelete` flag is enable by default (on vNext builds). And it's an option that I've not been able to disable: https://github.com/Microsoft/vso-agent-tasks/issues/453

**Comment by yaananth** [comment]
addressed in PR

**Comment by DavidKlempfner** [comment]
`-DoNotDelete` didn't work for me. I had to use this:
`-enableRule:DoNotDeleteRule`

![image](https://user-images.githubusercontent.com/13111539/148141628-ec24cfb2-147c-40cf-938f-20f8ac50eec5.png)
