### ISSUE TITLE
Is it possible to raise and display build warnings from build steps using TFS 2015?

### ISSUE THREAD

**Issue by mattbrooks2010** [Microsoft/vso-agent-tasks#573]
# Background

The questions below relate to TFS 2015 on-premise.

It is possible to fail a build step by returning a non-zero exit code from, for example, a `PowerShell` or `Command Line` step. The build logs also capture anything written to the standard output stream. It is also possible to fail a `Command Line` step if anything is written to the standard error stream.

# Question 1

Is it possible to raise build warnings via `PowerShell` and `Command Line` steps so that they're displayed on the build summary page under `Issues`? For example, in the same way that the `Visual Studio Build` / `MSBuild` steps are raised and displayed?

![image](https://cloud.githubusercontent.com/assets/2045274/10019793/45008c54-6137-11e5-80db-a793a5c714aa.png)

# Question 2

I notice in the build logs for the `Command Line` step the following lines:

````
2015-09-22T12:29:21.0696320Z Executing the following commandline. (workingFolder = C:\Builds\_work\dacceaf2\Repo)
2015-09-22T12:29:21.0696320Z C:\Builds\_work\dacceaf2\Repo\tools\Test\bin\Release\Test.exe .\src\Web\Content\Images\ C:\Builds\_work\dacceaf2\staging\Web\Content\Images\
2015-09-22T12:29:21.0696320Z Error message highlight pattern: 
2015-09-22T12:29:21.0706314Z Warning message highlight pattern: 
````

Is there any way to set these highlight patterns for the step?

**Comment by pascalberger** [comment]
You should be able to return warnings and errors from your script using [logging commands](https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md).

**Comment by mattbrooks2010** [comment]
@pascalberger OK thanks — tried emitting the output below from a PowerShell step and got the desired result on the build summary page:

````
Write-Host "##vso[task.logissue type=warning;]Test warning"
Write-Host "##vso[task.logissue type=error;]Test error"
````

![image](https://cloud.githubusercontent.com/assets/2045274/10051205/58244762-6218-11e5-9d1c-90d23caabf95.png)

Is there currently a generic way of teaching the build system what forms of existing tool output should be considered as warnings though — as per question 2 above? For example, it would be good to distinguish between a 'failed' step and a 'partially succeeded' step in some cases.

**Comment by bryanmacfarlane** [comment]
the logging cmds are the only mechanism.  and even though are proprietary, then just go to console out

**Comment by sufyannisar** [comment]
I am using _Run PowerShell on Remote Machine From File_
When I Write

Whenever I use Write-Host e.g.
`Write-Host "##vso[task.logissue type=error;]Test error"`
 in Powershell script I get error saying

> A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.

**Comment by pascalberger** [comment]
@cosminstirbu If you're using Cake you might be intereste in the [Cake.Issues Addin](https://cake-contrib.github.io/Cake.Issues.Website/). It provides addins for parsing MsBuild output for warnings and processing them further (by e.g. posting them as comments to VSTS pull requests). If it doesn't cover your scenario it can easily be enchanced with additional addins or code in your Cake script.
