### ISSUE TITLE
The "Batch Script" (and any other shell/posh/etc) task should set the build name to the BUILD_BUILDNUMBER environment variable on exit (upon completion).

### ISSUE THREAD

**Issue by dmccaffery** [Microsoft/vso-agent-tasks#581]
In MsBuild scenarios, one could call the UpdateBuildNumberAndDropLocation task, which would set the name of the build and drop location on the server. I automatically generate a semantic build version in both MSBuild (and now in a build script) and would like the name of the build within VSO/TFS to match the build number I generated. This makes it easier to find, especially for testers using manual test scripts -- since the build number matches the assembly informational version of the assembly / nuget package, etc.

In most cases, the build format just isn't acceptable as it is impossible to maintain semantic version (SEMVER) using the available arguments.

If the script modifies the BUILD_BUILDNUMBER; the server should pick up this change and use it.

**Comment by dmccaffery** [comment]
As a note, the VSO REST API supports this: https://www.visualstudio.com/integrate/api/build/builds#Updateabuild

This PATCH allows for setting the BuildNumber (in addition to other things). I looked through the NodeJS API, and it already supports the operation:

https://github.com/Microsoft/vso-node-api/blob/d5e6b874de488777b2c9a64437c8751a4b370374/api/BuildApi.ts#L482

**Comment by ericsciple** [comment]
The functionality it sounds like you're ultimately after is available now via the build.updatebuildnumber logging command. https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md

**Comment by dmccaffery** [comment]
@ericsciple you, sir, are fantastic!
