### ISSUE TITLE
A simple copy file task is needed

### ISSUE THREAD

**Issue by RobCannon** [Microsoft/vso-agent-tasks#620]
Either the Machine Copy task should be changed to make the Machine group parameter optional, or a create a new File Copy task that does the same thing, but only within the agent machine (or a network location that the agent has access to).

**Comment by roniga** [comment]
Hi,
    We are modifying the WindowsFileCopy task to support this and other scenarios. It would be available with the next release.

**Comment by bryanmacfarlane** [comment]
This sprint the PublishArtifact task is being split into a copy and publish task.

The copy task is generic, supports a list of minimatch patterns and copy patterns.  It's also not limited to windows.  It works on all platforms.

**Comment by bryanmacfarlane** [comment]
.. and the existing publishartifact task is getting renamed to Copy And Publish Artifacts.
