### ISSUE TITLE
Visual Studio Test Task: Add option to specify the Run Title

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/vso-agent-tasks#625]
Currently, the Visual Studio Test Task generates default titles for the test runs, such as `1279:VSTest Test Run Release Mixed Platforms`.

When you have multiple test runs running against the same build, it quickly becomes difficult to keep track of which which results relate to a specific run. For example, it would be easier if the test runs could be named `UnitTests`, `IntegrationTests`, and similar.

`vstest.console.exe` has a [RunTitle](https://msdn.microsoft.com/en-us/library/jj155796.aspx) parameter which can be specified as part of the `/Logger` switch (e.g. `/Logger:trx,RunTitle=IntegrationTests`), but currently the `/Logger` is hard coded in the `Invoke-VSTest` cmdlet.

Hence, a request to add an option to specify the Run Title in the Visual Studio Test Task.

**Comment by atinb** [comment]
We are looking to add this option in the next sprint or two. Will reply back once it is done
Thanks!

**Comment by jessehouwing** [comment]
I believe this has been in for a while now.

**Comment by atinb** [comment]
Yes, thanks Jesse. You will find this setting in the Reporting Options for the tasks.

**Comment by andydix** [comment]
"Reporting Options for the tasks"

Can you elaborate on this please? As far as I can see I don't have fields or a section for "Reporting Options" on the Visual Studio Test task I'm using in my build.

**Comment by atinb** [comment]
@andydix 
Are you on VSTS or using an On-Premise TFS? For On-Premise, this functionality will ship with Update2

**Comment by andydix** [comment]
Ah, ok. We're using on-premise. Thanks for the clarification.
