### ISSUE TITLE
Conditional tasks

### ISSUE THREAD

**Issue by naeemsarfraz** [Microsoft/vso-agent-tasks#629]
I have a CI build and a separate nightly build. The nightly build has additional tasks such as Publish and others. Ideally I'd like there to be one but there is no way to disable a step linking it to the selected trigger.

Can this be done?

If not I don't mind looking at this via a pull request. I've never done one before so can anyone advise on the process?

**Comment by bryanmacfarlane** [comment]
This is on our backlog for the service.  It's a good ask.
