### ISSUE TITLE
NuGetPackager - Space in path 

### ISSUE THREAD

**Issue by drewkg** [Microsoft/vso-agent-tasks#631]
There appears to be an issue with the NuGet Packager step, if the repository has a space in the path then the csproj or nuspec cannot be found.  I think the issue lies in the fact the source is not surrounded by quotations as the issue can be replicated in a normal powershell window.

**Comment by pascalberger** [comment]
I think this was already fixed with #579

**Comment by drewkg** [comment]
Yes this has been fixed in #579, can confirm it is working as expected now.
