### ISSUE TITLE
PANIC: ANDROID_AVD_HOME is defined but could not find AndroidBuildEmulator.ini file in $ANDROID_AVD_HOME

### ISSUE THREAD

**Issue by kfstorm** [Microsoft/vso-agent-tasks#645]
We are setting up Android build agent. I found that I can only use my domain username/password to start the VSO agent service. If I use NETWORK SERVICE or SYSTEM, below error will show:

> PANIC: ANDROID_AVD_HOME is defined but could not find AndroidBuildEmulator.ini file in $ANDROID_AVD_HOME

I've tried to set environement variable ANDROID_AVD_HOME but no help.

**Comment by bryanmacfarlane** [comment]
If you need to run the emulator, run the service as a user.  It needs the users profile etc...
