### ISSUE TITLE
How to enable the logger using "Test with Test Agent"? And get the results back to vso?

### ISSUE THREAD

**Issue by samgrimmer** [Microsoft/vso-agent-tasks#654]
I know you can specify a logger using vstest.console.exe /logger:trx, via the command line
And the location in the .runsettings:
< RunSettings>
  < RunConfiguration>
    < ResultsDirectory>c:\</ResultsDirectory>
  </RunConfiguration>
< /RunSettings> 

How do I enable the logger in the options using build step "Visual studio test using test agent"?
Because I can't see the logger file being produced anywhere?

**Comment by samgrimmer** [comment]
The Invoke-RunDistributedTests doesn't seem to give me the options I have with the VSTest Step.

Invoke-RunDistributedTests -TestMachineGroup $testMachineGroup -SourceFilter $sourcefilters -TestCaseFilter $testFilterCriteria -RunSettingsPath $runSettingsFile -Platform $platform -Configuration $configuration -CodeCoverageEnabled $codeCoverageEnabled -TestRunParams $overrideRunParams -TestDropLocation $dropLocation -Connection $connection -TestConfiguration $testConfigurations -AutMachineGroup $autMachineGroup -UnregisterTestAgentScriptLocation $unregisterTestAgentScriptLocation 

Write-Verbose "Leaving script RunDistributedTests.ps1"

https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/RunDistributedTests
RunDistributedTests.ps1

Any ideas?

**Comment by acesiddhu** [comment]
Hi,
Sorry for the delay. Which logger are you looking for? trx? This task enables trx automatically and uploads them to test runs. you can navigate to the test run and see the trx as attachments there. you can navigate to the test run from build summary page itself. 

Thanks
Siddhartha

**Comment by samgrimmer** [comment]
Hi Acesiddhu,

Thanks for the reply.
I can navigate to the test from the build summary page. But I only see the title of my test which ran and it's pass / fail status. There is no more test output.

However, if I manually kick off the tests via command line on the test agent server using vstest.console.exe /logger:trx the produced trx files contains more information about test:

<Results>
    <UnitTestResult executionId="38883ecb-7a7d-435e-97de-49b7cddb9b1a" testId="4d715d12-e7f4-4c74-a3b2-8597aff6aad1" testName="CreateAnOrganisation" computerName="OP-BUILD-AGENT" duration="00:00:30.2610000" startTime="2015-10-16T02:05:45.6684316+00:00" endTime="2015-10-16T02:05:45.6684316+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="38883ecb-7a7d-435e-97de-49b7cddb9b1a">
      <Output>
        <StdOut>Given I am an authenticated user
-&gt; done: OrganisationSteps.GivenIAmAnAuthenticatedUser() (6.3s)
When I create a new organisation
-&gt; done: OrganisationSteps.WhenICreateANewOrganisation() (2.2s)
Then I can view my newly created organisation
-&gt; done: OrganisationSteps.ThenICanViewMyNewlyCreatedOrganisation() (0.3s)</StdOut>
      </Output>
    </UnitTestResult>
  </Results>

You mentioned that it automatically creates the log file. Where does it save it? 
And can you give me any guidance (docs?) about these automatic activities that are carried out?

**Comment by samgrimmer** [comment]
You are right. The .trx file is present there as an attachment.
Is there a way I can access that file (from powershell or something?) so I can parse the test results out into a styled html document or something?

And / or is there a buildstep or something which does this out of the box?

**Comment by ManojBableshwar** [comment]
Sam,
You can access the trx files programmatically with the REST APIs - https://www.visualstudio.com/integrate/api/test/attachments#Downloadatestresultattachment

**Comment by acesiddhu** [comment]
Closing the issue. Let us know if you need more info.
