### ISSUE TITLE
Unable to run build definitions that contains 120+ build steps

### ISSUE THREAD

**Issue by qwert789** [Microsoft/vso-agent-tasks#681]
Unable to run build definitions that contains more than 120 build steps.
I'm getting an error 500:Not found  when pressing "ok button" on queue build window.
TFS.WebApi. Exception: Not Found 

Although when build definitions contains only 119 build steps is run perfectly fine..

**Comment by chrisrpatterson** [comment]
Can you give your scenario for 120 build steps beyond arbitrary limit testing?

**Comment by bryanmacfarlane** [comment]
A step in the new build system is equivalent to a developer action - invoking build on a solution or a project (which references many other projects).  

When your developers build, do they perform 120 invocations or steps to build?  

As a point of reference, for the VSO/TFS build, we have hundreds (if not thousands of projects) and developers run init.cmd and then build a root project.  A very large software project with hundreds of developers working on it.  Two steps

Further, this repository is tracking issues with the tasks, not the service.

**Comment by qwert789** [comment]
I'm sorry but it's certainly a bug, if you allow to add more than 120 build steps , why can't you run them? This behavior is very confusing !
From where this limitation is coming and why is not documented at all?
Why wouldn't you prevent a user from adding the step in the first place if such a limitation exist?

And also @babumuralidharan why should i use a "cmd file" and not to use build step which is easily configurable this also very strange , i agree maybe this is not right place to submit this issue but it's seems related to tasks also.

Thnx for response.

**Comment by chrisrpatterson** [comment]
@qwert789 you shouldn't necessarily use a cmd file, however, do your developers individually build 120+ csproj files every time they build? I have personally never worked on such a project.  Even with thousands of assemblies I have always had a single root project/solution that I can build.  Typing msubild foo.csproj at the command line 120 times many times a day seems horribly inefficient.

**Comment by qwert789** [comment]
@chrisrpatterson i'm not trying to build 120 projects , i'm trying to build 120+ solutions.
Step per solution sounds very logical to me and i believe to many people out there, why?

Because nobody want to use .target files or .proj files because it isn't configurable from GUI and also 
what if i want to see the step that currently building - currently building solution or failed (live output) if i'll do a "cmd file" i can't really know what is the progress right away.

And i don't understand why you guys talking about developer it's build server how it's even related, of course developer don't need to build 120 solution at once, but the server does for CI, NB. 
How the steps related to developer anyway -it's strange.

**Comment by bryanmacfarlane** [comment]
>> How the steps related to developer anyway -it's strange. 

It's strange and very problematic for your CI to differ from what the dev does.

So when your developer builds this locally, they go to 120 solutions and build each?  Or, can developers not pragmatically build what they are coding?

It also sounds like the feature that you need is chaining if you're building many discrete applications (many solutions).  Team City has this.

This discussion really is out of scope of this task repo.  Start an email with Chris and I.  bryanmac and chrispat and that's at microsoft dot com
