### ISSUE TITLE
Error "Invalid resource " while configuring xplat build agent on mac

### ISSUE THREAD

**Issue by AshwiniChalla** [Microsoft/vso-agent-tasks#682]
I tried configuring xplat vso agent on my mac. It gives an error "Error starting the agent. Invalid resource.". I could successfully configure on my windows by doing some hacks of removing the check for platform. Also I couldn't see any logs for the failures. Any idea why this can happen?

**Comment by bryanmacfarlane** [comment]
We need at least some details.  Inputs and output at a minimum.

**Comment by bryanmacfarlane** [comment]
reactivate if you can supply some details

**Comment by prawalagarwal** [comment]
I am getting the same issue. This happens while configuring the agent:

netcfs-mac-mini:buildagent netcf$ node agent/vsoagent.js
Enter alternate username > prawalagarwal
Enter alternate password > 
Enter server url > https://prawal.visualstudio.com
Enter agent name (enter sets netcfs-mac-mini.local)  > Agent-Mac-Xcode
Enter agent pool name (enter sets default)  > 
Error starting the agent
Invalid Resource
Shutting down host.

**Comment by prawalagarwal** [comment]
Moving this to https://github.com/Microsoft/vso-agent/issues/161
