### ISSUE TITLE
Fail build if Sonar Qube analysis fails

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#688]
Is there a way to have the build failed if the analysis run by the SonarQube for MSBuild task has failed (turned red) in Sonar?

**Comment by bgavrilMS** [comment]
Hi Pascal - can you clarify what you mean by "the analysis run failing?". Do you mean the SonarQube quality gate is broken?

**Comment by pascalberger** [comment]
Yes, the error threshold for the quality gate was reached and the Quality Gate Status in Sonar turned to Error, but the VSO build still succeeds. I'm looking for a way to have the VSO build failed in such a case.

**Comment by bgavrilMS** [comment]
Hi Pascal, 

Can you try to leverage the BuildBreaker plugin available from SonarQube? http://www.sonarsource.com/products/plugins/integration/build-breaker/

**Comment by pascalberger** [comment]
Thanks, using the BuildBreaker plugin will fail the build. 

But its not a nice integrated solution since it would result in a `Unexpected exit code received from batch file: 1` error message. The only thing the MSBuild runner returns is the summary.md file. 

It would be nice if sonar could return the breaking changes through the MSBuild runner to the build task, which afterwards can log it as real errors. But maybe this is already on your roadmap for the further integration of sonar/vso.

**Comment by bgavrilMS** [comment]
Thank you for you feedback Pascal! I will pass it on to our product managers.

**Comment by pascalberger** [comment]
Reopening this since the build breaker plugin is not compatible with the recently released 5.2 version of Sonar. 

@bgavrilMS Do you have any idea how this can be achieved with Sonar 5.2?

**Comment by bgavrilMS** [comment]
@pascalberger - Indeed, SonarQube 5.2 breaks the Build Breaker ... However, this is not something specific to the Msbuild / Build VNext integration and you'd be better helped if SonarQube engineers take a look at your question. As such - can direct your question on stackoverflow and tag it with "SonarQube" please? Then add the link here for other people wondering about this.

**Comment by pascalberger** [comment]
Thanks, question is now on [Stackoverflow](http://stackoverflow.com/questions/33495949/build-breaker-plugin-with-sonarqube-5-2).
