### ISSUE TITLE
Publish Test Results doesn't work.

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Microsoft/vso-agent-tasks#703]
I have a shell script task that creates Junit-style.xml and coverture-style.xml and Publish test results. It works fine. However if I add a Publish Code Coverage Results, it always fails before I can see "prepareWorkspace". 

Only hint for this problem is I can see an error on my VSO agent screen.

 ##[Error] 2015-10-31T07:55:01.176Z: Error: Agent could not find a handler for this task

The code must be here.

https://github.com/Microsoft/vso-agent/blob/master/src/agent/job.ts#L349
 https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/PublishCodeCoverageResults/task.json#L59

I guess this task must be only for Windows server. 
I use an Ubuntu server fas a build server.

Does it support ubuntu build server?

**Comment by atinb** [comment]
@TsuyoshiUshio 
Sorry, the Publish Code Coverage task currently only works on Windows. Support for xPlat is on our backlog. Thanks!
