### ISSUE TITLE
sonar project version variables

### ISSUE THREAD

**Issue by baywet** [Microsoft/vso-agent-tasks#743]
Hi,
I currently set my project version in the fetch task to $(MajorAndIntermediateVersion).$(Date:yyMM).$(Date:dd)$(Rev:r)

it gives me at the end in the sonar interface
6.3.$(Date:yyMM).$(Date:dd)$(Rev:r)

$(MajorAndIntermediateVersion) is a custom variable of my build definition and it works fine.
But apparently the "environment" variables don't work properly.
Thanks for your help!

**Comment by bgavrilMS** [comment]
Hi @baywet - thanks for taking the time to report this. 

1. As far as I know, $(Date:yyMM) type of variables were supported on the old build system (XAML Build). I am not sure this is supported on the new build system i.e. TFS Build. Perhaps @bryanmacfarlane can confirm.

2. SonarQube does not recommend you up your project version on every build, but instead suggests you use it for major version changes. Version is used to scope aggregation of the various metrics SonarQube collects, so you'd be missing out on trend reports etc. @duncanpMS may want to add more.

**Comment by baywet** [comment]
Hi @bgavrilMS ,
Thanks for the quick answer:
1 At least I'm using it in the Build number format and it works.
2 Ok then maybe it should have another name like branch name or something like that instead of version so it's less confusing, the tooltip also should be updated.

**Comment by bgavrilMS** [comment]
Hi @baywet - I've logged a bug https://jira.sonarsource.com/browse/TBSTFNP-24 to change the tooltip

**Comment by baywet** [comment]
Thanks for the follow up! How do you since the "backlogs" between JIRA and Github? to you update the status over here too?

**Comment by bgavrilMS** [comment]
Hi Vincent. At present the SonarQube tasks are shipped in the box to all customers so the code needs to be on this GitHub repo. As the VSO platform evolves, we're looking at moving the tasks into an extension and possibly into its own separate repo. Until then, I monitor GitHub issues and log bugs on Jira.

**Comment by dumians** [comment]
Hi, 
I'm using today sonar 6.0 with msbuild 2.1 runner on premise with CI servers TFS 2015 update 3.

On build definitions i have also version variables, and on running the sonar end task i've got
**"Analysis failed for SonarQube project "solution_all", version 5.0.$(Date:yyMM).$(Date:dd)$(Rev:r) "**

How it is posible to use this variables ?

regards,
Johannes

**Comment by bgavrilMS** [comment]
Hi, 

It's not advised that you change the SQ project version too often. The SQ version does not need to be in sync with the assembly version. SQ uses the version as a scoping mechanism for the "leak period", to differentiate between "old tech debt" and "new tech debt". If you change the version on every CI build, all the debt will be seen "old debt". So I suggest changing the version on big milestones. 

Alternatively, you can configure SQ "leak period" to be a set duration, for example the same duration as your sprint. 

Take a look at https://sonarqube.com/ to see how they configured some large open source projects.

**Comment by dumians** [comment]
hi,  
the point of the question was to use some of the  TFS build custom variables,  is that supported ?
was just an specific examples with the version

**Comment by bgavrilMS** [comment]
Please log a new issue if you want to ask about custom TFS build variables. The ones you described are not available out of the box, but it could be done by setting env variables. The core build team might know more.
