### ISSUE TITLE
NuGet Publisher does not work when running within a Release Definition

### ISSUE THREAD

**Issue by FunnyFry** [Microsoft/vso-agent-tasks#745]
In the **NuGet Publisher** task, the *VsoNuGetHelper.ps1* file intends to use the current build/release working directory to save a temporary NuGet.Config file as shown below.

```$nuGetTempDirectory = Join-Path $Env:AGENT_BUILDDIRECTORY "NuGet\"```

However, within a Release Definition, the environment variable ```AGENT_BUILDDIRECTORY``` is not defined and ```AGENT_RELEASEDIRECTORY``` should be used.

One way this could be written is below:
```
$baseDirectory = $Env:AGENT_BUILDDIRECTORY
if($baseDirectory -eq $null)
{
    $baseDirectory = $Env:AGENT_RELEASEDIRECTORY
}

$nuGetTempDirectory = Join-Path $baseDirectory "NuGet\"
```

**Comment by FunnyFry** [comment]
Forgot to mention what is logged when this fails. If you try to run the existing **NuGet Publisher** task within a Release Definition, the following error is logged multiple times.

```##[error]Cannot bind argument to parameter 'Path' because it is null.```

**Comment by omeshp** [comment]
We should be using system.artifactsdirectory which points to AGENT_BUILDDIRECTORY for build and AGENT_RELEASEDIRECTORY in case of Release.

**Comment by vtbassmatt** [comment]
Thanks @omeshp - we'll do what you proposed.

**Comment by davidpurkiss** [comment]
Yip, I'm picking up the same issue. The packages are being published correctly but the entire release fails because of the error from the **NuGet Publisher** task.

**Comment by vtbassmatt** [comment]
This has been addressed with my PR. It'll get deployed to the service in a few weeks; if anyone is blocked, you can grab the latest from GitHub and `tfx build task upload` it to your account.

**Comment by mxa0079** [comment]
@vtbassmatt Thanks for the fix! Has this been deployed to the service? (we need Task versioning as a first class citizen in VSTS/TFS. Please! =D)

**Comment by vtbassmatt** [comment]
@mxa0079 I believe it has been.

**Comment by mxa0079** [comment]
@vtbassmatt Thanks! Is there a way I can check Tasks versions myself? Do you keep a public log of task version changes?

**Comment by vtbassmatt** [comment]
For minor bugfixes, the only way to see that is to look at PRs and the code here. Once every 3 weeks, we take a snapshot and deploy that through the service. Big new stuff will be announced in [release notes](https://www.visualstudio.com/news/release-archive-vso).

I don't know any easy way to determine task versions. I ran Fiddler while the Build UI loaded, and then looked for the name of the NugetPublisher task in the resulting JSON :)

**Comment by FunnyFry** [comment]
If you have you're own build agent the tasks are downloaded with the version number in the folder name.

On Feb 18, 2016, at 11:30 AM, Matt Cooper <notifications@github.com> wrote:

For minor bugfixes, the only way to see that is to look at PRs and the code here. Once every 3 weeks, we take a snapshot and deploy that through the service. Big new stuff will be announced in release notes.

I don't know any easy way to determine task versions. I ran Fiddler while the Build UI loaded, and then looked for the name of the NugetPublisher task in the resulting JSON :)

**Comment by vtbassmatt** [comment]
@FunnyFry Ah, good call. I also realized that these tasks in particular seem to print their working folder which includes version: Set workingFolder to default: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\NuGetPackager\0.1.59

**Comment by mxa0079** [comment]
Great tips, thank you Gentlemen!
