### ISSUE TITLE
Azure Resource Group Deployment outputs as build variables

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vso-agent-tasks#788]
Is it possible to use ARM template outputs in further steps in the build?

An example would be a website name that was generated in an ARM deployment step that could then be used in an Azure Website deployment step as a variable i.e. $(arm.WebsiteName)

**Comment by chrisrpatterson** [comment]
We do not currently have that feature.

**Comment by damienpontifex** [comment]
Considering it's using azure powershell, could the output commands here https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md not be used as part of the deployment process to set the template outputs as variables?

**Comment by RoopeshNair** [comment]
@damienpontifex 

We enabled output variables support in Azure Resource Group task. Now you can refer to the output variable as $(output-variable-name) in task viz. "PowerShell on Target" in the Machines input field.

Please ensure that Azure VMs are having WinRM ports enabled.

**Comment by damienpontifex** [comment]
Great news @RoopeshNair I will try it in my builds. Thanks

**Comment by drlawler** [comment]
is the resource group name the only output parameter that is supported, or will it support other output params declared in the template?

**Comment by kedigby** [comment]
I'd like to use the outputs from the template, to update values in the app.config prior to deploying into the arm template.

**Comment by keesschollaart81** [comment]
I've just published a [https://marketplace.visualstudio.com/items?itemName=keesschollaart.arm-outputs](VSTS extension) which copies ARM Output values from the most recent deployment to VSTS variables, hope it helps!
