### ISSUE TITLE
I would like to use a scriptcs task.

### ISSUE THREAD

**Issue by aarondandy** [Microsoft/vso-agent-tasks#79]
I think it would be great to see a scriptcs task runner that uses svm, chocolatey, or anything that gets this working. I don't have privileged access to vNext Build so I can't take this on but it would enable us to better integrate our .csx build scripts with VSO and Team Build.

**Comment by chrisrpatterson** [comment]
Thanks Arron, Script CS is an interesting idea.

**Comment by aarondandy** [comment]
Did you mean to close this? I think this is a task that the community could help with when we have the ability to write our own.

**Comment by aarondandy** [comment]
Blocked by #273

**Comment by bryanmacfarlane** [comment]
We've gotten the task management tool written.  Finishing up and will publish soon.  I will focus on docs at that point.
