### ISSUE TITLE
The AndroidSigning.ps1 does not escape keystore path

### ISSUE THREAD

**Issue by khronosX** [Microsoft/vso-agent-tasks#790]
The $keystoreFile should be escaped since the jar signing tool does not handle space correctly.

$jarsignerArgs = "$jarsignerArguments -keystore $keystoreFile -signedjar $file $unsignedApk $keystoreAlias"

**Comment by khronosX** [comment]
I submitted a pull request with the fix.

**Comment by yacaovsnc** [comment]
I merged the pull request.  Thanks.
