### ISSUE TITLE
NuGet Packager fails since today with error in SonarQube.Integration.targets

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#793]
Since today some builds building NuGet packages and doing Sonar analysis fail with the following error:

    Set workingFolder to default: D:\BuildAgent\tasks\NuGetPackager\0.1.56
    Executing the powershell script: D:\BuildAgent\tasks\NuGetPackager\0.1.56\NuGetPackager.ps1
    Checking pattern is specified
    Output folder used but doesn't exists, creating it
    D:\work\0fdea3f6\a\package
    Pattern found in solution parameter.
    Find-Files -SearchPattern d:\work\0fdea3f6\NuGetPackage.Base\**\*.csproj;-:**\*tests.csproj
    Found files: 1
    --File: d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj
    Creating Nuget Arguments:
    --ARGS: pack d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj -OutputDirectory d:\work\0fdea3f6\a\package -Properties Configuration=Release;OutputPath=d:\work\0fdea3f6\a\output -Version 1.1.0-unstable0002 -Build
    Invoking nuget with pack d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj -OutputDirectory d:\work\0fdea3f6\a\package -Properties Configuration=Release;OutputPath=d:\work\0fdea3f6\a\output -Version 1.1.0-unstable0002 -Build on D:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base
    D:\BuildAgent\agent\worker\tools\NuGet.exe pack d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj -OutputDirectory d:\work\0fdea3f6\a\package -Properties Configuration=Release;OutputPath=d:\work\0fdea3f6\a\output -Version 1.1.0-unstable0002 -Build
    MSBuild auto-detection: using msbuild version '12.0' from 'C:\Program Files (x86)\MSBuild\12.0\bin'.
    Attempting to build package from 'IOZ.Base.csproj'.
    Building project 'd:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj' for target framework '.NETFramework,Version=v4.5'.
    __________________________________________________
    Project "d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj" (default targets):
    d:\work\0fdea3f6\.sonarqube\bin\targets\SonarQube.Integration.targets(162,5): error MSB4127: The "IsTestFileByName" task could not be instantiated from the assembly "d:\work\0fdea3f6\.sonarqube\bin\SonarQube.Integration.Tasks.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'SonarQube.MSBuild.Tasks.IsTestFileByName' to type 'Microsoft.Build.Framework.ITask'.
    d:\work\0fdea3f6\.sonarqube\bin\targets\SonarQube.Integration.targets(162,5): error MSB4060: The "IsTestFileByName" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
    Done building project "IOZ.Base.csproj" -- FAILED.
    ##[error]Failed to build 'IOZ.Base.csproj'.
    ##[error]Unexpected exit code 1 returned from tool NuGet.exe

The last successful build had the following log output:

    Set workingFolder to default: D:\BuildAgent\tasks\NuGetPackager\0.1.56
    Executing the powershell script: D:\BuildAgent\tasks\NuGetPackager\0.1.56\NuGetPackager.ps1
    Checking pattern is specified
    Output folder used but doesn't exists, creating it
    D:\work\0fdea3f6\a\package
    Pattern found in solution parameter.
    Find-Files -SearchPattern d:\work\0fdea3f6\NuGetPackage.Base\**\*.csproj;-:**\*tests.csproj
    Found files: 1
    --File: d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj
    Creating Nuget Arguments:
    --ARGS: pack d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj -OutputDirectory d:\work\0fdea3f6\a\package -Properties Configuration=Release;OutputPath=d:\work\0fdea3f6\a\output -Version 1.1.0-unstable0002 -Build
    Invoking nuget with pack d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj -OutputDirectory d:\work\0fdea3f6\a\package -Properties Configuration=Release;OutputPath=d:\work\0fdea3f6\a\output -Version 1.1.0-unstable0002 -Build on D:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base
    D:\BuildAgent\agent\worker\tools\NuGet.exe pack d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj -OutputDirectory d:\work\0fdea3f6\a\package -Properties Configuration=Release;OutputPath=d:\work\0fdea3f6\a\output -Version 1.1.0-unstable0002 -Build
    Attempting to build package from 'IOZ.Base.csproj'.
    Building project 'd:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj' for target framework '.NETFramework,Version=v4.5'.
    Packing files from 'd:\work\0fdea3f6\a\output'.
    Using 'IOZ.Base.nuspec' for metadata.
    Successfully created package 'd:\work\0fdea3f6\a\package\IOZ.Base.1.1.0-unstable0002.nupkg'.

There was no code change and no change of the build definition inbetween. Also task version seems to be the same. Any idea what might be causing this?

**Comment by pascalberger** [comment]
@bgavrilMS Any idea about this one? Might it be caused by the Sonnar Runner update (even though Sonar Task number is also the same between working and non-working build)?

**Comment by pascalberger** [comment]
Btw running the same command as the build does manually on the build server seems to work:

    D:\BuildAgent\agent\worker\tools\NuGet.exe pack d:\work\0fdea3f6\NuGetPackage.Base\IOZ.Base\IOZ.Base\IOZ.Base.csproj -OutputDirectory d:\work\0fdea3f6\a\package -Properties Configuration=Release;OutputPath=d:\work\0fdea3f6\a\output -Version 1.1.0-unstable0002 -Build

**Comment by bgavrilMS** [comment]
Hi @pascalberger 

Taking a look. Looks like a SonarQube related msbuild tasks is failing. + @duncanpMS for awareness.

**Comment by duncanpMS** [comment]
It looks like an MSBuild-version mismatch. The log shows that MSBuild 12.0 was detected on the build agent, but SonarQube task build can't be cast to ITask which suggests it was built against MSBuild 14.0.

@pascalberger If the code, build definition and task are all the same then something must have changed in the configuration of the agent machine or the SonarQube server. Are you using the same agent machine as before? Is the agent a hosted agent or an on-premise agent? Which version of the C# plugin do you have installed on your SonarQube server, and has it been upgraded since the last successful build?

**Comment by pascalberger** [comment]
@duncanpMS We're using an On-Prem Agent. It's the same agent as before. We changed some NodeJs stuff on the agent, but this shouldn't affect MSBuild. Otherwise Visual Studio 2013 was the first time started on the build agent, maybe this changed some environment variables?

SonarQube is Version 5.1.2 and the C# Plugin is at 4.3. The SonarQube server was not updated inbetween.

**Comment by duncanpMS** [comment]
@pascalberger It's possible I guess, although I thought VS didn't tend to set global environment variables.
Have you restarted the build agent service since VS was run for the first time? If there have been environment variable changes the build agent won't pick them up until the service is restarted.

**Comment by pascalberger** [comment]
@duncanpMS Yes, I've already restarted the build agent service afterwards

**Comment by pascalberger** [comment]
@duncanpMS You mentioned that Sonar requires VS Projects being build with MSBuild 14? We never had VS 2015 installed on this agent, which brings the question why it had worked before? 
If if there's such a requirement shouldn't the Sonar task have a corresponding demand?

**Comment by duncanpMS** [comment]
@pascalberger I've checked and the integration tasks are built against MSBuild 4.0. We deliberately build against as low a level of MSBuild as possible so we're compatible with as many clients as possible, and rely on binding redirects at runtime to select the appropriate MSBuild assemblies.

The error message does say to check that "*the host application is not missing a binding redirect for Microsoft.Build.Framework*". Normally the host application is MSBuild.exe or devenv.exe, both of which have .config files that have the appropriate binding redirects.

I don't know anything about how the NuGet packager works or what the host application is in this case. However, the logs suggest that the packager is using a different version of the MSBuild framework: the failure log contains the text *MSBuild: auto-detection: using msbuild version '12.0' from...*, which isn't present in the successful log output. Installing VS2013 will have installed MSBuild 12.0 on the agent.
The failure log reports that it is NuGet.exe which has failed, suggesting that this is the host application that should have the binding redirects.

It looks as if the NuGet task is auto-detecting the version of MSBuild to use, but isn't redirecting the assemblies to the selected version.
As a workaround, you could try creating a NuGet.exe.config file next to the NuGet.exe that contains the same redirect info that is in %PROGRAMFILES(x86)%\MSBuild\12.0\bin\msbuild.exe.config.

**Comment by pascalberger** [comment]
Thanks @duncanpMS! It builds from VSO if I add `-MSBuildVersion 4` to the `nuget pack` command. But still didn't get what was the cause of this change.

**Comment by chrisrpatterson** [comment]
It is possible that this is an issue with the new version of NuGet.  We upgraded to 3.x recently.

**Comment by pascalberger** [comment]
@chrisrpatterson Where did you upgrade? On the hosted agent? I'm using the an On-Prem agent. And since the task version has not changed I assume that the NuGet Version used by the task should also not have been changed?

**Comment by ericsciple** [comment]
The agent was updated in sprint 88 I think. So if your onprem agent was updated to 88 or higher then the version under the agent\worker\tools folder would be the new version.
