### ISSUE TITLE
Support for running tasks conditionally

### ISSUE THREAD

**Issue by jmezach** [Microsoft/vso-agent-tasks#795]
I was wondering if any support is planned for running tasks in a build conditionally. For instance, run a particular task only for the release configuration, or run a task only for a particular branch. Currently I'm putting this logic into the tasks themselves, but it would be great if this was supported by the task runner somehow making it a bit more flexible.

**Comment by bryanmacfarlane** [comment]
We do have it on our backlog to condition tasks on trigger type (CI, scheduled).

**Comment by pascalberger** [comment]
:+1: 

@bryanmacfarlane Do you plan to only condition on type of trigger (ci, scheduled) or also on trigger details like branch who triggered the build (would be really useful). 
Or more general to run tasks conditionally on any condition with support for variable expanding. This would allow to set in a first step some variables and use them later as condition.

**Comment by bryanmacfarlane** [comment]
That's why I mentioned it - feedback welcome but we want to keep it reasonable :) Variables was the other one but it might be limited to exists or equals

**Comment by jmezach** [comment]
If we could specify something like $(BuildConfiguration) equals "Release" on a task that would be extremely helpful.

**Comment by bryanmacfarlane** [comment]
OK - adding to our backlog for our service.  (not a task issue)

**Comment by dnelly** [comment]
Any updates on this?  This would be extremely helpful right now.  I could cut down on what get's copied for uploading which would save me about a gig of data transfer.

**Comment by brphelps** [comment]
@bryanmacfarlane -- Is there another issue created that replaced this?

**Comment by bryanmacfarlane** [comment]
This was implemented in agent and service so tracked there

That said it's in production now in preview.  You have to opt into new designer (user) and then enable conditional tasks ( account level ).  Opt in from context menu on profile

**Comment by bryanmacfarlane** [comment]
https://www.visualstudio.com/en-us/docs/build/concepts/process/conditions
