### ISSUE TITLE
Is it possible to populate a dropdown in the custom build step UI with some values based on another dropdown choice?

### ISSUE THREAD

**Issue by yansklyarenko** [Microsoft/vso-agent-tasks#801]
Here is the scenario: I have added a generic service endpoint, and my build step contains a field of that type. There's another multilist field, which I'd like to populate with some values depending on the service endpoint selected in the first field. 

Is this possible? Is this UI capable to populate the contents of the dropdown on the fly based on another field value? If yes, where should the code for this be placed? I would appreciate a super simple example.

Thanks!

**Comment by roniga** [comment]
Hi,
   Yes, this is possible. Do look at the DeployAzureResourceGroup task, to understand about picklist input and its corresponding source definition:
https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/DeployAzureResourceGroup/task.json
Also, look at this thread for some more info:
https://github.com/Microsoft/vso-agent-tasks/issues/667
If you have some specific issues, we can discuss them here.

**Comment by yansklyarenko** [comment]
Great, thank you! This gives me enough information to play with my custom service. I'll get back in case I have any unexpected obstacles. Thanks again for your answer!

**Comment by yansklyarenko** [comment]
Sorry for not getting back earlier on this. I investigated the samples you posted, and the mechanism is clear in general. However, I still can't make it work...

Instead of throwing the entire context onto you, I'd like to ask a couple of questions which I hope can give me some hint:

- When I create a new generic service and fill in its fields, how are those values used? Will the username/password be automatically added as basic authentication header to the endpoint request?

- Is it possible to access the attributes of the generic service from inside task.json? I mean, the Server Url I specify should be used as my endpoint URL. If that's possible, how do I reference it?

Thanks!

**Comment by roniga** [comment]
* When I create a new generic service and fill in its fields, how are those values used? Will the username/password be automatically added as basic authentication header to the endpoint request?
   Yes, the username/password is automatically added as the basic authentication header to the endpoint. You need not do anything special for it.
* Is it possible to access the attributes of the generic service from inside task.json? I mean, the Server Url I specify should be used as my endpoint URL. If that's possible, how do I reference it?
   This is not possible currently. Right now, you would have to specify the endpoint in the source definition and same server, when creating the generic service endpoint. Is there any specific scenario where you need it? In my opinion, the endpoint server name is generally always static and hence we didn't make a dynamic provision here.

**Comment by yansklyarenko** [comment]
1) Regarding basic authentication: that's clear, thank you!

2) Regarding server URL in the generic service and the endpoint: Here is my scenario. I have several TeamCity servers, running on different machines. Each server hosts a number of build projects. Each server is represented as a generic service in TFS. Now in my custom build step in vNext I would like to choose one of this generic services in the first field, and this fact should automatically populate another pickList field with the list of build projects from that server. Thus, I initially planned to place some kind of a token in the endpoint configuration, so that it gets replaced with a particular server name taken from the chosen generic service.

Anyway, I ended up authoring 2 plain edit fields, where users have to enter the URL of the TC server and the desired build project to trigger.

**Comment by thusithagh** [comment]
Apparently, most of the Microsoft VSTS related github links are broken. Even here following link gives a 404.
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployAzureResourceGroup/task.json

Would it be possible to have the correct link please?

Thank you

**Comment by kmkumaran** [comment]
You can look at all the tasks at https://github.com/Microsoft/vsts-tasks/tree/master/Tasks. For Azure RG task, https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureResourceGroupDeploymentV2 takes you to the current latest version (V2)
