### ISSUE TITLE
Make IndexSources an option in PublishSymbols task

### ISSUE THREAD

**Issue by davidjward30** [Microsoft/vso-agent-tasks#807]
It would be good if the IndexSources step was optional. We've had some performance issues with our on premises TFS and our XAML based build has the option to disable indexing of sources.

**Comment by chrisrpatterson** [comment]
Simply disable or remove the step.

**Comment by davidjward30** [comment]
Apologies if I've misunderstood, but I do want to publish symbols, but not index sources. Disabling/removing the step wont publish my symbols.

**Comment by chrisrpatterson** [comment]
Ok I misunderstood what you were referring to.

**Comment by andremarques023** [comment]
I don't know if it makes sense at all. I see no pratical benefit in publishing the symbols without index the sources. Anyway, I'm sending a PR for that.

**Comment by davidjward30** [comment]
I can confirm that we benefit from it. Indeed it's inconvenient to have to manually locate sources if we get a crash dump, but its a compromise for the problem with have with our TFS server taking 4 hours or more to index some builds.

**Comment by andremarques023** [comment]
Right, I get it. Did you see the [PR](https://github.com/Microsoft/vso-agent-tasks/pull/835)? I've added an option to the task that can help in certain situations (like yours).

**Comment by davidjward30** [comment]
Just had a look and it seems perfect. Thanks.

**Comment by bryanmacfarlane** [comment]
adding Eric who worked on the task

**Comment by andremarques023** [comment]
ping

**Comment by ericsciple** [comment]
Thanks. I've completely refactored the task in a feature branch I'm working in. I'll pull in your change as well.

**Comment by ericsciple** [comment]
This change is in production on visualstudio.com and will also be in on-premises TFS 2015 Update 2.

**Comment by andremarques023** [comment]
Nice, thanks!
