### ISSUE TITLE
Fail fast when the selected MSBuild version is 14 but only VS2013 is installed

### ISSUE THREAD

**Issue by dbolkensteyn** [Microsoft/vso-agent-tasks#812]
**Task: MSBuild** (similar issue might exist with "Visual Studio Build")

If a build with MSBuild 14 is explicitly requested in the task, but only VS2013 is installed on the build agent, then the task emits a warning stating that it is falling back to version 12, but tries to proceed. This can result in strange errors, which are harder to investigate then a quick failure with an explicit message.

**Comment by chrisrpatterson** [comment]
Thanks for the feedback.  it would be a tough thing to change now as it would likely break peoples build definitions that are working under the current behavior.  We do add a warning into the log that shows up on the front page of the build result.
