### ISSUE TITLE
PowerShell task which executes not file but script itself

### ISSUE THREAD

**Issue by anpur** [Microsoft/vso-agent-tasks#821]
As VSO user I often want to execute some PowerShell expression without having a file. It may seems like a bad practice (since that expression not in git), but it is actually really useful, especially during experiments. 

Anyway, a lot of build specific data end up in VSO steps, so it makes sense to keep short expressions there too without trashing repo.

Currently, as workaround, I use command line task, calling `powershell.exe` with `-c some-cmdlet` argument. This approach has multiple flaws (string literals require ugly escaping, you should not forget to add `-NonInteractive`, etc.) and causes following [bug/confusion](https://github.com/Microsoft/vso-agent-tasks/issues/818).

It would be great to have PowerShell task which executes not a script file but expression and shares setup with current PowerShell task (like `-NoProfile -NonInteractive`, etc.).

**Comment by RoopeshNair** [comment]
Appreciate your feedback.

One of the reasons inline script/expression weren't prioritized was due to the fact that the changes to release weren't tracked for audit yet. 

Support for inline script in lieu of PS script is in backlog. However, it might take a while before we get to it.

**Comment by bryanmacfarlane** [comment]
Closing since tracking on back log
