### ISSUE TITLE
What's the right syntax to pass a hash-table as a parameter to PowerShell build step?

### ISSUE THREAD

**Issue by yansklyarenko** [Microsoft/vso-agent-tasks#830]
Unfortunately, this syntax doesn't work:

```
-properties @{var1="a";var2="b"}
```

I've tried different combinations, but it has never succeeded. Perhaps, that's because the PowerShell build step just passes the whole `$(arguments)` as a string on without any parsing?

If there's a way to pass a hash-table as a parameter without creating a custom build step, please share. 

Thanks!

**Comment by chrisrpatterson** [comment]
Eric?

**Comment by chrisrpatterson** [comment]
It will work when the current deployment finishes rolling out over the next couple weeks.

From: Chris Patterson
Sent: Wednesday, November 18, 2015 9:41 AM
To: Microsoft/vso-agent-tasks <reply@reply.github.com>; Microsoft/vso-agent-tasks <vso-agent-tasks@noreply.github.com>; Eric Sciple <ersciple@microsoft.com>
Subject: RE: [vso-agent-tasks] What's the right syntax to pass a hash-table as a parameter to PowerShell build step? (#830)

Eric?

**Comment by ericsciple** [comment]
It will work when the current deployment finishes rolling out over the next couple weeks.

**Comment by yansklyarenko** [comment]
Great, thank you! 
Considering on-premise TFS, when should we expect this fix? Update-1?

**Comment by chrisrpatterson** [comment]
Won’t be until Update 2
