### ISSUE TITLE
"Publish artifacts" step can't find anything

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/vso-agent-tasks#832]
I have  "publish artifacts" step with minimatch pattern: `!+(*.vsix|installer.msi|installer.wixpdb|installer.exe)`
which supposed to copy everything except and vsix files and installer binaries.
Worked until yesterday, now it can’t find anything.

**Comment by chrisrpatterson** [comment]
@TingluoHuang Do you have any ideas what might be going on here?

**Comment by TingluoHuang** [comment]
try add a include all pattern at first.
**
!+(*.vsix|installer.msi|installer.wixpdb|installer.exe)

when you do a exclude matching, we expect you have some include first.
