### ISSUE TITLE
Suppress credentials / API keys from logs in tool runs like NuGet

### ISSUE THREAD

**Issue by tillig** [Microsoft/vso-agent-tasks#833]
When you run a task like the NuGet publisher the invocation of the tool logs the API key and/or credentials in the build log. Users with access to the build log may not actually have the credentials to perform the actions the build server is performing, so logging this information creates a security risk. It allows anyone with access to the build log to execute commands using the build server's credentials.

Particularly in the case of NuGet, this somewhat defeats the purpose of maintaining NuGet endpoints or credentials in the Service Endpoints repository; it's all going to get dumped out in plaintext right in the log.

**Comment by chrisrpatterson** [comment]
Hi Travis,  this was a bug in an older version of the agent.  Can you check to see which version of the agent you are currently running? If you simply restart the service it will automatically update it self.

**Comment by tillig** [comment]
From the agent capabilities page it appears the agent version is 1.90.1.

I may be missing something obvious, but I can't find the way to restart the hosted build agent process in VSO/VSTS. I've searched but only found documents on how to do that if it's a build agent I installed. Any pointers?

**Comment by chrisrpatterson** [comment]
Ok it is hosted. We are in the process of rolling out a new version of the hosted agent that has the fix.

**Comment by tillig** [comment]
Nice. It's like you guys are reading my mind. Very cool, gang, very cool.

**Comment by vtbassmatt** [comment]
Looks like this one is resolved.
