### ISSUE TITLE
VSTest and multiple appx

### ISSUE THREAD

**Issue by JamesNK** [Microsoft/vso-agent-tasks#834]
I have a solution with multiple UWP test projects. Passing multiple appx files to vstest.console results in this error:

```Error: Only one app package (.appx file) can be specified for running tests.```

There needs to be a way to specify that vstest is invoke once per file.

**Comment by chrisrpatterson** [comment]
Thanks for the feedback, For now you could put multiple VSTest tasks in the build definition.

**Comment by JamesNK** [comment]
That's what I'm doing. It doesn't automatically detect new projects like the search wildcard would though, and is more verbose.

**Comment by atinb** [comment]
This is a limitation of the vstest.console.exe runner. I suggest filing a suggestion on visualstudio.uservoice.com – this will help us gauge interest from others and set our priority appropriately.

**Comment by JamesNK** [comment]
Why can't you call the vstest exe multiple times? The user doesn't care about how it works internally

**Comment by JamesNK** [comment]
Hello? Just add an option like "Call vstest.console.exe once per file" (or whatever you'd like to label it as). Users who have this option can check that and it will work for them.

**Comment by atinb** [comment]
It can be done, but the priority is lower since a workaround exists. You could also modify the task to get the desired behavior and upload it to your account . Thanks!

**Comment by dersteve** [comment]
For everyone that ran into the same issue, here is the uservoice item you can wish for: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/15577407-vstest-console-exe-should-be-able-to-handle-multip
