### ISSUE TITLE
Passing boolean arguments to powershell task

### ISSUE THREAD

**Issue by naeemsarfraz** [Microsoft/vso-agent-tasks#836]
I have a powershell task which accepts a boolean parameter like so:

    param([bool]$param1 = $false)

In the task I have tried setting the arguments to many different combinations but all fail as the task reports:

    Cannot process argument transformation on parameter 'param1'. 
    Cannot convert value "System.String" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
    At line:1 char:100 
    + ... '1000' -param1 '0'; if ((Test-Path Variable:Global:LastExitCode)) { exit $LastEx ...

I've tried: 
* -param1 1
* -param1 $true
* -param1 $True
* -param1 "$true" 
* -param1 "$True"

Is this a bug in the task due to it quoting every argument passed to the powershell script?

**Comment by chrisrpatterson** [comment]
There is an update rolling out to VSTS at the moment that should resolve this problem.  We are sorry for the issue.

**Comment by naeemsarfraz** [comment]
Is there anything I can do for on premise? As a workaround

I have a solution which is to pass a string and then parse it as a bool. It
works but not ideal.

**Comment by chrisrpatterson** [comment]
Pass as a string and parse back to a Boolean in your script.

**Comment by ericsciple** [comment]
Closing this issue. The fix should be in production now. Please reopen if you find otherwise.
