### ISSUE TITLE
NuGetPublisher and VSTS package manager fail on xproj symbol nugets

### ISSUE THREAD

**Issue by tthiery** [Microsoft/vso-agent-tasks#846]
A ASP.Net 5 xproj creates two nupgk ... one Foobar.1.0.0.nupgk and a second Foobar.1.0.0.symbols.nupgk.

Unfortunately, the VSTS package manager cannot handle it (return 409 conflict for the symbol package after successful upload of Foobar.1.0.0.nupgk) and the file pattern for the find-file does not exclude them (AFAIK). So far I have added a build step to delete them.

Considering that the xproj will soon become a major project type, I think a better search pattern should be added.

**Comment by npnelson** [comment]
+1

**Comment by ericsciple** [comment]
Find-Files accepts exclude patterns. I'm working on some changes that will include better documentation for this. Until then, the syntax would be something like:
$(build.binariesdirectory\**\*.nupkg;-:**\*.symbols.nupkg

**Comment by npnelson** [comment]
:thumbsup:  Thanks for the tip on exclude patterns.  Now my builds report success!

**Comment by vtbassmatt** [comment]
@tthiery can those two nupkgs be successfully uploaded to NuGet.org? If they have different IDs (Foobar and Foobar.Symbols, for example) then you shouldn't see a 409 on VSTS. If they have the same ID, then they are effectively the same package and NuGet.org should not accept both of them, either. Thanks.

**Comment by tthiery** [comment]
I checked the output of the VS2015 Update 1 / .Net Core RC1 Update 1 xproj/project.json: Actually both have indeed the same id in their nuspec. just the file is named are differently. In regards of NuGet.org: Have not tried. Same id is surely a conflict there as well.

So I understand why it fails. I will file a issue on dotnet/cli.

**Comment by vtbassmatt** [comment]
Thanks.
