### ISSUE TITLE
PublishBuildArtifacts.ps1 due to missing import-module fails on Get-LocalizedString

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/vso-agent-tasks#850]
I am trying to build and publish on my own machine (not hosted build) and **everything** works just fine, but because of a missing import-module the "Publish Artifact" step 'fails' (even though it actually _did everything correctly_).

The error was that `Get-LocalizedString` could not be recognized, which is true because in order to have this available one must import `*.Common`module yet `PublishBuildArtifacts.ps1` only imports `*.Internal` module.

The missing line is the following - I was able to work around the issue by manually patching the `PublishBuildArtifacts.ps1` (but this won't work on hosted builds and will be overwritten next time we upgrade Agent software): just below `import-module "Microsoft.TeamFoundation.DistributedTask.Task.Internal"` I inserted `import-module "Microsoft.TeamFoundation.DistributedTask.Task.Common"`

Finally, purely out of curiosity, why isn't `PublishBuildArtifacts.ps1` present in the repo, it appears to be generated contrary to other similar scripts which are present in the repo?

**Comment by bryanmacfarlane** [comment]
This was fixed on the rollout of sprint 91 which has already started.

PublishBuildArtifacts.ps1 is present in the repro

In master it was renamed to CopyPublishArtifacts: https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/CopyPublishBuildArtifacts

In the released M91 branch, it's there by that name:  https://github.com/Microsoft/vso-agent-tasks/tree/releases/m91/Tasks/PublishBuildArtifacts

**Comment by ddotlic** [comment]
I'm assuming that by "rollout" you mean the agent version available online should be soon updated?

Because I downloaded the latest version of the agent (prior to opening the bug :smile:) and the change was not there - when did this rollout start? How long does it typically take?

**Comment by bryanmacfarlane** [comment]
Tasks are downloaded independently of the agent.  The fix is in the task: https://github.com/Microsoft/vso-agent-tasks/blob/releases/m91/Tasks/CopyPublishBuildArtifacts/CopyPublishBuildArtifacts.ps1 

We have scale units are the world and updates like this roll to different scale units starting with inner rings serving as canaries with the option to patch as it rolls.  Sprints are every 3 weeks and we start rolling week after sprint.  Typically takes a week + to get everywhere.

**Comment by ddotlic** [comment]
Yeah, I can see the fix, I've patched locally to get to the same result.

Now if the tasks are downloaded independently, why would there be a need of a rollout? Shouldn't the task be downloaded immediately upon release (I'm assuming you're downloading from release branch of github - using API - or something similar, I might be entirely on the wrong track of course)?

But not to drag this on forever, worst case we must wait a week until we can see the fix?
