### ISSUE TITLE
Sonar Build Runner doesn't work with /p:IsPackaging=True

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#899]
I've a build definition containing a Visual Studio Build task surrounded by the Sonar Begin Analysis and End Analysis task. The Visual Studio Build packages an application using the `/p:IsPackaging=True` property. If this property is set I get the following error from the Sonar Build Runner:

```
2015-11-27T13:23:05.9534586Z WARNING: Duplicate project GUID: "31ef7995-fdbc-4307-9024-a3d640fdf987". Check that the project is only being built for a single platform/configuration and that that the project guid is unique. The project will not be analyzed by SonarQube. 
```
Of course I could first build the solution without the `/p:IsPackaging=True` and running analysis on this and in a second step do the packaging, but this seems like a waste of resources to have to build the solutions twice. 

Any idea how I can package a project and use the same task for code analysis with Sonar?

**Comment by bgavrilMS** [comment]
Hi @pascalberger, 

What sort of project are you building? Is it an Office app / SharePoint app ?

**Comment by pascalberger** [comment]
@bgavrilMS Yes, a SharePoint provider hosted Add-In

**Comment by bgavrilMS** [comment]
Ok, I'll have a go at reproducing this. Off the bat, I think a packaging project is being created dynamically and the project GUID is the same as your SharePoint project which is confusing the SonarQube Scanner for Msbuild. 

There are a few ways of excluding projects based on name, path etc. described here https://github.com/SonarSource/sonar-.net-documentation/blob/master/doc/appendix-3.md

Also - may I ask you to open a question on StackOverflow as this is a general problem with the SonarQube Scanner for Msbuild and not really task related. Many thanks!

**Comment by pascalberger** [comment]
Thanks. Created the [StackOverflow question](http://stackoverflow.com/questions/33996594/using-sonar-msbuild-runner-with-pispackaging-true).
