### ISSUE TITLE
Copy and Publish Build Artifacts doesn't work on vso agent on Ubuntu.

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Microsoft/vso-agent-tasks#901]
Suddenly, my "Copy and aPublish Build Artifacts" definition causes an error. It worked when I tried  a few weeks before. 

I guess the reason could be the "Target Path". As I look at the log file, the "target path" is for Windows. Also, I can't see any input box for "target path" on the Visual Studio Team Services screen. 

```
[Debug] 2015-11-28T05:51:26.170Z: CopyRoot: /home/azureuser/myagent/_work/build/e7ec74aff796611c47e105ff2ed0607fe50da60075a879683e605cd12220105f/repo
##[Debug] 2015-11-28T05:51:26.171Z: Contents: **/build/libs/!(buildSrc)*.?ar
##[Debug] 2015-11-28T05:51:26.171Z: ArtifactName: drop
##[Debug] 2015-11-28T05:51:26.171Z: ArtifactType: Container
##[Debug] 2015-11-28T05:51:26.171Z: TargetPath: \\my\share\PartsUnlimitedMRP.CI\133
##[Debug] 2015-11-28T05:51:26.171Z: 
##[Debug] 2015-11-28T05:51:26.172Z: cwd: /home/azureuser/myagent/_work/build/e7ec74aff796611c47e105ff2ed0607fe50da60075a879683e605cd12220105f
```

However, On the task.json, I can see the target path definition. 

[CopyPublishBuildArtifacts/task.json](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/CopyPublishBuildArtifacts/task.json#L57-L66)

**Comment by TsuyoshiUshio** [comment]
I tried to set TargetPath using a bad know-how. However, it still didn't work. I noticed that the artifacttype should be server however, the log said that it is "Container"

----- a new log.
CopyRoot: /home/azureuser/myagent/_work/build/e7ec74aff796611c47e105ff2ed0607fe50da60075a879683e605cd12220105f/repo
Contents: **/build/libs/!(buildSrc)*.?ar
ArtifactName: drop
ArtifactType: Container
TargetPath: /home/azureuser/myagent/server
cwd: /home/azureuser/myagent/_work/build/e7ec74aff796611c47e105ff2ed0607fe50da60075a879683e605cd12220105f

**Comment by TsuyoshiUshio** [comment]
I tried File Share however, the result is the same.

CopyRoot: /home/azureuser/myagent/_work/build/e7ec74aff796611c47e105ff2ed0607fe50da60075a879683e605cd12220105f/repo
Contents: **/build/libs/!(buildSrc)*.?ar
ArtifactName: drop
ArtifactType: FilePath
TargetPath: /home/azureuser/myagent/server
cwd: /home/azureuser/myagent/_work/build/e7ec74aff796611c47e105ff2ed0607fe50da60075a879683e605cd12220105f

**Comment by TsuyoshiUshio** [comment]
I'm not sure. However, I try to find out a queue. 

https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/CopyPublishBuildArtifacts/task.json#L75-L77

Is this OK? because if we use ubuntu as a build server, it will be case sensitive.

**Comment by winguse** [comment]
@TsuyoshiUshio I found the same issues, and you are right, after modify that file on the fly, I got the copying job succeed.

**Comment by TsuyoshiUshio** [comment]
Thank you @winguse ;)

**Comment by bryanmacfarlane** [comment]
I merged the PR.  Thanks for finding it.  It will be fixed with the post holidays deployment.  Until then, you can manually change the json on the agents disk as a workaround.  We could patch if that's too much of a pain ...

**Comment by TsuyoshiUshio** [comment]
Thank you for your support,  @bryanmacfarlane. No problem. It is very easy. I have a hackathon of Visual Studio Team Services this week. So I wrote a article about how to upload the Build Task for the attendees in Japanese.  http://qiita.com/TsuyoshiUshio@github/items/c8b7d6ed05afddc30957 haha
