### ISSUE TITLE
Configure Xamarin.Android on VSO

### ISSUE THREAD

**Issue by DeveloperOne2540** [Microsoft/vso-agent-tasks#904]
Hi 
I'm setting up a CI build with VSO for my Xamarin.Forms (Android) app but I have a lot of error. I would appreciate if someone tell me how I can configure xamarin.Android build step.
what should I address in the project field? should I give project sln or in the .Droid folder .csproj ?
I could not find any document about this configuration.
![1](https://cloud.githubusercontent.com/assets/16080576/11469180/dd4b9cee-9754-11e5-97e7-9fe99584d209.png)

**Comment by yacaovsnc** [comment]
@DeveloperOne2540, 
hi what specific errors are you running into?

Specifically, the "project" field should point to the .csproj file for the android project.  If you hover over the little (i) symbols to the right of each field, there are some hints about what to do with each field.

**Comment by DeveloperOne2540** [comment]
My Dear Friend
I have solved some problem but now when I select android project .csproj I get this error "PingPong.MobileApp\PingPong.MobileApp\App.cs(6,7): Error CS0246: The type or namespace name 'Xamarin' could not be found (are you missing a using directive or an assembly reference?)"

I think that this error occurs because Xamarin.Forms.Core and Xamarin.Forms.Xaml are not in the reference.
this is error "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xamarin.Forms.Core, Version=1.3.3.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors."
I have those file in my project reference but VSO can't get those as a reference.

**Comment by yacaovsnc** [comment]
Are they nuget dependencies?  You can use "NuGet Installer" build step to restore any missing NuGet packages.

**Comment by yacaovsnc** [comment]
I am closing this issue based on non-activity.  Please reopen if you still experience problem with the task.

Thanks.
