### ISSUE TITLE
Update Pre-requisites in Windows Machine File Copy readme

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#910]
With the recent switch in the Windows Machine File Copy from WinRM to RoboCopy I think the Pre-requisites section in the [Readme](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/WindowsMachineFileCopy/README.md) is no longer valid and should be updated.

**Comment by kmkumaran** [comment]
ReadMe has been addressed. Thanks for the feedback.
