### ISSUE TITLE
Add demand for PowerShell 4

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#911]
Is it OOTB possible to add a demand for a specific PowerShell version to a custom task? My task requires PowerShell 4 and I would like to check this using a demand.

**Comment by bryanmacfarlane** [comment]
We don't have ranges yet.  At some point we will (on the backlog).  Is it possible to check the version in your script before you use anything PS4 specific?

**Comment by pascalberger** [comment]
Thanks. I'll check using `#requires` in the meantime. 

@bryanmacfarlane Should I close the issue or do you prefer to keep it open until it is possible to add a demand?

**Comment by bryanmacfarlane** [comment]
Let's close it - we have something tracking it on our backlog.  Thanks!
