### ISSUE TITLE
Update Windows Machine File Copy Readme regarding environment variable support

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#912]
Since the rewrite to RoboCopy the Windows Machine File Copy task no longer seems to support environment variables for the destination folder. This is still documented as supported in the [Readme](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/WindowsMachineFileCopy/README.md)

**Comment by kmkumaran** [comment]
Thanks for pointing out. We will address the Readme.

**Comment by kmkumaran** [comment]
Readme is now updated.

**Comment by pascalberger** [comment]
OK, will close #913 in this case
