### ISSUE TITLE
Two publish build artifact tasks available

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vso-agent-tasks#914]
With the recent deployment I now get two publish build artifact tasks available:
* Publish Build Artifacts
* Copy and Publish Build Artifacts

The former seems to be [this one](https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/PublishBuildArtifacts), the later [this one](https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/CopyPublishBuildArtifacts). Was this by design to have two tasks for nearly the same task?

**Comment by bryanmacfarlane** [comment]
Yes, "Copy and Publish Build Artifacts" is the old one.  It was renamed.

Two new tasks are available, Copy, Publish Build Artifacts which essentially offer the first one split.

Reasons you would use the new ones:
  - You want to publish build artifacts right out of the build bin without copying.  We noticed in some cases, the copy was taking longer on certain low I/O machines. 
  - You want your own custom copy process (a script), and then publish (without copy).
  - You just want copy logic (using match patterns) without writing your script and you're not publishing to the service.
  - You want multiple copy (root and patterns) and then a publish.

Used singly together they would offer the equivalent functionality of the former.

I'm writing docs right now.

**Comment by pascalberger** [comment]
Thanks, makes sense
