### ISSUE TITLE
Gulp task stopped working with Powershell

### ISSUE THREAD

**Issue by fiedler** [Microsoft/vso-agent-tasks#923]
After updating to the version 0.5.4 of the Gulp task it has stopped working for us on Windows build agents.

It exits with the following error:
`A parameter cannot be found that matches parameter name 'gulpjs'.`

It seems commit 01289943e0701f1cf33826ae977dfa6805308fe9 introduced a new parameter 'gulpjs' for the task's js implementation but the parameter is not recognised by the Powershell script.

**Comment by chrisrpatterson** [comment]
What do you mean you updated to the version?  You should not upload tasks in the repo to your own accounts or servers as they may not be compatible.

Ting, you should have updated the minimum agent version when you added a parameter for the node implementation and didn’t add the same parameter to the deprecated powershell implementation.

**Comment by bryanmacfarlane** [comment]
Noted here: https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/contribute.md 

@fiedler  - These are in the box tasks that we own deploying to the service and you will get in future Quaterly on-prem updates.  They are open sourced as reference examples of how to write tasks and help you debug.  You cannot take future tasks (master branch hasn't shipped) which is code a sprint or multiple sprints (onprem) ahead and expect it to work.  Just as you can't take a binary from a future version of a box product and just drop it into another version and expect it to work.  That's unsupported.  

The upload tool is to upload your custom tasks or a patched task that the product may hand out (we have release branches that correspond to each release).

**Comment by bryanmacfarlane** [comment]
@fiedler - can you confirm if you updated the task?

Or, are you saying you got the new sprint and now it's broken?  In that case, does updating the agent, restarting fix it?  Or are you using hosted pool?

**Comment by fiedler** [comment]
Sorry I should have been more clear.

We have the problem on a on-premise setup of TFS. I believe someone here updated the task manually and I can understand from your comments that they shouldn't have.

I think they did it to get a fix for arguments in 0c40691e5c2f25ad2960eca737ced8c3bcbd02e9.

**Comment by bryanmacfarlane** [comment]
OK - if they wanted to patch gulp with a fix for arguments then the right thing to do is patch the proper release branch.
releases/83 is RTM
releases/89 is QU1
If they do a pull request against either of those with whatever patches they need, I'll approve then it's OK to patch with those.

**Comment by bryanmacfarlane** [comment]
I need a map of branch to on-prem release on the main page <sigh>

**Comment by bryanmacfarlane** [comment]
closing - PR one of the release branches if you want
