### ISSUE TITLE
Dynamic pickList (using SourceDefinitions) is broken. 

### ISSUE THREAD

**Issue by mithunshanbhag** [Microsoft/vso-agent-tasks#934]
There are a bunch of Azure-related deployment tasks that support dynamic pickLists (via sourceDefinitions). 

Currently all of them seem to be broken, since the pickLists don't populate when I choose the Azure subscription (service endpoint with manual creds or service principal). 

Observing under fiddler, all REST calls seems to be generating HttpRequestExceptions. 

Can anyone please take a look? Please let me know if you need more details. 

# Request: 

POST https://mithuns.visualstudio.com/DefaultCollection/_apis/distributedtask/endpoint HTTP/1.1
Host: mithuns.visualstudio.com
Connection: keep-alive
Content-Length: 289
Accept: application/json;api-version=2.2-preview.1
Origin: https://mithuns.visualstudio.com
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
Content-Type: application/json
DNT: 1
Referer: https://mithuns.visualstudio.com/DefaultCollection/MithunVSOTest/_build
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Cookie: <truncated for brevity>

{"url":"https://management.core.windows.net/36a2bbab-6deb-4bf8-9c4c-b815c357b3e6/services/storageservices","selector":"xpath://ServiceName","connectionId":"b7d31e85-3530-4506-9c25-bf81ade019b9","scope":"2b7b7a04-8657-477a-8b5b-a5bd86e53b65","taskId":"2ca8fe15-42ea-4b26-80f1-e0738ec17e89"}

# Response

HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
X-TFS-ProcessId: 22c82896-5ea5-4acb-9083-c36ed9198157
Strict-Transport-Security: max-age=31536000; includeSubDomains
Access-Control-Allow-Origin: https://mithuns.visualstudio.com
Access-Control-Max-Age: 3600
Access-Control-Allow-Methods: OPTIONS,GET,POST,PATCH,PUT,DELETE
Access-Control-Expose-Headers: ActivityId,X-TFS-Session,X-MS-ContinuationToken
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: authorization
Set-Cookie: Tfs-SessionId=ac277d3a-b5db-4769-a863-41d216663d40; path=/; secure
Set-Cookie: Tfs-SessionActive=2015-12-05T22:55:45; path=/; secure
X-VSS-UserData: 2e5d16eb-7f3d-4b7c-baf0-429607fbd385:mithuns@microsoft.com
ActivityId: 0b6a36d4-cf64-46bd-8d66-ee264802e13b
X-TFS-Session: ac277d3a-b5db-4769-a863-41d216663d40
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
X-Content-Type-Options: nosniff
Date: Sat, 05 Dec 2015 22:55:45 GMT
Content-Length: 327

{"$id":"1","innerException":null,"message":"TF400898: An Internal Error Occurred. Activity Id: 0b6a36d4-cf64-46bd-8d66-ee264802e13b.","typeName":"System.Net.Http.HttpRequestException, System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"HttpRequestException","errorCode":0,"eventId":0}

**Comment by mithunshanbhag** [comment]
From an internal mail thread: 

"Dynamic picklist (using SourceDefinitions) are only supported for Azure connection using certificate. The functionality for manual creds and service principal isn’t there yet, we are planning to add it soon."

**Comment by bryanmacfarlane** [comment]
Who was on that internal mail thread?  A 500 is never an acceptable answer

**Comment by mithunshanbhag** [comment]
@bryanmacfarlane: Added you on the internal mail thread.

**Comment by roniga** [comment]
The azure tasks currently only support "Certificate" based authentication for picklist. We are working on SPN and credentials based authentication support. It should be coming up in next deployment.

**Comment by kmkumaran** [comment]
The support for drop down with SPN is available. I am marking this thread closed. Feel free to re-open if you think the issue still needs attention.
