### ISSUE TITLE
System.IO.FileNotFoundException: Unable to find Maven because the M2_HOME environment variable is set to a non-existent directory: D:\apache-maven-3.3.9

### ISSUE THREAD

**Issue by kimptoc** [Microsoft/vso-agent-tasks#955]
Hi,

I am trying to use the Maven task, but getting this error:

```
System.IO.FileNotFoundException: Unable to find Maven because the M2_HOME environment variable is set to a non-existent directory: D:\apache-maven-3.3.9
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeMavenCmdlet.GetMavenToolLocation()
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeMavenCmdlet.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
```

Its probably some basic setup I am missing, but I cannot see what.  The above M2_HOME directory does exist and I have the bin subdirectory on my path - which allows me to use the mvn command interactively.

Thanks in advance for any tips/helps.
Chris

**Comment by olivierdagenais** [comment]
Hi Chris,

I just checked the code that can raise this exception and it would indeed do so if `Directory.Exists()` returns `false`.  Can you check that the **user account that the build agent runs under** indeed has read & execute permissions to that folder and its sub-folders?

In other words, if you run `icacls D:\apache-maven-3.3.9`, do you see the name of the user account or a group it's part of?

Please report back your findings.

Thanks!
- Oli

**Comment by kimptoc** [comment]
Hi Oli,

That was it - was running the service with a basic account, no perms on the directory.

All working now.  

Many thanks for that.

Cheers,
Chris
