### ISSUE TITLE
Visual Studio Test Agent Deployment Task fails using output variable of Azure Resource Group Deployment

### ISSUE THREAD

**Issue by hrboyceiii** [Microsoft/vso-agent-tasks#969]
I have a release definition with a Resource Group Deployment that creates a new VM (Azure Resource Manager) configured with an output variable. With fix to issue #788 (PR #967) applied to an on premise agent, the output environment object causes the subsequent Test Agent Deployment Task to fail with error:

2015-12-10T21:33:37.7653475Z ##[error]Bad Request
2015-12-10T21:33:37.7653475Z ##[warning]DistributedTests: Machine Group provider failed with error : Bad Request
2015-12-10T21:33:37.7653475Z ##[warning]For troubleshooting, refer http://aka.ms/remotevstest.
2015-12-10T21:33:37.7653475Z ##[error]Initialization of machine group provider failed. Check the logs for more details.

That is the content from the task's log file.  Are there any known workarounds to this issue?

[tasklog.txt](https://github.com/Microsoft/vso-agent-tasks/files/58816/tasklog.txt)

**Comment by pryenugu** [comment]
Hi @hrboyceiii ,
We do not yet support output variables in the TestAgent deployment task. What is the input you gave in the Test Agent deployment task in the machines section?

**Comment by hrboyceiii** [comment]
I'm trying to create new test agent VMs using the ARM deployment task, referencing the Resource Group name in the machine group/resource group parameter.  When I do that, I get an error saying "the machine group does not exist", which is true and, from what I can tell, I cannot create an empty machine group (one without any machines).

How are you supposed to use this task when you are provisioning the test agent VMs using an ARM deployment??
![image](https://cloud.githubusercontent.com/assets/8991815/11746837/e145acee-9fed-11e5-8a51-03f457921c05.png)
![image](https://cloud.githubusercontent.com/assets/8991815/11746861/f9ca103e-9fed-11e5-8157-523cc9622434.png)

[deployTestAgentNewResourceGroup.txt](https://github.com/Microsoft/vso-agent-tasks/files/59515/deployTestAgentNewResourceGroup.txt)

**Comment by atinb** [comment]
@hrboyceiii 
The Test Agent Deployment task currently does not support output variables. This is on our backlog and will be addressed in the next 2-3 sprints. Till then, you can create a machine group with pre-provisioned Azure machines and use the same in the task. 
Thanks!

**Comment by hrboyceiii** [comment]
Is there any update on this? I have been working with multiple customers since original post that would like this capability. Thanks for the update!

**Comment by atinb** [comment]
This functionality will be available with the deployment for next sprint (around 2-3 weeks from now)
